export default [
  // {
  //   name: "Biblia de estudio hebrea interlineal con vocales, acentos, transliteración y número Strong",
  //   url: "_dl.php?back=bbl&a=HSB_plus_&b=mybible&c",
  //   key: "HSB+",
  //   size: 5459189,
  //   storedName: "HSB+",
  // },
  {
    name: "Nueva Biblia al Día",
    url: "_dl.php?back=bbl&a=NBD'08&b=mybible&c",
    key: "NBD",
    size: 2066515,
    storedName: "NBD'08",
  },
  {
    name: "Sagradas Escrituras. La Biblia del Oso",
    url: "_dl.php?back=bbl&a=BDO'1573&b=mybible&c",
    key: "BDO",
    size: 3221980,
    storedName: "BDO'1573",
  },
  {
    name: "Dios Habla Hoy Con Deuterocanónicos Versión Española",
    url: "_dl.php?back=bbl&a=DHHED&b=mybible&c",
    key: "DHHED",
    size: 4146483,
    storedName: "DHHED",
  },
  {
    name: "La Biblia Dios Habla Hoy (Castellano Peninsular)",
    url: "_dl.php?back=bbl&a=DHHE&b=mybible&c",
    key: "DHHE",
    size: 1718131,
    storedName: "DHHE",
  },
  {
    name: "Biblia Dios Habla Hoy",
    url: "_dl.php?back=bbl&a=DHHD&b=mybible&c",
    key: "DHHD",
    size: 2413808,
    storedName: "DHHD",
  },
  {
    name: "Dios habla Hoy Estándar",
    url: "_dl.php?back=bbl&a=DHHS'94&b=mybible&c",
    key: "DHHS",
    size: 2583954,
    storedName: "DHHS'94",
  },
  {
    name: "La Biblia Hispanoamericana (Traducción Interconfesional, versión hispanoamericana)",
    url: "_dl.php?back=bbl&a=BHTI&b=mybible&c",
    key: "BHTI",
    size: 2445032,
    storedName: "BHTI",
  },
  {
    name: "La Biblia, Traducción Interconfesional",
    url: "_dl.php?back=bbl&a=BTI-es&b=mybible&c",
    key: "BTI",
    size: 2626421,
    storedName: "BTI-es",
  },
  {
    name: "Traducciόn En Lenguaje Actual con Deuterocanónicos",
    url: "_dl.php?back=bbl&a=TLAD&b=mybible&c",
    key: "TLAD",
    size: 2653757,
    storedName: "TLAD",
  },
  {
    name: "Sagrada Biblia",
    url: "_dl.php?back=bbl&a=EUNSA&b=mybible&c",
    key: "EUNSA",
    size: 6454260,
    storedName: "EUNSA",
  },
  {
    name: "La Palabra",
    url: "_dl.php?back=bbl&a=BLP&b=mybible&c",
    key: "BLP",
    size: 2131030,
    storedName: "BLP",
  },
  {
    name: "La Palabra Hispanoamericana",
    url: "_dl.php?back=bbl&a=BLPH&b=mybible&c",
    key: "BLPH",
    size: 2126071,
    storedName: "BLPH",
  },
  {
    name: "Biblia del Siglo de Oro",
    url: "_dl.php?back=bbl&a=BSO&b=mybible&c",
    key: "BSO",
    size: 1876498,
    storedName: "BSO",
  },
  {
    name: "La Biblia Textual",
    url: "_dl.php?back=bbl&a=BTX&b=mybible&c",
    key: "BTX",
    size: 1890904,
    storedName: "BTX",
  },
  {
    name: "Sagradas Escrituras. La Biblia del Oso",
    url: "_dl.php?back=bbl&a=ESE&b=mybible&c",
    key: "ESE",
    size: 1837625,
    storedName: "ESE",
  },
  {
    name: "Jünemann Septuaginta en español",
    url: "_dl.php?back=bbl&a=JSE&b=mybible&c",
    key: "JSE",
    size: 1880666,
    storedName: "JSE",
  },
  {
    name: "Traducción Kadosh Israelita Mesiánica",
    url: "_dl.php?back=bbl&a=KDSH&b=mybible&c",
    key: "KDSH",
    size: 2059524,
    storedName: "KDSH",
  },
  {
    name: "La Biblia de las Américas",
    url: "_dl.php?back=bbl&a=LBLA_plus_&b=mybible&c",
    key: "LBLA_plus_",
    size: 5869767,
    storedName: "LBLA_plus_",
  },
  {
    name: "Nueva Biblia de los Hispanos",
    url: "_dl.php?back=bbl&a=NBdLH&b=mybible&c",
    key: "NBdLH",
    size: 1929070,
    storedName: "NBdLH",
  },
  {
    name: "Nueva Biblia de los Hispanos",
    url: "_dl.php?back=bbl&a=NBLH&b=mybible&c",
    key: "NBLH",
    size: 3898449,
    storedName: "NBLH",
  },
  {
    name: "Nueva Traducción Viviente",
    url: "_dl.php?back=bbl&a=NTV&b=mybible&c",
    key: "NTV",
    size: 2393963,
    storedName: "NTV",
  },
  {
    name: "La Santa Biblia (Nueva Versión Internacional)",
    url: "_dl.php?back=bbl&a=NVI&b=mybible&c",
    key: "NVI",
    size: 2383835,
    storedName: "NVI",
  },
  {
    name: "Nueva Versión Internacional (Castellano)",
    url: "_dl.php?back=bbl&a=NVIC'17&b=mybible&c",
    key: "NVIC",
    size: 2274828,
    storedName: "NVIC'17",
  },
  {
    name: "Sagradas Escrituras Version Antigua",
    url: "_dl.php?back=bbl&a=SEVA&b=mybible&c",
    key: "SEVA",
    size: 1904975,
    storedName: "SEVA",
  },
  {
    name: "Traducción en Lenguaje Actual",
    url: "_dl.php?back=bbl&a=TLA&b=mybible&c",
    key: "TLA",
    size: 1920083,
    storedName: "TLA",
  },
  {
    name: "Las Sagradas Escrituras — Versión Israelita Nazarena",
    url: "_dl.php?back=bbl&a=VIN&b=mybible&c",
    key: "VIN",
    size: 1922105,
    storedName: "VIN",
  },
  {
    name: "La Biblia",
    url: "_dl.php?back=bbl&a=Ausejo&b=mybible&c",
    key: "Ausejo",
    size: 1958004,
    storedName: "Ausejo",
  },
  {
    name: "Biblia al día",
    url: "_dl.php?back=bbl&a=BAD'1989&b=mybible&c",
    key: "BAD",
    size: 2047370,
    storedName: "BAD'1989",
  },
  {
    name: "La Biblia del Oso",
    url: "_dl.php?back=bbl&a=BDO'1569&b=mybible&c",
    key: "BDO",
    size: 1928338,
    storedName: "BDO'1569",
  },
  {
    name: "Biblia de Jerusalem 3-Edicion",
    url: "_dl.php?back=bbl&a=BJ3&b=mybible&c",
    key: "BJ3",
    size: 1917027,
    storedName: "BJ3",
  },
  {
    name: "Biblia Latinoamericana",
    url: "_dl.php?back=bbl&a=BL'1995&b=mybible&c",
    key: "BL",
    size: 1960493,
    storedName: "BL'1995",
  },
  {
    name: "Biblia de nuestro Pueblo",
    url: "_dl.php?back=bbl&a=BNP&b=mybible&c",
    key: "BNP",
    size: 1903051,
    storedName: "BNP",
  },
  {
    name: "La Biblia Textual 3a Edicion",
    url: "_dl.php?back=bbl&a=BTX3&b=mybible&c",
    key: "BTX3",
    size: 1977703,
    storedName: "BTX3",
  },
  {
    name: "Biblia Castilian",
    url: "_dl.php?back=bbl&a=CAB'2003&b=mybible&c",
    key: "CAB",
    size: 1946543,
    storedName: "CAB'2003",
  },
  {
    name: "Biblia Corona de Jerusalen",
    url: "_dl.php?back=bbl&a=CJ&b=mybible&c",
    key: "CJ",
    size: 1910252,
    storedName: "CJ",
  },
  {
    name: "El Libro del Pueblo de Dios",
    url: "_dl.php?back=bbl&a=LPD&b=mybible&c",
    key: "LPD",
    size: 1991776,
    storedName: "LPD",
  },
  {
    name: "Biblia Septuaginta al Español",
    url: "_dl.php?back=bbl&a=LXX-es&b=mybible&c",
    key: "LXX",
    size: 1869968,
    storedName: "LXX-es",
  },
  {
    name: "Nacar-Colunga",
    url: "_dl.php?back=bbl&a=N-C&b=mybible&c",
    key: "N",
    size: 1919194,
    storedName: "N-C",
  },
  {
    name: "Biblia de Jerusalén",
    url: "_dl.php?back=bbl&a=NBJ'1998&b=mybible&c",
    key: "NBJ",
    size: 1917027,
    storedName: "NBJ'1998",
  },
  {
    name: "Biblia de Jerusalén",
    url: "_dl.php?back=bbl&a=BJ'1975&b=mybible&c",
    key: "BJ",
    size: 2152118,
    storedName: "BJ'1975",
  },
  {
    name: "Biblia Platense",
    url: "_dl.php?back=bbl&a=Platense&b=mybible&c",
    key: "Platense",
    size: 2224007,
    storedName: "Platense",
  },
  {
    name: "Versión oficial de la Conferencia Episcopal Española",
    url: "_dl.php?back=bbl&a=CEE'11&b=mybible&c",
    key: "CEE",
    size: 3711485,
    storedName: "CEE'11",
  },
  {
    name: "Torres Amat",
    url: "_dl.php?back=bbl&a=TA&b=mybible&c",
    key: "TA",
    size: 2499213,
    storedName: "TA",
  },
  {
    name: "Catolica Biblia de Jerusalén",
    url: "_dl.php?back=bbl&a=BJ&b=mybible&c",
    key: "BJ",
    size: 1885092,
    storedName: "BJ",
  },
  {
    name: "Sagrada Biblia — Versión de la LXX al español — por Guillermo Jünemann",
    url: "_dl.php?back=bbl&a=JLXX&b=mybible&c",
    key: "JLXX",
    size: 1890963,
    storedName: "JLXX",
  },
  {
    name: "Nueva Reina Valera (Adventista)",
    url: "_dl.php?back=bbl&a=NRV'1990&b=mybible&c",
    key: "NRV",
    size: 1930443,
    storedName: "NRV'1990",
  },
  {
    name: "Reina Valera Independiente",
    url: "_dl.php?back=bbl&a=RVI'12&b=mybible&c",
    key: "RVI",
    size: 2043354,
    storedName: "RVI'12",
  },
  {
    name: "La Santa Biblia",
    url: "_dl.php?back=bbl&a=SBMN&b=mybible&c",
    key: "SBMN",
    size: 1956280,
    storedName: "SBMN",
  },
  {
    name: "Biblia Universidad de Jerusalem",
    url: "_dl.php?back=bbl&a=SBVUJ&b=mybible&c",
    key: "SBVUJ",
    size: 1926286,
    storedName: "SBVUJ",
  },
  {
    name: "Nueva Biblia Española",
    url: "_dl.php?back=bbl&a=SM'1975&b=mybible&c",
    key: "SM",
    size: 1870437,
    storedName: "SM'1975",
  },
  {
    name: "La Biblia (Spanish Sagradas Escrituras)",
    url: "_dl.php?back=bbl&a=SSE&b=mybible&c",
    key: "SSE",
    size: 1906189,
    storedName: "SSE",
  },
  {
    name: "Versión Israelita Nazarena",
    url: "_dl.php?back=bbl&a=VIN'2011&b=mybible&c",
    key: "VIN",
    size: 1999785,
    storedName: "VIN'2011",
  },
  {
    name: "Version Moderna",
    url: "_dl.php?back=bbl&a=VM'1929&b=mybible&c",
    key: "VM",
    size: 2023244,
    storedName: "VM'1929",
  },
  {
    name: "Español Palabra de Dios para Todos",
    url: "_dl.php?back=bbl&a=PDT&b=mybible&c",
    key: "PDT",
    size: 2253793,
    storedName: "PDT",
  },
  {
    name: "Biblia Textual IV edición | BTX IV",
    url: "_dl.php?back=bbl&a=BTX4&b=mybible&c",
    key: "BTX4",
    size: 20409965,
    storedName: "BTX4",
  },
  {
    name: "Nueva Biblia Viva",
    url: "_dl.php?back=bbl&a=NBV'08&b=mybible&c",
    key: "NBV",
    size: 2070975,
    storedName: "NBV'08",
  },
  {
    name: "Nueva Version Internacional",
    url: "_dl.php?back=bbl&a=NVI'1984&b=mybible&c",
    key: "NVI",
    size: 1980941,
    storedName: "NVI'1984",
  },
  {
    name: "Nueva Versión Internacional",
    url: "_dl.php?back=bbl&a=NVI'15&b=mybible&c",
    key: "NVI",
    size: 2330516,
    storedName: "NVI'15",
  },
  {
    name: "Nueva Versión Internacional Simplificada",
    url: "_dl.php?back=bbl&a=NVI-S'19&b=mybible&c",
    key: "NVI",
    size: 649494,
    storedName: "NVI-S'19",
  },
  {
    name: "Reina-Valera 2017 de Russel Stendal and Larry Pierce",
    url: "_dl.php?back=bbl&a=RV'17_plus_&b=mybible&c",
    key: "RV",
    size: 2767992,
    storedName: "RV'17_plus_",
  },
  {
    name: "Biblia Reina Valera",
    url: "_dl.php?back=bbl&a=RV1909&b=mybible&c",
    key: "RV1909",
    size: 2864587,
    storedName: "RV1909",
  },
  {
    name: "Reina Valera",
    url: "_dl.php?back=bbl&a=RV'77&b=mybible&c",
    key: "RV",
    size: 1946563,
    storedName: "RV'77",
  },
  {
    name: "Reina Valera Actualizada",
    url: "_dl.php?back=bbl&a=RVA'15&b=mybible&c",
    key: "RVA",
    size: 2132858,
    storedName: "RVA'15",
  },
  {
    name: "Nueva Reina Valera",
    url: "_dl.php?back=bbl&a=NRV&b=mybible&c",
    key: "NRV",
    size: 1803229,
    storedName: "NRV",
  },
  {
    name: "Reina-Valera",
    url: "_dl.php?back=bbl&a=RV'09_plus_&b=mybible&c",
    key: "RV",
    size: 2732947,
    storedName: "RV'09_plus_",
  },
  {
    name: "La Santa Biblia Reina-Valera",
    url: "_dl.php?back=bbl&a=RV'60_plus_&b=mybible&c",
    key: "RV",
    size: 2947330,
    storedName: "RV'60_plus_",
  },
  {
    name: "Reina-Valera",
    url: "_dl.php?back=bbl&a=RV'65&b=mybible&c",
    key: "RV",
    size: 1836432,
    storedName: "RV'65",
  },
  {
    name: "La Santa Biblia Reina-Valera",
    url: "_dl.php?back=bbl&a=RV1865&b=mybible&c",
    key: "RV1865",
    size: 1682379,
    storedName: "RV1865",
  },
  {
    name: "Reina Valera (Nuevo Testamento)",
    url: "_dl.php?back=bbl&a=RV'1858&b=mybible&c",
    key: "RV",
    size: 473569,
    storedName: "RV'1858",
  },
  {
    name: "Reina Valera",
    url: "_dl.php?back=bbl&a=RV'1862&b=mybible&c",
    key: "RV",
    size: 1886473,
    storedName: "RV'1862",
  },
  {
    name: "La Santa Biblia Reina Valera Revisión",
    url: "_dl.php?back=bbl&a=RV'95&b=mybible&c",
    key: "RV",
    size: 2059374,
    storedName: "RV'95",
  },
  {
    name: "Reina Valera",
    url: "_dl.php?back=bbl&a=RV'2000&b=mybible&c",
    key: "RV",
    size: 1915375,
    storedName: "RV'2000",
  },
  {
    name: "Reina Valera",
    url: "_dl.php?back=bbl&a=RV'2004&b=mybible&c",
    key: "RV",
    size: 1892804,
    storedName: "RV'2004",
  },
  {
    name: "Reina Valera Actualizada",
    url: "_dl.php?back=bbl&a=RVA&b=mybible&c",
    key: "RVA",
    size: 1929235,
    storedName: "RVA",
  },
  {
    name: "Reina Valera Antigua",
    url: "_dl.php?back=bbl&a=RVA'1602&b=mybible&c",
    key: "RVA",
    size: 1906975,
    storedName: "RVA'1602",
  },
  {
    name: "Reina Valera Contemporánea",
    url: "_dl.php?back=bbl&a=RVC&b=mybible&c",
    key: "RVC",
    size: 2187446,
    storedName: "RVC",
  },
  {
    name: "Reina Valera Gómez",
    url: "_dl.php?back=bbl&a=RVG'04&b=mybible&c",
    key: "RVG",
    size: 1854050,
    storedName: "RVG'04",
  },
  {
    name: "Reina-Valera 1602 Purificada",
    url: "_dl.php?back=bbl&a=RVP&b=mybible&c",
    key: "RVP",
    size: 1897386,
    storedName: "RVP",
  },
  {
    name: "Español Reina Valera",
    url: "_dl.php?back=bbl&a=RVR&b=mybible&c",
    key: "RVR",
    size: 1853137,
    storedName: "RVR",
  },
  {
    name: "La Santa Biblia Reina Valera Revisión, con títulos",
    url: "_dl.php?back=bbl&a=RVR60&b=mybible&c",
    key: "RVR60",
    size: 2164551,
    storedName: "RVR60",
  },
  {
    name: "El Nuevo Testamento",
    url: "_dl.php?back=bbl&a=NTPB&b=mybible&c",
    key: "NTPB",
    size: 462242,
    storedName: "NTPB",
  },
  {
    name: "El Nuevo Testamento, Versión Biblia Libre",
    url: "_dl.php?back=bbl&a=VBL&b=mybible&c",
    key: "VBL",
    size: 570778,
    storedName: "VBL",
  },
  {
    name: "Peshita (Nuevo Testamento)",
    url: "_dl.php?back=bbl&a=Pesh-es&b=mybible&c",
    key: "Pesh",
    size: 511870,
    storedName: "Pesh-es",
  },
  {
    name: "Arcas-Fernandez (Nuevo Testamento)",
    url: "_dl.php?back=bbl&a=AFNT&b=mybible&c",
    key: "AFNT",
    size: 531179,
    storedName: "AFNT",
  },
  {
    name: "Lenguaje Sencillo (Nuevo Testamento)",
    url: "_dl.php?back=bbl&a=BLSNT&b=mybible&c",
    key: "BLSNT",
    size: 536172,
    storedName: "BLSNT",
  },
  {
    name: "Brit Xadasha Judia Ortodoxa (Nuevo Testamento)",
    url: "_dl.php?back=bbl&a=BXJO&b=mybible&c",
    key: "BXJO",
    size: 501558,
    storedName: "BXJO",
  },
  {
    name: "EUNSA (Nuevo Testamento)",
    url: "_dl.php?back=bbl&a=EUNSA&b=mybible&c",
    key: "EUNSA",
    size: 6454260,
    storedName: "EUNSA",
  },
  {
    name: "El Codigo Real - Nuevo Testamento Textual Hebraico",
    url: "_dl.php?back=bbl&a=CDG&b=mybible&c",
    key: "CDG",
    size: 543613,
    storedName: "CDG",
  },
  {
    name: "Nueva Traducción Viviente",
    url: "_dl.php?back=bbl&a=NTV'10&b=mybible&c",
    key: "NTV",
    size: 2393884,
    storedName: "NTV'10",
  },
  {
    name: "Biblia de Israel (Solo Genesis)",
    url: "_dl.php?back=bbl&a=BDI&b=mybible&c",
    key: "BDI",
    size: 98256,
    storedName: "BDI",
  },
  {
    name: "DuTillet — Solo Mateo — Hebreo",
    url: "_dl.php?back=bbl&a=DuTillet&b=mybible&c",
    key: "DuTillet",
    size: 71969,
    storedName: "DuTillet",
  },
  {
    name: "Scio de San Miguel",
    url: "_dl.php?back=bbl&a=SCIO&b=mybible&c",
    key: "SCIO",
    size: 239031,
    storedName: "SCIO",
  },
  {
    name: "La Torah",
    url: "_dl.php?back=bbl&a=TORAH&b=mybible&c",
    key: "TORAH",
    size: 345022,
    storedName: "TORAH",
  },
  {
    name: "Bizantino interlineal griego-español",
    url: "_dl.php?back=bbl&a=iBY_plus_&b=mybible&c",
    key: "iBY_plus_",
    size: 1312204,
    storedName: "iBY_plus_",
  },
  {
    name: "NA27 interlineal griego-español",
    url: "_dl.php?back=bbl&a=iNA27_plus_&b=mybible&c",
    key: "iNA27_plus_",
    size: 1335954,
    storedName: "iNA27_plus_",
  },
  {
    name: "Westcott y Hort interlineal griego-español",
    url: "_dl.php?back=bbl&a=inWH_plus_&b=mybible&c",
    key: "inWH_plus_",
    size: 1322972,
    storedName: "inWH_plus_",
  },
  {
    name: "Tischendorf interlineal griego-español",
    url: "_dl.php?back=bbl&a=iTisch_plus_&b=mybible&c",
    key: "iTisch_plus_",
    size: 1317022,
    storedName: "iTisch_plus_",
  },
  {
    name: "Títulos de Reina Valera",
    url: "_dl.php?back=bbl&a=RV60-s.subheadings&b=mybible&c",
    key: "RV60",
    size: 71594,
    storedName: "RV60-s.subheadings",
  },
  {
    name: "Diccionario de Religiones, Denominaciones y Sectas",
    url: "_dl.php?back=bbl&a=RDS.dictionary&b=mybible&c",
    key: "RDS",
    size: 231615,
    storedName: "RDS.dictionary",
  },
  {
    name: "Barclay Palabras Griegas del Nuevo Testamento",
    url: "_dl.php?back=bbl&a=Barclay.dictionary&b=mybible&c",
    key: "Barclay",
    size: 426773,
    storedName: "Barclay.dictionary",
  },
  {
    name: "Babylon Spanish-English",
    url: "_dl.php?back=bbl&a=es-en-B.dictionary&b=mybible&c",
    key: "es",
    size: 2321065,
    storedName: "es-en-B.dictionary",
  },
  {
    name: "Diccionario Clave - Diccionario de uso del espanol actual (con sinonimos y antonimos)",
    url: "_dl.php?back=bbl&a=Clave.dictionary&b=mybible&c",
    key: "Clave",
    size: 8265896,
    storedName: "Clave.dictionary",
  },
  {
    name: "Diccionario Hispano-Americano de la Misión",
    url: "_dl.php?back=bbl&a=DHAM.dictionary&b=mybible&c",
    key: "DHAM",
    size: 522928,
    storedName: "DHAM.dictionary",
  },
  {
    name: "Concordancia Biblica",
    url: "_dl.php?back=bbl&a=Conc.dictionary&b=mybible&c",
    key: "Conc",
    size: 1080614,
    storedName: "Conc.dictionary",
  },
  {
    name: "Diccionario Teológico Enciclopédico",
    url: "_dl.php?back=bbl&a=DTE.dictionary&b=mybible&c",
    key: "DTE",
    size: 1698898,
    storedName: "DTE.dictionary",
  },
  {
    name: "Nuevo Diccionario Bíblico Vila-Escuaín",
    url: "_dl.php?back=bbl&a=NDBI.dictionary&b=mybible&c",
    key: "NDBI",
    size: 2047346,
    storedName: "NDBI.dictionary",
  },
  {
    name: "Gran diccionario enciclopédico Time Life",
    url: "_dl.php?back=bbl&a=TL-GDE.dictionary&b=mybible&c",
    key: "TL",
    size: 3375493,
    storedName: "TL-GDE.dictionary",
  },
  {
    name: "Sinónimos y antónimos TIME LIFE",
    url: "_dl.php?back=bbl&a=TL-SyA.dictionary&b=mybible&c",
    key: "TL",
    size: 55522,
    storedName: "TL-SyA.dictionary",
  },
  {
    name: "Vocabulario de teología bíblica",
    url: "_dl.php?back=bbl&a=VdTB.dictionary&b=mybible&c",
    key: "VdTB",
    size: 1109752,
    storedName: "VdTB.dictionary",
  },
  {
    name: "Vocabulario de las epístolas paulinas",
    url: "_dl.php?back=bbl&a=VocEP.dictionary&b=mybible&c",
    key: "VocEP",
    size: 93348,
    storedName: "VocEP.dictionary",
  },
  {
    name: "Diccionario de la Real Academia Española",
    url: "_dl.php?back=bbl&a=DRAE.dictionary&b=mybible&c",
    key: "DRAE",
    size: 8562950,
    storedName: "DRAE.dictionary",
  },
  {
    name: "Diccionario Apologético",
    url: "_dl.php?back=bbl&a=Apologét.dictionary&b=mybible&c",
    key: "Apologét",
    size: 126879,
    storedName: "Apologét.dictionary",
  },
  {
    name: "Diccionario de Patrística",
    url: "_dl.php?back=bbl&a=DiPat.dictionary&b=mybible&c",
    key: "DiPat",
    size: 134656,
    storedName: "DiPat.dictionary",
  },
  {
    name: "Nueva Concordancia Strong Exhaustiva",
    url: "_dl.php?back=bbl&a=NCSE.dictionary&b=mybible&c",
    key: "NCSE",
    size: 7518086,
    storedName: "NCSE.dictionary",
  },
  {
    name: "Significado dos nomes",
    url: "_dl.php?back=bbl&a=Nomes.dictionary&b=mybible&c",
    key: "Nomes",
    size: 159297,
    storedName: "Nomes.dictionary",
  },
  {
    name: "Multiléxico Strong-Chávez-Tuggy-Vine-Swanson",
    url: "_dl.php?back=bbl&a=Multi.dictionary&b=mybible&c",
    key: "Multi",
    size: 6053214,
    storedName: "Multi.dictionary",
  },
  {
    name: "Concordancia facilitada por Ministerios Ebenezer",
    url: "_dl.php?back=bbl&a=CFME.dictionary&b=mybible&c",
    key: "CFME",
    size: 777393,
    storedName: "CFME.dictionary",
  },
  {
    name: "Nuevo Diccionario Biblico",
    url: "_dl.php?back=bbl&a=DAL.dictionary&b=mybible&c",
    key: "DAL",
    size: 1793417,
    storedName: "DAL.dictionary",
  },
  {
    name: "Comentario Biblico Siglo Ventiuno",
    url: "_dl.php?back=bbl&a=SXXI.dictionary&b=mybible&c",
    key: "SXXI",
    size: 2872675,
    storedName: "SXXI.dictionary",
  },
  {
    name: "Diccionario bíblico: Mundo Hispano",
    url: "_dl.php?back=bbl&a=DBMH.dictionary&b=mybible&c",
    key: "DBMH",
    size: 1383125,
    storedName: "DBMH.dictionary",
  },
  {
    name: "Diccionario de Nombres Bíblicos Hitchcock",
    url: "_dl.php?back=bbl&a=DNBH.dictionary&b=mybible&c",
    key: "DNBH",
    size: 57341,
    storedName: "DNBH.dictionary",
  },
  {
    name: "Diccionario Enciclopédico Ibalpe",
    url: "_dl.php?back=bbl&a=IBALPE.dictionary&b=mybible&c",
    key: "IBALPE",
    size: 5268639,
    storedName: "IBALPE.dictionary",
  },
  {
    name: "Mapas bíblicos",
    url: "_dl.php?back=bbl&a=LDS-es.dictionary&b=mybible&c",
    key: "LDS",
    size: 14312799,
    storedName: "LDS-es.dictionary",
  },
  {
    name: "Diccionario Vine Nuevo Testamento VINE GR-ES",
    url: "_dl.php?back=bbl&a=VineNT-es.dictionary&b=mybible&c",
    key: "VineNT",
    size: 1686279,
    storedName: "VineNT-es.dictionary",
  },
  {
    name: "Diccionario Antiguo Testamento VINE HE-ES",
    url: "_dl.php?back=bbl&a=VineAT-es.dictionary&b=mybible&c",
    key: "VineAT",
    size: 623916,
    storedName: "VineAT-es.dictionary",
  },
  {
    name: "Mujeres de la Biblia",
    url: "_dl.php?back=bbl&a=MdlB.dictionary&b=mybible&c",
    key: "MdlB",
    size: 99187,
    storedName: "MdlB.dictionary",
  },
  {
    name: "Diccionario Abreviado de Pastoral Católica",
    url: "_dl.php?back=bbl&a=DAP.dictionary&b=mybible&c",
    key: "DAP",
    size: 56563,
    storedName: "DAP.dictionary",
  },
  {
    name: "Diccionario Biblico Arqueologico",
    url: "_dl.php?back=bbl&a=DBA-CH.dictionary&b=mybible&c",
    key: "DBA",
    size: 860987,
    storedName: "DBA-CH.dictionary",
  },
  {
    name: "Diccionario de la evangelización",
    url: "_dl.php?back=bbl&a=DEVA.dictionary&b=mybible&c",
    key: "DEVA",
    size: 698915,
    storedName: "DEVA.dictionary",
  },
  {
    name: "Diccionario Nombres Segun RV",
    url: "_dl.php?back=bbl&a=DicRV.dictionary&b=mybible&c",
    key: "DicRV",
    size: 220005,
    storedName: "DicRV.dictionary",
  },
  {
    name: "Diccionario Mini Biografias",
    url: "_dl.php?back=bbl&a=DMB.dictionary&b=mybible&c",
    key: "DMB",
    size: 43456,
    storedName: "DMB.dictionary",
  },
  {
    name: "Diccionario Nelson",
    url: "_dl.php?back=bbl&a=Nelson.dictionary&b=mybible&c",
    key: "Nelson",
    size: 1718129,
    storedName: "Nelson.dictionary",
  },
  {
    name: "Diccionario Biblico de las Américas 2000 Indice de Topicos",
    url: "_dl.php?back=bbl&a=LBLA2000.dictionary&b=mybible&c",
    key: "LBLA2000",
    size: 665484,
    storedName: "LBLA2000.dictionary",
  },
  {
    name: "Un gran diccionario español-ruso",
    url: "_dl.php?back=bbl&a=es-ru.dictionary&b=mybible&c",
    key: "es",
    size: 6215447,
    storedName: "es-ru.dictionary",
  },
  {
    name: "diccionario Español-Inglés",
    url: "_dl.php?back=bbl&a=es-en.dictionary&b=mybible&c",
    key: "es",
    size: 752361,
    storedName: "es-en.dictionary",
  },
  {
    name: "Diccionario Strong en Español",
    url: "_dl.php?back=bbl&a=Strong-ES.dictionary&b=mybible&c",
    key: "Strong",
    size: 1558073,
    storedName: "Strong-ES.dictionary",
  },
  {
    name: "Formas de las palabras españolas",
    url: "_dl.php?back=bbl&a=es.dictionary&b=mybible&c",
    key: "es",
    size: 1412247,
    storedName: "es.dictionary",
  },
  {
    name: "Diccionario Strong en Español",
    url: "_dl.php?back=bbl&a=Str-ES.dictionary&b=mybible&c",
    key: "Str",
    size: 1647807,
    storedName: "Str-ES.dictionary",
  },
  {
    name: "A Spanish-English Dictionary",
    url: "_dl.php?back=bbl&a=es-en-GU.dictionary&b=mybible&c",
    key: "es",
    size: 17146219,
    storedName: "es-en-GU.dictionary",
  },
  {
    name: "Diccionario Biblico Adventista",
    url: "_dl.php?back=bbl&a=DBAdvn.dictionary&b=mybible&c",
    key: "DBAdvn",
    size: 2439140,
    storedName: "DBAdvn.dictionary",
  },
  {
    name: "El Codigo Real - NT Textual Hebraico",
    url: "_dl.php?back=bbl&a=DECR.dictionary&b=mybible&c",
    key: "DECR",
    size: 41770,
    storedName: "DECR.dictionary",
  },
  {
    name: "Glosario de Nombres Bíblicos de Jack Enlow",
    url: "_dl.php?back=bbl&a=Enlow.dictionary&b=mybible&c",
    key: "Enlow",
    size: 118509,
    storedName: "Enlow.dictionary",
  },
  {
    name: "Devociones en Español",
    url: "_dl.php?back=bbl&a=WC-es.devotions&b=mybible&c",
    key: "WC",
    size: 653557,
    storedName: "WC-es.devotions",
  },
  {
    name: "Diccionario Strong",
    url: "_dl.php?back=bbl&a=Str-ES.devotions&b=mybible&c",
    key: "Str",
    size: 0,
    storedName: "Str-ES.devotions",
  },
  {
    name: "La Biblia Textual 3a Edicion",
    url: "_dl.php?back=bbl&a=BTX3-c.commentaries&b=mybible&c",
    key: "BTX3",
    size: 398900,
    storedName: "BTX3-c.commentaries",
  },
  {
    name: "Comentario Bíblico Mundo Hispano",
    url: "_dl.php?back=bbl&a=CBMH-c.commentaries&b=mybible&c",
    key: "CBMH",
    size: 4645248,
    storedName: "CBMH-c.commentaries",
  },
  {
    name: "Comentario biblia textual",
    url: "_dl.php?back=bbl&a=CBT-c.commentaries&b=mybible&c",
    key: "CBT",
    size: 268375,
    storedName: "CBT-c.commentaries",
  },
  {
    name: "El Codigo Real — Nuevo Testamento Textual Hebraico",
    url: "_dl.php?back=bbl&a=CDG-c.commentaries&b=mybible&c",
    key: "CDG",
    size: 83092,
    storedName: "CDG-c.commentaries",
  },
  {
    name: "Apocalipse Versículo Por Versículo",
    url: "_dl.php?back=bbl&a=AVPV-c.commentaries&b=mybible&c",
    key: "AVPV",
    size: 281220,
    storedName: "AVPV-c.commentaries",
  },
  {
    name: "Introducción a la Reina-Valera",
    url: "_dl.php?back=bbl&a=RV60-c.commentaries&b=mybible&c",
    key: "RV60",
    size: 63155,
    storedName: "RV60-c.commentaries",
  },
  {
    name: "Comentario Bíblico Adventista",
    url: "_dl.php?back=bbl&a=CBA-c.commentaries&b=mybible&c",
    key: "CBA",
    size: 8049516,
    storedName: "CBA-c.commentaries",
  },
  {
    name: "Comentario Biblico Wiiliam Macdonald",
    url: "_dl.php?back=bbl&a=CBWM-c.commentaries&b=mybible&c",
    key: "CBWM",
    size: 3356434,
    storedName: "CBWM-c.commentaries",
  },
  {
    name: "Comentario Mattew Henry",
    url: "_dl.php?back=bbl&a=CMH-c.commentaries&b=mybible&c",
    key: "CMH",
    size: 2626245,
    storedName: "CMH-c.commentaries",
  },
  {
    name: "Comentario Diario Vivir",
    url: "_dl.php?back=bbl&a=DV-c.commentaries&b=mybible&c",
    key: "DV",
    size: 2147915,
    storedName: "DV-c.commentaries",
  },
  {
    name: "Reina Valera 1995 — Notas",
    url: "_dl.php?back=bbl&a=RV95-c.commentaries&b=mybible&c",
    key: "RV95",
    size: 1202300,
    storedName: "RV95-c.commentaries",
  },
  {
    name: "Biblia de Estudio Ryrie",
    url: "_dl.php?back=bbl&a=Ryrie-c.commentaries&b=mybible&c",
    key: "Ryrie",
    size: 735580,
    storedName: "Ryrie-c.commentaries",
  },
  {
    name: "Nuevo Comentario Bíblico Siglo Veintiuno",
    url: "_dl.php?back=bbl&a=Siglo-c.commentaries&b=mybible&c",
    key: "Siglo",
    size: 2399454,
    storedName: "Siglo-c.commentaries",
  },
  {
    name: "Bosquejos expositivos de la Biblia",
    url: "_dl.php?back=bbl&a=WEO-ES-c.commentaries&b=mybible&c",
    key: "WEO",
    size: 1287133,
    storedName: "WEO-ES-c.commentaries",
  },
  {
    name: "BCS Biblia Comentada",
    url: "_dl.php?back=bbl&a=BCS-c.commentaries&b=mybible&c",
    key: "BCS",
    size: 7004680,
    storedName: "BCS-c.commentaries",
  },
  {
    name: "Bíblia de Estudo Pentencostal",
    url: "_dl.php?back=bbl&a=BdEP-c.commentaries&b=mybible&c",
    key: "BdEP",
    size: 1264971,
    storedName: "BdEP-c.commentaries",
  },
  {
    name: "MacArthur — Comentarios Expositivos",
    url: "_dl.php?back=bbl&a=MCE-c.commentaries&b=mybible&c",
    key: "MCE",
    size: 1754709,
    storedName: "MCE-c.commentaries",
  },
  {
    name: "Biblia de Estudio de MacArthur",
    url: "_dl.php?back=bbl&a=BEM-c.commentaries&b=mybible&c",
    key: "BEM",
    size: 3268575,
    storedName: "BEM-c.commentaries",
  },
  {
    name: "La Biblia Textual 2a Edicion",
    url: "_dl.php?back=bbl&a=BTX2-c.commentaries&b=mybible&c",
    key: "BTX2",
    size: 312027,
    storedName: "BTX2-c.commentaries",
  },
  {
    name: "BDI La Biblia De Israel — Genesis",
    url: "_dl.php?back=bbl&a=BDI-c.commentaries&b=mybible&c",
    key: "BDI",
    size: 39169,
    storedName: "BDI-c.commentaries",
  },
  {
    name: "Comentario plenitud",
    url: "_dl.php?back=bbl&a=PL-c.commentaries&b=mybible&c",
    key: "PL",
    size: 1980540,
    storedName: "PL-c.commentaries",
  },
  {
    name: "Comentario Jamieson-Fausset-Brown",
    url: "_dl.php?back=bbl&a=JFB-ES-c.commentaries&b=mybible&c",
    key: "JFB",
    size: 4980736,
    storedName: "JFB-ES-c.commentaries",
  },
  {
    name: "Notas Torres Amat",
    url: "_dl.php?back=bbl&a=TA-c.commentaries&b=mybible&c",
    key: "TA",
    size: 108040,
    storedName: "TA-c.commentaries",
  },
  {
    name: "Estudios personales sobre Colosenses",
    url: "_dl.php?back=bbl&a=Flores-c.commentaries&b=mybible&c",
    key: "Flores",
    size: 134490,
    storedName: "Flores-c.commentaries",
  },
  {
    name: "La Biblia de las Américas",
    url: "_dl.php?back=bbl&a=LBLA-c.commentaries&b=mybible&c",
    key: "LBLA",
    size: 370589,
    storedName: "LBLA-c.commentaries",
  },
  {
    name: "Los Evangelios Explicados",
    url: "_dl.php?back=bbl&a=LEE-c.commentaries&b=mybible&c",
    key: "LEE",
    size: 838640,
    storedName: "LEE-c.commentaries",
  },
  {
    name: "Los Evangelios Explicados",
    url: "_dl.php?back=bbl&a=LEER-c.commentaries&b=mybible&c",
    key: "LEER",
    size: 838921,
    storedName: "LEER-c.commentaries",
  },
  {
    name: "Nueva Reina Valera",
    url: "_dl.php?back=bbl&a=NRV-c.commentaries&b=mybible&c",
    key: "NRV",
    size: 235332,
    storedName: "NRV-c.commentaries",
  },
  {
    name: "Nueva Versión Internacional — Referencias y notas",
    url: "_dl.php?back=bbl&a=NVI-c.commentaries&b=mybible&c",
    key: "NVI",
    size: 109518,
    storedName: "NVI-c.commentaries",
  },
  {
    name: "Traducción En Lenguaje Actual Con Deuterocanonicos En Orden Alejandrino",
    url: "_dl.php?back=bbl&a=TLA-c.commentaries&b=mybible&c",
    key: "TLA",
    size: 26855,
    storedName: "TLA-c.commentaries",
  },
  {
    name: "Las Sagradas Escrituras, Versión Israelita Nazarena, Revision",
    url: "_dl.php?back=bbl&a=VIN2011-c.commentaries&b=mybible&c",
    key: "VIN2011",
    size: 10780,
    storedName: "VIN2011-c.commentaries",
  },
  {
    name: "Comentario Bíblico Beacon",
    url: "_dl.php?back=bbl&a=CBB-es.commentaries&b=mybible&c",
    key: "CBB",
    size: 32406914,
    storedName: "CBB-es.commentaries",
  },
  {
    name: "B-C1957 Sagrada Biblia Bover-Cantera (4ta Edición)",
    url: "_dl.php?back=bbl&a=B-C'57-c.commentaries&b=mybible&c",
    key: "B",
    size: 349736,
    storedName: "B-C'57-c.commentaries",
  },
  {
    name: "Comentario Conferencia Episcopal Española",
    url: "_dl.php?back=bbl&a=CEE'2011.commentaries&b=mybible&c",
    key: "CEE",
    size: 166305,
    storedName: "CEE'2011.commentaries",
  },
  {
    name: "Comentarios de Elena G. White",
    url: "_dl.php?back=bbl&a=EGW-c.commentaries&b=mybible&c",
    key: "EGW",
    size: 709313,
    storedName: "EGW-c.commentaries",
  },
  {
    name: "Comentario Biblia Jünemann",
    url: "_dl.php?back=bbl&a=JLXX-c.commentaries&b=mybible&c",
    key: "JLXX",
    size: 302563,
    storedName: "JLXX-c.commentaries",
  },
  {
    name: "Comentario Biblia Jerusalén",
    url: "_dl.php?back=bbl&a=NBJ'98-c.commentaries&b=mybible&c",
    key: "NBJ",
    size: 1777589,
    storedName: "NBJ'98-c.commentaries",
  },
  {
    name: "Escrituras del Nombre Verdadero — Notas",
    url: "_dl.php?back=bbl&a=NTNV-c.commentaries&b=mybible&c",
    key: "NTNV",
    size: 142718,
    storedName: "NTNV-c.commentaries",
  },
  {
    name: "Comentario Al NT Por Partain – Reeves",
    url: "_dl.php?back=bbl&a=WP-BR-c.commentaries&b=mybible&c",
    key: "WP",
    size: 4293215,
    storedName: "WP-BR-c.commentaries",
  },
  {
    name: "Comentario del Nuevo Testamento Versión Recobro",
    url: "_dl.php?back=bbl&a=RCB-c.commentaries&b=mybible&c",
    key: "RCB",
    size: 1078171,
    storedName: "RCB-c.commentaries",
  },
  {
    name: "Comentario al Nuevo Testamento, que presenta la nueva edición española actualizada",
    url: "_dl.php?back=bbl&a=BAR-c.commentaries&b=mybible&c",
    key: "BAR",
    size: 3551413,
    storedName: "BAR-c.commentaries",
  },
  {
    name: "Comentario al Texto Griego del Nuevo Testamento",
    url: "_dl.php?back=bbl&a=CATG-c.commentaries&b=mybible&c",
    key: "CATG",
    size: 2553649,
    storedName: "CATG-c.commentaries",
  },
].map((version) => {
  return {
    ...version,
    disabled:
      version.name.includes("Comentario") || version.name.includes("Comentada"),
  };
});
