import { BookChapter, IDBBookChapterVerse, IDBBookNames } from "../types";

export const DB_BOOK_NAMES: IDBBookNames[] = [
  {
    bookColor: "#ccccff",
    bookNumber: 10,
    longName: "Génesis",
    shortName: "Gn",
  },
  {
    bookColor: "#ccccff",
    bookNumber: 20,
    longName: "Éxodo",
    shortName: "Ex",
  },
  {
    bookColor: "#ccccff",
    bookNumber: 30,
    longName: "Levítico",
    shortName: "Lv",
  },
  {
    bookColor: "#ccccff",
    bookNumber: 40,
    longName: "Números",
    shortName: "Nm",
  },
  {
    bookColor: "#ccccff",
    bookNumber: 50,
    longName: "Deuteronomio",
    shortName: "Dt",
  },
  {
    bookColor: "#ffcc99",
    bookNumber: 60,
    longName: "Josué",
    shortName: "Jos",
  },
  {
    bookColor: "#ffcc99",
    bookNumber: 70,
    longName: "Jueces",
    shortName: "Jue",
  },
  {
    bookColor: "#ffcc99",
    bookNumber: 80,
    longName: "Rut",
    shortName: "Rt",
  },
  {
    bookColor: "#ffcc99",
    bookNumber: 90,
    longName: "1 Samuel",
    shortName: "1S",
  },
  {
    bookColor: "#ffcc99",
    bookNumber: 100,
    longName: "2 Samuel",
    shortName: "2S",
  },
  {
    bookColor: "#ffcc99",
    bookNumber: 110,
    longName: "1 Reyes",
    shortName: "1R",
  },
  {
    bookColor: "#ffcc99",
    bookNumber: 120,
    longName: "2 Reyes",
    shortName: "2R",
  },
  {
    bookColor: "#ffcc99",
    bookNumber: 130,
    longName: "1 Crónicas",
    shortName: "1Cr",
  },
  {
    bookColor: "#ffcc99",
    bookNumber: 140,
    longName: "2 Crónicas",
    shortName: "2Cr",
  },
  {
    bookColor: "#ffcc99",
    bookNumber: 150,
    longName: "Esdras",
    shortName: "Esd",
  },
  {
    bookColor: "#ffcc99",
    bookNumber: 160,
    longName: "Nehemías",
    shortName: "Neh",
  },
  {
    bookColor: "#ffcc99",
    bookNumber: 190,
    longName: "Ester",
    shortName: "Est",
  },
  {
    bookColor: "#66ff99",
    bookNumber: 220,
    longName: "Job",
    shortName: "Job",
  },
  {
    bookColor: "#66ff99",
    bookNumber: 230,
    longName: "Salmos",
    shortName: "Sal",
  },
  {
    bookColor: "#66ff99",
    bookNumber: 240,
    longName: "Proverbios",
    shortName: "Pr",
  },
  {
    bookColor: "#66ff99",
    bookNumber: 250,
    longName: "Eclesiastés",
    shortName: "Ec",
  },
  {
    bookColor: "#66ff99",
    bookNumber: 260,
    longName: "Cantar de los Cantares",
    shortName: "Cnt",
  },
  {
    bookColor: "#ff9fb4",
    bookNumber: 290,
    longName: "Isaías",
    shortName: "Is",
  },
  {
    bookColor: "#ff9fb4",
    bookNumber: 300,
    longName: "Jeremías",
    shortName: "Jer",
  },
  {
    bookColor: "#ff9fb4",
    bookNumber: 310,
    longName: "Lamentaciones",
    shortName: "Lm",
  },
  {
    bookColor: "#ff9fb4",
    bookNumber: 330,
    longName: "Ezequiel",
    shortName: "Ez",
  },
  {
    bookColor: "#ff9fb4",
    bookNumber: 340,
    longName: "Daniel",
    shortName: "Dn",
  },
  {
    bookColor: "#ffff99",
    bookNumber: 350,
    longName: "Oseas",
    shortName: "Os",
  },
  {
    bookColor: "#ffff99",
    bookNumber: 360,
    longName: "Joel",
    shortName: "Jl",
  },
  {
    bookColor: "#ffff99",
    bookNumber: 370,
    longName: "Amós",
    shortName: "Am",
  },
  {
    bookColor: "#ffff99",
    bookNumber: 380,
    longName: "Abdías",
    shortName: "Abd",
  },
  {
    bookColor: "#ffff99",
    bookNumber: 390,
    longName: "Jonás",
    shortName: "Jon",
  },
  {
    bookColor: "#ffff99",
    bookNumber: 400,
    longName: "Miqueas",
    shortName: "Mi",
  },
  {
    bookColor: "#ffff99",
    bookNumber: 410,
    longName: "Nahum",
    shortName: "Nah",
  },
  {
    bookColor: "#ffff99",
    bookNumber: 420,
    longName: "Habacuc",
    shortName: "Hab",
  },
  {
    bookColor: "#ffff99",
    bookNumber: 430,
    longName: "Sofonías",
    shortName: "Sof",
  },
  {
    bookColor: "#ffff99",
    bookNumber: 440,
    longName: "Hageo",
    shortName: "Hag",
  },
  {
    bookColor: "#ffff99",
    bookNumber: 450,
    longName: "Zacarías",
    shortName: "Zac",
  },
  {
    bookColor: "#ffff99",
    bookNumber: 460,
    longName: "Malaquías",
    shortName: "Mal",
  },
  {
    bookColor: "#ff6600",
    bookNumber: 470,
    longName: "Mateo",
    shortName: "Mt",
  },
  {
    bookColor: "#ff6600",
    bookNumber: 480,
    longName: "Marcos",
    shortName: "Mr",
  },
  {
    bookColor: "#ff6600",
    bookNumber: 490,
    longName: "Lucas",
    shortName: "Lc",
  },
  {
    bookColor: "#ff6600",
    bookNumber: 500,
    longName: "Juan",
    shortName: "Jn",
  },
  {
    bookColor: "#00ffff",
    bookNumber: 510,
    longName: "Hechos de los Apóstoles",
    shortName: "Hch",
  },
  {
    bookColor: "#ffff00",
    bookNumber: 520,
    longName: "Romanos",
    shortName: "Ro",
  },
  {
    bookColor: "#ffff00",
    bookNumber: 530,
    longName: "1 Corintios",
    shortName: "1Co",
  },
  {
    bookColor: "#ffff00",
    bookNumber: 540,
    longName: "2 Corintios",
    shortName: "2Co",
  },
  {
    bookColor: "#ffff00",
    bookNumber: 550,
    longName: "Gálatas",
    shortName: "Ga",
  },
  {
    bookColor: "#ffff00",
    bookNumber: 560,
    longName: "Efesios",
    shortName: "Ef",
  },
  {
    bookColor: "#ffff00",
    bookNumber: 570,
    longName: "Filipenses",
    shortName: "Fil",
  },
  {
    bookColor: "#ffff00",
    bookNumber: 580,
    longName: "Colosenses",
    shortName: "Col",
  },
  {
    bookColor: "#ffff00",
    bookNumber: 590,
    longName: "1 Tesalonicenses",
    shortName: "1Ts",
  },
  {
    bookColor: "#ffff00",
    bookNumber: 600,
    longName: "2 Tesalonicenses",
    shortName: "2Ts",
  },
  {
    bookColor: "#ffff00",
    bookNumber: 610,
    longName: "1 Timoteo",
    shortName: "1Ti",
  },
  {
    bookColor: "#ffff00",
    bookNumber: 620,
    longName: "2 Timoteo",
    shortName: "2Ti",
  },
  {
    bookColor: "#ffff00",
    bookNumber: 630,
    longName: "Tito",
    shortName: "Tit",
  },
  {
    bookColor: "#ffff00",
    bookNumber: 640,
    longName: "Filemón",
    shortName: "Flm",
  },
  {
    bookColor: "#ffff00",
    bookNumber: 650,
    longName: "Hebreos",
    shortName: "He",
  },
  {
    bookColor: "#00ff00",
    bookNumber: 660,
    longName: "Santiago",
    shortName: "Stg",
  },
  {
    bookColor: "#00ff00",
    bookNumber: 670,
    longName: "1 Pedro",
    shortName: "1P",
  },
  {
    bookColor: "#00ff00",
    bookNumber: 680,
    longName: "2 Pedro",
    shortName: "2P",
  },
  {
    bookColor: "#00ff00",
    bookNumber: 690,
    longName: "1 Juan",
    shortName: "1Jn",
  },
  {
    bookColor: "#00ff00",
    bookNumber: 700,
    longName: "2 Juan",
    shortName: "2Jn",
  },
  {
    bookColor: "#00ff00",
    bookNumber: 710,
    longName: "3 Juan",
    shortName: "3Jn",
  },
  {
    bookColor: "#00ff00",
    bookNumber: 720,
    longName: "Judas",
    shortName: "Jud",
  },
  {
    bookColor: "#ff7c80",
    bookNumber: 730,
    longName: "Apocalipsis (de Juan)",
    shortName: "Ap",
  },
];

export const DB_BOOK_CHAPTER_NUMBER: BookChapter = {
  Génesis: 50,
  Éxodo: 40,
  Levítico: 27,
  Números: 36,
  Deuteronomio: 34,
  Josué: 24,
  Jueces: 21,
  Rut: 4,
  "1 Samuel": 31,
  "2 Samuel": 24,
  "1 Reyes": 22,
  "2 Reyes": 25,
  "1 Crónicas": 29,
  "2 Crónicas": 36,
  Esdras: 10,
  Nehemías: 13,
  Ester: 10,
  Job: 42,
  Salmos: 150,
  Proverbios: 31,
  Eclesiastés: 12,
  "Cantar de los Cantares": 8,
  Isaías: 66,
  Jeremías: 52,
  Lamentaciones: 5,
  Ezequiel: 48,
  Daniel: 12,
  Oseas: 14,
  Joel: 3,
  Amós: 9,
  Abdías: 1,
  Jonás: 4,
  Miqueas: 7,
  Nahum: 3,
  Habacuc: 3,
  Sofonías: 3,
  Hageo: 2,
  Zacarías: 14,
  Malaquías: 4,
  Mateo: 28,
  Marcos: 16,
  Lucas: 24,
  Juan: 21,
  "Hechos de los Apóstoles": 28,
  Romanos: 16,
  "1 Corintios": 16,
  "2 Corintios": 13,
  Gálatas: 6,
  Efesios: 6,
  Filipenses: 4,
  Colosenses: 4,
  "1 Tesalonicenses": 5,
  "2 Tesalonicenses": 3,
  "1 Timoteo": 6,
  "2 Timoteo": 4,
  Tito: 3,
  Filemón: 1,
  Hebreos: 13,
  Santiago: 5,
  "1 Pedro": 5,
  "2 Pedro": 3,
  "1 Juan": 5,
  "2 Juan": 1,
  "3 Juan": 1,
  Judas: 1,
  "Apocalipsis (de Juan)": 22,
};

export const DB_BOOK_CHAPTER_VERSES: IDBBookChapterVerse[] = [
  {
    bookNumber: 10,
    chapterNumber: 1,
    verseCount: 31,
  },
  {
    bookNumber: 10,
    chapterNumber: 2,
    verseCount: 25,
  },
  {
    bookNumber: 10,
    chapterNumber: 3,
    verseCount: 24,
  },
  {
    bookNumber: 10,
    chapterNumber: 4,
    verseCount: 26,
  },
  {
    bookNumber: 10,
    chapterNumber: 5,
    verseCount: 32,
  },
  {
    bookNumber: 10,
    chapterNumber: 6,
    verseCount: 22,
  },
  {
    bookNumber: 10,
    chapterNumber: 7,
    verseCount: 24,
  },
  {
    bookNumber: 10,
    chapterNumber: 8,
    verseCount: 22,
  },
  {
    bookNumber: 10,
    chapterNumber: 9,
    verseCount: 29,
  },
  {
    bookNumber: 10,
    chapterNumber: 10,
    verseCount: 32,
  },
  {
    bookNumber: 10,
    chapterNumber: 11,
    verseCount: 32,
  },
  {
    bookNumber: 10,
    chapterNumber: 12,
    verseCount: 20,
  },
  {
    bookNumber: 10,
    chapterNumber: 13,
    verseCount: 18,
  },
  {
    bookNumber: 10,
    chapterNumber: 14,
    verseCount: 24,
  },
  {
    bookNumber: 10,
    chapterNumber: 15,
    verseCount: 21,
  },
  {
    bookNumber: 10,
    chapterNumber: 16,
    verseCount: 16,
  },
  {
    bookNumber: 10,
    chapterNumber: 17,
    verseCount: 27,
  },
  {
    bookNumber: 10,
    chapterNumber: 18,
    verseCount: 33,
  },
  {
    bookNumber: 10,
    chapterNumber: 19,
    verseCount: 38,
  },
  {
    bookNumber: 10,
    chapterNumber: 20,
    verseCount: 18,
  },
  {
    bookNumber: 10,
    chapterNumber: 21,
    verseCount: 34,
  },
  {
    bookNumber: 10,
    chapterNumber: 22,
    verseCount: 24,
  },
  {
    bookNumber: 10,
    chapterNumber: 23,
    verseCount: 20,
  },
  {
    bookNumber: 10,
    chapterNumber: 24,
    verseCount: 67,
  },
  {
    bookNumber: 10,
    chapterNumber: 25,
    verseCount: 34,
  },
  {
    bookNumber: 10,
    chapterNumber: 26,
    verseCount: 35,
  },
  {
    bookNumber: 10,
    chapterNumber: 27,
    verseCount: 46,
  },
  {
    bookNumber: 10,
    chapterNumber: 28,
    verseCount: 22,
  },
  {
    bookNumber: 10,
    chapterNumber: 29,
    verseCount: 35,
  },
  {
    bookNumber: 10,
    chapterNumber: 30,
    verseCount: 43,
  },
  {
    bookNumber: 10,
    chapterNumber: 31,
    verseCount: 55,
  },
  {
    bookNumber: 10,
    chapterNumber: 32,
    verseCount: 32,
  },
  {
    bookNumber: 10,
    chapterNumber: 33,
    verseCount: 20,
  },
  {
    bookNumber: 10,
    chapterNumber: 34,
    verseCount: 31,
  },
  {
    bookNumber: 10,
    chapterNumber: 35,
    verseCount: 29,
  },
  {
    bookNumber: 10,
    chapterNumber: 36,
    verseCount: 43,
  },
  {
    bookNumber: 10,
    chapterNumber: 37,
    verseCount: 36,
  },
  {
    bookNumber: 10,
    chapterNumber: 38,
    verseCount: 30,
  },
  {
    bookNumber: 10,
    chapterNumber: 39,
    verseCount: 23,
  },
  {
    bookNumber: 10,
    chapterNumber: 40,
    verseCount: 23,
  },
  {
    bookNumber: 10,
    chapterNumber: 41,
    verseCount: 57,
  },
  {
    bookNumber: 10,
    chapterNumber: 42,
    verseCount: 38,
  },
  {
    bookNumber: 10,
    chapterNumber: 43,
    verseCount: 34,
  },
  {
    bookNumber: 10,
    chapterNumber: 44,
    verseCount: 34,
  },
  {
    bookNumber: 10,
    chapterNumber: 45,
    verseCount: 28,
  },
  {
    bookNumber: 10,
    chapterNumber: 46,
    verseCount: 34,
  },
  {
    bookNumber: 10,
    chapterNumber: 47,
    verseCount: 31,
  },
  {
    bookNumber: 10,
    chapterNumber: 48,
    verseCount: 22,
  },
  {
    bookNumber: 10,
    chapterNumber: 49,
    verseCount: 33,
  },
  {
    bookNumber: 10,
    chapterNumber: 50,
    verseCount: 26,
  },
  {
    bookNumber: 20,
    chapterNumber: 1,
    verseCount: 22,
  },
  {
    bookNumber: 20,
    chapterNumber: 2,
    verseCount: 25,
  },
  {
    bookNumber: 20,
    chapterNumber: 3,
    verseCount: 22,
  },
  {
    bookNumber: 20,
    chapterNumber: 4,
    verseCount: 31,
  },
  {
    bookNumber: 20,
    chapterNumber: 5,
    verseCount: 23,
  },
  {
    bookNumber: 20,
    chapterNumber: 6,
    verseCount: 30,
  },
  {
    bookNumber: 20,
    chapterNumber: 7,
    verseCount: 25,
  },
  {
    bookNumber: 20,
    chapterNumber: 8,
    verseCount: 32,
  },
  {
    bookNumber: 20,
    chapterNumber: 9,
    verseCount: 35,
  },
  {
    bookNumber: 20,
    chapterNumber: 10,
    verseCount: 29,
  },
  {
    bookNumber: 20,
    chapterNumber: 11,
    verseCount: 10,
  },
  {
    bookNumber: 20,
    chapterNumber: 12,
    verseCount: 51,
  },
  {
    bookNumber: 20,
    chapterNumber: 13,
    verseCount: 22,
  },
  {
    bookNumber: 20,
    chapterNumber: 14,
    verseCount: 31,
  },
  {
    bookNumber: 20,
    chapterNumber: 15,
    verseCount: 27,
  },
  {
    bookNumber: 20,
    chapterNumber: 16,
    verseCount: 36,
  },
  {
    bookNumber: 20,
    chapterNumber: 17,
    verseCount: 16,
  },
  {
    bookNumber: 20,
    chapterNumber: 18,
    verseCount: 27,
  },
  {
    bookNumber: 20,
    chapterNumber: 19,
    verseCount: 25,
  },
  {
    bookNumber: 20,
    chapterNumber: 20,
    verseCount: 26,
  },
  {
    bookNumber: 20,
    chapterNumber: 21,
    verseCount: 36,
  },
  {
    bookNumber: 20,
    chapterNumber: 22,
    verseCount: 31,
  },
  {
    bookNumber: 20,
    chapterNumber: 23,
    verseCount: 33,
  },
  {
    bookNumber: 20,
    chapterNumber: 24,
    verseCount: 18,
  },
  {
    bookNumber: 20,
    chapterNumber: 25,
    verseCount: 40,
  },
  {
    bookNumber: 20,
    chapterNumber: 26,
    verseCount: 37,
  },
  {
    bookNumber: 20,
    chapterNumber: 27,
    verseCount: 21,
  },
  {
    bookNumber: 20,
    chapterNumber: 28,
    verseCount: 43,
  },
  {
    bookNumber: 20,
    chapterNumber: 29,
    verseCount: 46,
  },
  {
    bookNumber: 20,
    chapterNumber: 30,
    verseCount: 38,
  },
  {
    bookNumber: 20,
    chapterNumber: 31,
    verseCount: 18,
  },
  {
    bookNumber: 20,
    chapterNumber: 32,
    verseCount: 35,
  },
  {
    bookNumber: 20,
    chapterNumber: 33,
    verseCount: 23,
  },
  {
    bookNumber: 20,
    chapterNumber: 34,
    verseCount: 35,
  },
  {
    bookNumber: 20,
    chapterNumber: 35,
    verseCount: 35,
  },
  {
    bookNumber: 20,
    chapterNumber: 36,
    verseCount: 38,
  },
  {
    bookNumber: 20,
    chapterNumber: 37,
    verseCount: 29,
  },
  {
    bookNumber: 20,
    chapterNumber: 38,
    verseCount: 31,
  },
  {
    bookNumber: 20,
    chapterNumber: 39,
    verseCount: 43,
  },
  {
    bookNumber: 20,
    chapterNumber: 40,
    verseCount: 38,
  },
  {
    bookNumber: 30,
    chapterNumber: 1,
    verseCount: 17,
  },
  {
    bookNumber: 30,
    chapterNumber: 2,
    verseCount: 16,
  },
  {
    bookNumber: 30,
    chapterNumber: 3,
    verseCount: 17,
  },
  {
    bookNumber: 30,
    chapterNumber: 4,
    verseCount: 35,
  },
  {
    bookNumber: 30,
    chapterNumber: 5,
    verseCount: 19,
  },
  {
    bookNumber: 30,
    chapterNumber: 6,
    verseCount: 30,
  },
  {
    bookNumber: 30,
    chapterNumber: 7,
    verseCount: 38,
  },
  {
    bookNumber: 30,
    chapterNumber: 8,
    verseCount: 36,
  },
  {
    bookNumber: 30,
    chapterNumber: 9,
    verseCount: 24,
  },
  {
    bookNumber: 30,
    chapterNumber: 10,
    verseCount: 20,
  },
  {
    bookNumber: 30,
    chapterNumber: 11,
    verseCount: 47,
  },
  {
    bookNumber: 30,
    chapterNumber: 12,
    verseCount: 8,
  },
  {
    bookNumber: 30,
    chapterNumber: 13,
    verseCount: 59,
  },
  {
    bookNumber: 30,
    chapterNumber: 14,
    verseCount: 57,
  },
  {
    bookNumber: 30,
    chapterNumber: 15,
    verseCount: 33,
  },
  {
    bookNumber: 30,
    chapterNumber: 16,
    verseCount: 34,
  },
  {
    bookNumber: 30,
    chapterNumber: 17,
    verseCount: 16,
  },
  {
    bookNumber: 30,
    chapterNumber: 18,
    verseCount: 30,
  },
  {
    bookNumber: 30,
    chapterNumber: 19,
    verseCount: 37,
  },
  {
    bookNumber: 30,
    chapterNumber: 20,
    verseCount: 27,
  },
  {
    bookNumber: 30,
    chapterNumber: 21,
    verseCount: 24,
  },
  {
    bookNumber: 30,
    chapterNumber: 22,
    verseCount: 33,
  },
  {
    bookNumber: 30,
    chapterNumber: 23,
    verseCount: 44,
  },
  {
    bookNumber: 30,
    chapterNumber: 24,
    verseCount: 23,
  },
  {
    bookNumber: 30,
    chapterNumber: 25,
    verseCount: 55,
  },
  {
    bookNumber: 30,
    chapterNumber: 26,
    verseCount: 46,
  },
  {
    bookNumber: 30,
    chapterNumber: 27,
    verseCount: 34,
  },
  {
    bookNumber: 40,
    chapterNumber: 1,
    verseCount: 54,
  },
  {
    bookNumber: 40,
    chapterNumber: 2,
    verseCount: 34,
  },
  {
    bookNumber: 40,
    chapterNumber: 3,
    verseCount: 51,
  },
  {
    bookNumber: 40,
    chapterNumber: 4,
    verseCount: 49,
  },
  {
    bookNumber: 40,
    chapterNumber: 5,
    verseCount: 31,
  },
  {
    bookNumber: 40,
    chapterNumber: 6,
    verseCount: 27,
  },
  {
    bookNumber: 40,
    chapterNumber: 7,
    verseCount: 89,
  },
  {
    bookNumber: 40,
    chapterNumber: 8,
    verseCount: 26,
  },
  {
    bookNumber: 40,
    chapterNumber: 9,
    verseCount: 23,
  },
  {
    bookNumber: 40,
    chapterNumber: 10,
    verseCount: 36,
  },
  {
    bookNumber: 40,
    chapterNumber: 11,
    verseCount: 35,
  },
  {
    bookNumber: 40,
    chapterNumber: 12,
    verseCount: 16,
  },
  {
    bookNumber: 40,
    chapterNumber: 13,
    verseCount: 33,
  },
  {
    bookNumber: 40,
    chapterNumber: 14,
    verseCount: 45,
  },
  {
    bookNumber: 40,
    chapterNumber: 15,
    verseCount: 41,
  },
  {
    bookNumber: 40,
    chapterNumber: 16,
    verseCount: 50,
  },
  {
    bookNumber: 40,
    chapterNumber: 17,
    verseCount: 13,
  },
  {
    bookNumber: 40,
    chapterNumber: 18,
    verseCount: 32,
  },
  {
    bookNumber: 40,
    chapterNumber: 19,
    verseCount: 22,
  },
  {
    bookNumber: 40,
    chapterNumber: 20,
    verseCount: 29,
  },
  {
    bookNumber: 40,
    chapterNumber: 21,
    verseCount: 35,
  },
  {
    bookNumber: 40,
    chapterNumber: 22,
    verseCount: 41,
  },
  {
    bookNumber: 40,
    chapterNumber: 23,
    verseCount: 30,
  },
  {
    bookNumber: 40,
    chapterNumber: 24,
    verseCount: 25,
  },
  {
    bookNumber: 40,
    chapterNumber: 25,
    verseCount: 18,
  },
  {
    bookNumber: 40,
    chapterNumber: 26,
    verseCount: 65,
  },
  {
    bookNumber: 40,
    chapterNumber: 27,
    verseCount: 23,
  },
  {
    bookNumber: 40,
    chapterNumber: 28,
    verseCount: 31,
  },
  {
    bookNumber: 40,
    chapterNumber: 29,
    verseCount: 40,
  },
  {
    bookNumber: 40,
    chapterNumber: 30,
    verseCount: 16,
  },
  {
    bookNumber: 40,
    chapterNumber: 31,
    verseCount: 54,
  },
  {
    bookNumber: 40,
    chapterNumber: 32,
    verseCount: 42,
  },
  {
    bookNumber: 40,
    chapterNumber: 33,
    verseCount: 56,
  },
  {
    bookNumber: 40,
    chapterNumber: 34,
    verseCount: 29,
  },
  {
    bookNumber: 40,
    chapterNumber: 35,
    verseCount: 34,
  },
  {
    bookNumber: 40,
    chapterNumber: 36,
    verseCount: 13,
  },
  {
    bookNumber: 50,
    chapterNumber: 1,
    verseCount: 46,
  },
  {
    bookNumber: 50,
    chapterNumber: 2,
    verseCount: 37,
  },
  {
    bookNumber: 50,
    chapterNumber: 3,
    verseCount: 29,
  },
  {
    bookNumber: 50,
    chapterNumber: 4,
    verseCount: 49,
  },
  {
    bookNumber: 50,
    chapterNumber: 5,
    verseCount: 33,
  },
  {
    bookNumber: 50,
    chapterNumber: 6,
    verseCount: 25,
  },
  {
    bookNumber: 50,
    chapterNumber: 7,
    verseCount: 26,
  },
  {
    bookNumber: 50,
    chapterNumber: 8,
    verseCount: 20,
  },
  {
    bookNumber: 50,
    chapterNumber: 9,
    verseCount: 29,
  },
  {
    bookNumber: 50,
    chapterNumber: 10,
    verseCount: 22,
  },
  {
    bookNumber: 50,
    chapterNumber: 11,
    verseCount: 32,
  },
  {
    bookNumber: 50,
    chapterNumber: 12,
    verseCount: 32,
  },
  {
    bookNumber: 50,
    chapterNumber: 13,
    verseCount: 18,
  },
  {
    bookNumber: 50,
    chapterNumber: 14,
    verseCount: 29,
  },
  {
    bookNumber: 50,
    chapterNumber: 15,
    verseCount: 23,
  },
  {
    bookNumber: 50,
    chapterNumber: 16,
    verseCount: 22,
  },
  {
    bookNumber: 50,
    chapterNumber: 17,
    verseCount: 20,
  },
  {
    bookNumber: 50,
    chapterNumber: 18,
    verseCount: 22,
  },
  {
    bookNumber: 50,
    chapterNumber: 19,
    verseCount: 21,
  },
  {
    bookNumber: 50,
    chapterNumber: 20,
    verseCount: 20,
  },
  {
    bookNumber: 50,
    chapterNumber: 21,
    verseCount: 23,
  },
  {
    bookNumber: 50,
    chapterNumber: 22,
    verseCount: 30,
  },
  {
    bookNumber: 50,
    chapterNumber: 23,
    verseCount: 25,
  },
  {
    bookNumber: 50,
    chapterNumber: 24,
    verseCount: 22,
  },
  {
    bookNumber: 50,
    chapterNumber: 25,
    verseCount: 19,
  },
  {
    bookNumber: 50,
    chapterNumber: 26,
    verseCount: 19,
  },
  {
    bookNumber: 50,
    chapterNumber: 27,
    verseCount: 26,
  },
  {
    bookNumber: 50,
    chapterNumber: 28,
    verseCount: 68,
  },
  {
    bookNumber: 50,
    chapterNumber: 29,
    verseCount: 29,
  },
  {
    bookNumber: 50,
    chapterNumber: 30,
    verseCount: 20,
  },
  {
    bookNumber: 50,
    chapterNumber: 31,
    verseCount: 30,
  },
  {
    bookNumber: 50,
    chapterNumber: 32,
    verseCount: 52,
  },
  {
    bookNumber: 50,
    chapterNumber: 33,
    verseCount: 29,
  },
  {
    bookNumber: 50,
    chapterNumber: 34,
    verseCount: 12,
  },
  {
    bookNumber: 60,
    chapterNumber: 1,
    verseCount: 18,
  },
  {
    bookNumber: 60,
    chapterNumber: 2,
    verseCount: 24,
  },
  {
    bookNumber: 60,
    chapterNumber: 3,
    verseCount: 17,
  },
  {
    bookNumber: 60,
    chapterNumber: 4,
    verseCount: 24,
  },
  {
    bookNumber: 60,
    chapterNumber: 5,
    verseCount: 15,
  },
  {
    bookNumber: 60,
    chapterNumber: 6,
    verseCount: 27,
  },
  {
    bookNumber: 60,
    chapterNumber: 7,
    verseCount: 26,
  },
  {
    bookNumber: 60,
    chapterNumber: 8,
    verseCount: 35,
  },
  {
    bookNumber: 60,
    chapterNumber: 9,
    verseCount: 27,
  },
  {
    bookNumber: 60,
    chapterNumber: 10,
    verseCount: 43,
  },
  {
    bookNumber: 60,
    chapterNumber: 11,
    verseCount: 23,
  },
  {
    bookNumber: 60,
    chapterNumber: 12,
    verseCount: 24,
  },
  {
    bookNumber: 60,
    chapterNumber: 13,
    verseCount: 33,
  },
  {
    bookNumber: 60,
    chapterNumber: 14,
    verseCount: 15,
  },
  {
    bookNumber: 60,
    chapterNumber: 15,
    verseCount: 63,
  },
  {
    bookNumber: 60,
    chapterNumber: 16,
    verseCount: 10,
  },
  {
    bookNumber: 60,
    chapterNumber: 17,
    verseCount: 18,
  },
  {
    bookNumber: 60,
    chapterNumber: 18,
    verseCount: 28,
  },
  {
    bookNumber: 60,
    chapterNumber: 19,
    verseCount: 51,
  },
  {
    bookNumber: 60,
    chapterNumber: 20,
    verseCount: 9,
  },
  {
    bookNumber: 60,
    chapterNumber: 21,
    verseCount: 45,
  },
  {
    bookNumber: 60,
    chapterNumber: 22,
    verseCount: 34,
  },
  {
    bookNumber: 60,
    chapterNumber: 23,
    verseCount: 16,
  },
  {
    bookNumber: 60,
    chapterNumber: 24,
    verseCount: 33,
  },
  {
    bookNumber: 70,
    chapterNumber: 1,
    verseCount: 36,
  },
  {
    bookNumber: 70,
    chapterNumber: 2,
    verseCount: 23,
  },
  {
    bookNumber: 70,
    chapterNumber: 3,
    verseCount: 31,
  },
  {
    bookNumber: 70,
    chapterNumber: 4,
    verseCount: 24,
  },
  {
    bookNumber: 70,
    chapterNumber: 5,
    verseCount: 31,
  },
  {
    bookNumber: 70,
    chapterNumber: 6,
    verseCount: 40,
  },
  {
    bookNumber: 70,
    chapterNumber: 7,
    verseCount: 25,
  },
  {
    bookNumber: 70,
    chapterNumber: 8,
    verseCount: 35,
  },
  {
    bookNumber: 70,
    chapterNumber: 9,
    verseCount: 57,
  },
  {
    bookNumber: 70,
    chapterNumber: 10,
    verseCount: 18,
  },
  {
    bookNumber: 70,
    chapterNumber: 11,
    verseCount: 40,
  },
  {
    bookNumber: 70,
    chapterNumber: 12,
    verseCount: 15,
  },
  {
    bookNumber: 70,
    chapterNumber: 13,
    verseCount: 25,
  },
  {
    bookNumber: 70,
    chapterNumber: 14,
    verseCount: 20,
  },
  {
    bookNumber: 70,
    chapterNumber: 15,
    verseCount: 20,
  },
  {
    bookNumber: 70,
    chapterNumber: 16,
    verseCount: 31,
  },
  {
    bookNumber: 70,
    chapterNumber: 17,
    verseCount: 13,
  },
  {
    bookNumber: 70,
    chapterNumber: 18,
    verseCount: 31,
  },
  {
    bookNumber: 70,
    chapterNumber: 19,
    verseCount: 30,
  },
  {
    bookNumber: 70,
    chapterNumber: 20,
    verseCount: 48,
  },
  {
    bookNumber: 70,
    chapterNumber: 21,
    verseCount: 25,
  },
  {
    bookNumber: 80,
    chapterNumber: 1,
    verseCount: 22,
  },
  {
    bookNumber: 80,
    chapterNumber: 2,
    verseCount: 23,
  },
  {
    bookNumber: 80,
    chapterNumber: 3,
    verseCount: 18,
  },
  {
    bookNumber: 80,
    chapterNumber: 4,
    verseCount: 22,
  },
  {
    bookNumber: 90,
    chapterNumber: 1,
    verseCount: 28,
  },
  {
    bookNumber: 90,
    chapterNumber: 2,
    verseCount: 36,
  },
  {
    bookNumber: 90,
    chapterNumber: 3,
    verseCount: 21,
  },
  {
    bookNumber: 90,
    chapterNumber: 4,
    verseCount: 22,
  },
  {
    bookNumber: 90,
    chapterNumber: 5,
    verseCount: 12,
  },
  {
    bookNumber: 90,
    chapterNumber: 6,
    verseCount: 21,
  },
  {
    bookNumber: 90,
    chapterNumber: 7,
    verseCount: 17,
  },
  {
    bookNumber: 90,
    chapterNumber: 8,
    verseCount: 22,
  },
  {
    bookNumber: 90,
    chapterNumber: 9,
    verseCount: 27,
  },
  {
    bookNumber: 90,
    chapterNumber: 10,
    verseCount: 27,
  },
  {
    bookNumber: 90,
    chapterNumber: 11,
    verseCount: 15,
  },
  {
    bookNumber: 90,
    chapterNumber: 12,
    verseCount: 25,
  },
  {
    bookNumber: 90,
    chapterNumber: 13,
    verseCount: 23,
  },
  {
    bookNumber: 90,
    chapterNumber: 14,
    verseCount: 52,
  },
  {
    bookNumber: 90,
    chapterNumber: 15,
    verseCount: 35,
  },
  {
    bookNumber: 90,
    chapterNumber: 16,
    verseCount: 23,
  },
  {
    bookNumber: 90,
    chapterNumber: 17,
    verseCount: 58,
  },
  {
    bookNumber: 90,
    chapterNumber: 18,
    verseCount: 30,
  },
  {
    bookNumber: 90,
    chapterNumber: 19,
    verseCount: 24,
  },
  {
    bookNumber: 90,
    chapterNumber: 20,
    verseCount: 42,
  },
  {
    bookNumber: 90,
    chapterNumber: 21,
    verseCount: 15,
  },
  {
    bookNumber: 90,
    chapterNumber: 22,
    verseCount: 23,
  },
  {
    bookNumber: 90,
    chapterNumber: 23,
    verseCount: 29,
  },
  {
    bookNumber: 90,
    chapterNumber: 24,
    verseCount: 22,
  },
  {
    bookNumber: 90,
    chapterNumber: 25,
    verseCount: 44,
  },
  {
    bookNumber: 90,
    chapterNumber: 26,
    verseCount: 25,
  },
  {
    bookNumber: 90,
    chapterNumber: 27,
    verseCount: 12,
  },
  {
    bookNumber: 90,
    chapterNumber: 28,
    verseCount: 25,
  },
  {
    bookNumber: 90,
    chapterNumber: 29,
    verseCount: 11,
  },
  {
    bookNumber: 90,
    chapterNumber: 30,
    verseCount: 31,
  },
  {
    bookNumber: 90,
    chapterNumber: 31,
    verseCount: 13,
  },
  {
    bookNumber: 100,
    chapterNumber: 1,
    verseCount: 27,
  },
  {
    bookNumber: 100,
    chapterNumber: 2,
    verseCount: 32,
  },
  {
    bookNumber: 100,
    chapterNumber: 3,
    verseCount: 39,
  },
  {
    bookNumber: 100,
    chapterNumber: 4,
    verseCount: 12,
  },
  {
    bookNumber: 100,
    chapterNumber: 5,
    verseCount: 25,
  },
  {
    bookNumber: 100,
    chapterNumber: 6,
    verseCount: 23,
  },
  {
    bookNumber: 100,
    chapterNumber: 7,
    verseCount: 29,
  },
  {
    bookNumber: 100,
    chapterNumber: 8,
    verseCount: 18,
  },
  {
    bookNumber: 100,
    chapterNumber: 9,
    verseCount: 13,
  },
  {
    bookNumber: 100,
    chapterNumber: 10,
    verseCount: 19,
  },
  {
    bookNumber: 100,
    chapterNumber: 11,
    verseCount: 27,
  },
  {
    bookNumber: 100,
    chapterNumber: 12,
    verseCount: 31,
  },
  {
    bookNumber: 100,
    chapterNumber: 13,
    verseCount: 39,
  },
  {
    bookNumber: 100,
    chapterNumber: 14,
    verseCount: 33,
  },
  {
    bookNumber: 100,
    chapterNumber: 15,
    verseCount: 37,
  },
  {
    bookNumber: 100,
    chapterNumber: 16,
    verseCount: 23,
  },
  {
    bookNumber: 100,
    chapterNumber: 17,
    verseCount: 29,
  },
  {
    bookNumber: 100,
    chapterNumber: 18,
    verseCount: 33,
  },
  {
    bookNumber: 100,
    chapterNumber: 19,
    verseCount: 43,
  },
  {
    bookNumber: 100,
    chapterNumber: 20,
    verseCount: 26,
  },
  {
    bookNumber: 100,
    chapterNumber: 21,
    verseCount: 22,
  },
  {
    bookNumber: 100,
    chapterNumber: 22,
    verseCount: 51,
  },
  {
    bookNumber: 100,
    chapterNumber: 23,
    verseCount: 39,
  },
  {
    bookNumber: 100,
    chapterNumber: 24,
    verseCount: 25,
  },
  {
    bookNumber: 110,
    chapterNumber: 1,
    verseCount: 53,
  },
  {
    bookNumber: 110,
    chapterNumber: 2,
    verseCount: 46,
  },
  {
    bookNumber: 110,
    chapterNumber: 3,
    verseCount: 28,
  },
  {
    bookNumber: 110,
    chapterNumber: 4,
    verseCount: 34,
  },
  {
    bookNumber: 110,
    chapterNumber: 5,
    verseCount: 18,
  },
  {
    bookNumber: 110,
    chapterNumber: 6,
    verseCount: 38,
  },
  {
    bookNumber: 110,
    chapterNumber: 7,
    verseCount: 51,
  },
  {
    bookNumber: 110,
    chapterNumber: 8,
    verseCount: 66,
  },
  {
    bookNumber: 110,
    chapterNumber: 9,
    verseCount: 28,
  },
  {
    bookNumber: 110,
    chapterNumber: 10,
    verseCount: 29,
  },
  {
    bookNumber: 110,
    chapterNumber: 11,
    verseCount: 43,
  },
  {
    bookNumber: 110,
    chapterNumber: 12,
    verseCount: 33,
  },
  {
    bookNumber: 110,
    chapterNumber: 13,
    verseCount: 34,
  },
  {
    bookNumber: 110,
    chapterNumber: 14,
    verseCount: 31,
  },
  {
    bookNumber: 110,
    chapterNumber: 15,
    verseCount: 34,
  },
  {
    bookNumber: 110,
    chapterNumber: 16,
    verseCount: 34,
  },
  {
    bookNumber: 110,
    chapterNumber: 17,
    verseCount: 24,
  },
  {
    bookNumber: 110,
    chapterNumber: 18,
    verseCount: 46,
  },
  {
    bookNumber: 110,
    chapterNumber: 19,
    verseCount: 21,
  },
  {
    bookNumber: 110,
    chapterNumber: 20,
    verseCount: 43,
  },
  {
    bookNumber: 110,
    chapterNumber: 21,
    verseCount: 29,
  },
  {
    bookNumber: 110,
    chapterNumber: 22,
    verseCount: 53,
  },
  {
    bookNumber: 120,
    chapterNumber: 1,
    verseCount: 18,
  },
  {
    bookNumber: 120,
    chapterNumber: 2,
    verseCount: 25,
  },
  {
    bookNumber: 120,
    chapterNumber: 3,
    verseCount: 27,
  },
  {
    bookNumber: 120,
    chapterNumber: 4,
    verseCount: 44,
  },
  {
    bookNumber: 120,
    chapterNumber: 5,
    verseCount: 27,
  },
  {
    bookNumber: 120,
    chapterNumber: 6,
    verseCount: 33,
  },
  {
    bookNumber: 120,
    chapterNumber: 7,
    verseCount: 20,
  },
  {
    bookNumber: 120,
    chapterNumber: 8,
    verseCount: 29,
  },
  {
    bookNumber: 120,
    chapterNumber: 9,
    verseCount: 37,
  },
  {
    bookNumber: 120,
    chapterNumber: 10,
    verseCount: 36,
  },
  {
    bookNumber: 120,
    chapterNumber: 11,
    verseCount: 21,
  },
  {
    bookNumber: 120,
    chapterNumber: 12,
    verseCount: 21,
  },
  {
    bookNumber: 120,
    chapterNumber: 13,
    verseCount: 25,
  },
  {
    bookNumber: 120,
    chapterNumber: 14,
    verseCount: 29,
  },
  {
    bookNumber: 120,
    chapterNumber: 15,
    verseCount: 38,
  },
  {
    bookNumber: 120,
    chapterNumber: 16,
    verseCount: 20,
  },
  {
    bookNumber: 120,
    chapterNumber: 17,
    verseCount: 41,
  },
  {
    bookNumber: 120,
    chapterNumber: 18,
    verseCount: 37,
  },
  {
    bookNumber: 120,
    chapterNumber: 19,
    verseCount: 37,
  },
  {
    bookNumber: 120,
    chapterNumber: 20,
    verseCount: 21,
  },
  {
    bookNumber: 120,
    chapterNumber: 21,
    verseCount: 26,
  },
  {
    bookNumber: 120,
    chapterNumber: 22,
    verseCount: 20,
  },
  {
    bookNumber: 120,
    chapterNumber: 23,
    verseCount: 37,
  },
  {
    bookNumber: 120,
    chapterNumber: 24,
    verseCount: 20,
  },
  {
    bookNumber: 120,
    chapterNumber: 25,
    verseCount: 30,
  },
  {
    bookNumber: 130,
    chapterNumber: 1,
    verseCount: 54,
  },
  {
    bookNumber: 130,
    chapterNumber: 2,
    verseCount: 55,
  },
  {
    bookNumber: 130,
    chapterNumber: 3,
    verseCount: 24,
  },
  {
    bookNumber: 130,
    chapterNumber: 4,
    verseCount: 43,
  },
  {
    bookNumber: 130,
    chapterNumber: 5,
    verseCount: 26,
  },
  {
    bookNumber: 130,
    chapterNumber: 6,
    verseCount: 81,
  },
  {
    bookNumber: 130,
    chapterNumber: 7,
    verseCount: 40,
  },
  {
    bookNumber: 130,
    chapterNumber: 8,
    verseCount: 40,
  },
  {
    bookNumber: 130,
    chapterNumber: 9,
    verseCount: 44,
  },
  {
    bookNumber: 130,
    chapterNumber: 10,
    verseCount: 14,
  },
  {
    bookNumber: 130,
    chapterNumber: 11,
    verseCount: 47,
  },
  {
    bookNumber: 130,
    chapterNumber: 12,
    verseCount: 40,
  },
  {
    bookNumber: 130,
    chapterNumber: 13,
    verseCount: 14,
  },
  {
    bookNumber: 130,
    chapterNumber: 14,
    verseCount: 17,
  },
  {
    bookNumber: 130,
    chapterNumber: 15,
    verseCount: 29,
  },
  {
    bookNumber: 130,
    chapterNumber: 16,
    verseCount: 43,
  },
  {
    bookNumber: 130,
    chapterNumber: 17,
    verseCount: 27,
  },
  {
    bookNumber: 130,
    chapterNumber: 18,
    verseCount: 17,
  },
  {
    bookNumber: 130,
    chapterNumber: 19,
    verseCount: 19,
  },
  {
    bookNumber: 130,
    chapterNumber: 20,
    verseCount: 8,
  },
  {
    bookNumber: 130,
    chapterNumber: 21,
    verseCount: 30,
  },
  {
    bookNumber: 130,
    chapterNumber: 22,
    verseCount: 19,
  },
  {
    bookNumber: 130,
    chapterNumber: 23,
    verseCount: 32,
  },
  {
    bookNumber: 130,
    chapterNumber: 24,
    verseCount: 31,
  },
  {
    bookNumber: 130,
    chapterNumber: 25,
    verseCount: 31,
  },
  {
    bookNumber: 130,
    chapterNumber: 26,
    verseCount: 32,
  },
  {
    bookNumber: 130,
    chapterNumber: 27,
    verseCount: 34,
  },
  {
    bookNumber: 130,
    chapterNumber: 28,
    verseCount: 21,
  },
  {
    bookNumber: 130,
    chapterNumber: 29,
    verseCount: 30,
  },
  {
    bookNumber: 140,
    chapterNumber: 1,
    verseCount: 17,
  },
  {
    bookNumber: 140,
    chapterNumber: 2,
    verseCount: 18,
  },
  {
    bookNumber: 140,
    chapterNumber: 3,
    verseCount: 17,
  },
  {
    bookNumber: 140,
    chapterNumber: 4,
    verseCount: 22,
  },
  {
    bookNumber: 140,
    chapterNumber: 5,
    verseCount: 14,
  },
  {
    bookNumber: 140,
    chapterNumber: 6,
    verseCount: 42,
  },
  {
    bookNumber: 140,
    chapterNumber: 7,
    verseCount: 22,
  },
  {
    bookNumber: 140,
    chapterNumber: 8,
    verseCount: 18,
  },
  {
    bookNumber: 140,
    chapterNumber: 9,
    verseCount: 31,
  },
  {
    bookNumber: 140,
    chapterNumber: 10,
    verseCount: 19,
  },
  {
    bookNumber: 140,
    chapterNumber: 11,
    verseCount: 23,
  },
  {
    bookNumber: 140,
    chapterNumber: 12,
    verseCount: 16,
  },
  {
    bookNumber: 140,
    chapterNumber: 13,
    verseCount: 22,
  },
  {
    bookNumber: 140,
    chapterNumber: 14,
    verseCount: 15,
  },
  {
    bookNumber: 140,
    chapterNumber: 15,
    verseCount: 19,
  },
  {
    bookNumber: 140,
    chapterNumber: 16,
    verseCount: 14,
  },
  {
    bookNumber: 140,
    chapterNumber: 17,
    verseCount: 19,
  },
  {
    bookNumber: 140,
    chapterNumber: 18,
    verseCount: 34,
  },
  {
    bookNumber: 140,
    chapterNumber: 19,
    verseCount: 11,
  },
  {
    bookNumber: 140,
    chapterNumber: 20,
    verseCount: 37,
  },
  {
    bookNumber: 140,
    chapterNumber: 21,
    verseCount: 20,
  },
  {
    bookNumber: 140,
    chapterNumber: 22,
    verseCount: 12,
  },
  {
    bookNumber: 140,
    chapterNumber: 23,
    verseCount: 21,
  },
  {
    bookNumber: 140,
    chapterNumber: 24,
    verseCount: 27,
  },
  {
    bookNumber: 140,
    chapterNumber: 25,
    verseCount: 28,
  },
  {
    bookNumber: 140,
    chapterNumber: 26,
    verseCount: 23,
  },
  {
    bookNumber: 140,
    chapterNumber: 27,
    verseCount: 9,
  },
  {
    bookNumber: 140,
    chapterNumber: 28,
    verseCount: 27,
  },
  {
    bookNumber: 140,
    chapterNumber: 29,
    verseCount: 36,
  },
  {
    bookNumber: 140,
    chapterNumber: 30,
    verseCount: 27,
  },
  {
    bookNumber: 140,
    chapterNumber: 31,
    verseCount: 21,
  },
  {
    bookNumber: 140,
    chapterNumber: 32,
    verseCount: 33,
  },
  {
    bookNumber: 140,
    chapterNumber: 33,
    verseCount: 25,
  },
  {
    bookNumber: 140,
    chapterNumber: 34,
    verseCount: 33,
  },
  {
    bookNumber: 140,
    chapterNumber: 35,
    verseCount: 27,
  },
  {
    bookNumber: 140,
    chapterNumber: 36,
    verseCount: 23,
  },
  {
    bookNumber: 150,
    chapterNumber: 1,
    verseCount: 11,
  },
  {
    bookNumber: 150,
    chapterNumber: 2,
    verseCount: 70,
  },
  {
    bookNumber: 150,
    chapterNumber: 3,
    verseCount: 13,
  },
  {
    bookNumber: 150,
    chapterNumber: 4,
    verseCount: 24,
  },
  {
    bookNumber: 150,
    chapterNumber: 5,
    verseCount: 17,
  },
  {
    bookNumber: 150,
    chapterNumber: 6,
    verseCount: 22,
  },
  {
    bookNumber: 150,
    chapterNumber: 7,
    verseCount: 28,
  },
  {
    bookNumber: 150,
    chapterNumber: 8,
    verseCount: 36,
  },
  {
    bookNumber: 150,
    chapterNumber: 9,
    verseCount: 15,
  },
  {
    bookNumber: 150,
    chapterNumber: 10,
    verseCount: 44,
  },
  {
    bookNumber: 160,
    chapterNumber: 1,
    verseCount: 11,
  },
  {
    bookNumber: 160,
    chapterNumber: 2,
    verseCount: 20,
  },
  {
    bookNumber: 160,
    chapterNumber: 3,
    verseCount: 32,
  },
  {
    bookNumber: 160,
    chapterNumber: 4,
    verseCount: 23,
  },
  {
    bookNumber: 160,
    chapterNumber: 5,
    verseCount: 19,
  },
  {
    bookNumber: 160,
    chapterNumber: 6,
    verseCount: 19,
  },
  {
    bookNumber: 160,
    chapterNumber: 7,
    verseCount: 73,
  },
  {
    bookNumber: 160,
    chapterNumber: 8,
    verseCount: 18,
  },
  {
    bookNumber: 160,
    chapterNumber: 9,
    verseCount: 38,
  },
  {
    bookNumber: 160,
    chapterNumber: 10,
    verseCount: 39,
  },
  {
    bookNumber: 160,
    chapterNumber: 11,
    verseCount: 36,
  },
  {
    bookNumber: 160,
    chapterNumber: 12,
    verseCount: 47,
  },
  {
    bookNumber: 160,
    chapterNumber: 13,
    verseCount: 31,
  },
  {
    bookNumber: 190,
    chapterNumber: 1,
    verseCount: 22,
  },
  {
    bookNumber: 190,
    chapterNumber: 2,
    verseCount: 23,
  },
  {
    bookNumber: 190,
    chapterNumber: 3,
    verseCount: 15,
  },
  {
    bookNumber: 190,
    chapterNumber: 4,
    verseCount: 17,
  },
  {
    bookNumber: 190,
    chapterNumber: 5,
    verseCount: 14,
  },
  {
    bookNumber: 190,
    chapterNumber: 6,
    verseCount: 14,
  },
  {
    bookNumber: 190,
    chapterNumber: 7,
    verseCount: 10,
  },
  {
    bookNumber: 190,
    chapterNumber: 8,
    verseCount: 17,
  },
  {
    bookNumber: 190,
    chapterNumber: 9,
    verseCount: 32,
  },
  {
    bookNumber: 190,
    chapterNumber: 10,
    verseCount: 3,
  },
  {
    bookNumber: 220,
    chapterNumber: 1,
    verseCount: 22,
  },
  {
    bookNumber: 220,
    chapterNumber: 2,
    verseCount: 13,
  },
  {
    bookNumber: 220,
    chapterNumber: 3,
    verseCount: 26,
  },
  {
    bookNumber: 220,
    chapterNumber: 4,
    verseCount: 21,
  },
  {
    bookNumber: 220,
    chapterNumber: 5,
    verseCount: 27,
  },
  {
    bookNumber: 220,
    chapterNumber: 6,
    verseCount: 30,
  },
  {
    bookNumber: 220,
    chapterNumber: 7,
    verseCount: 21,
  },
  {
    bookNumber: 220,
    chapterNumber: 8,
    verseCount: 22,
  },
  {
    bookNumber: 220,
    chapterNumber: 9,
    verseCount: 35,
  },
  {
    bookNumber: 220,
    chapterNumber: 10,
    verseCount: 22,
  },
  {
    bookNumber: 220,
    chapterNumber: 11,
    verseCount: 20,
  },
  {
    bookNumber: 220,
    chapterNumber: 12,
    verseCount: 25,
  },
  {
    bookNumber: 220,
    chapterNumber: 13,
    verseCount: 28,
  },
  {
    bookNumber: 220,
    chapterNumber: 14,
    verseCount: 22,
  },
  {
    bookNumber: 220,
    chapterNumber: 15,
    verseCount: 35,
  },
  {
    bookNumber: 220,
    chapterNumber: 16,
    verseCount: 22,
  },
  {
    bookNumber: 220,
    chapterNumber: 17,
    verseCount: 16,
  },
  {
    bookNumber: 220,
    chapterNumber: 18,
    verseCount: 21,
  },
  {
    bookNumber: 220,
    chapterNumber: 19,
    verseCount: 29,
  },
  {
    bookNumber: 220,
    chapterNumber: 20,
    verseCount: 29,
  },
  {
    bookNumber: 220,
    chapterNumber: 21,
    verseCount: 34,
  },
  {
    bookNumber: 220,
    chapterNumber: 22,
    verseCount: 30,
  },
  {
    bookNumber: 220,
    chapterNumber: 23,
    verseCount: 17,
  },
  {
    bookNumber: 220,
    chapterNumber: 24,
    verseCount: 25,
  },
  {
    bookNumber: 220,
    chapterNumber: 25,
    verseCount: 6,
  },
  {
    bookNumber: 220,
    chapterNumber: 26,
    verseCount: 14,
  },
  {
    bookNumber: 220,
    chapterNumber: 27,
    verseCount: 23,
  },
  {
    bookNumber: 220,
    chapterNumber: 28,
    verseCount: 28,
  },
  {
    bookNumber: 220,
    chapterNumber: 29,
    verseCount: 25,
  },
  {
    bookNumber: 220,
    chapterNumber: 30,
    verseCount: 31,
  },
  {
    bookNumber: 220,
    chapterNumber: 31,
    verseCount: 40,
  },
  {
    bookNumber: 220,
    chapterNumber: 32,
    verseCount: 22,
  },
  {
    bookNumber: 220,
    chapterNumber: 33,
    verseCount: 33,
  },
  {
    bookNumber: 220,
    chapterNumber: 34,
    verseCount: 37,
  },
  {
    bookNumber: 220,
    chapterNumber: 35,
    verseCount: 16,
  },
  {
    bookNumber: 220,
    chapterNumber: 36,
    verseCount: 33,
  },
  {
    bookNumber: 220,
    chapterNumber: 37,
    verseCount: 24,
  },
  {
    bookNumber: 220,
    chapterNumber: 38,
    verseCount: 41,
  },
  {
    bookNumber: 220,
    chapterNumber: 39,
    verseCount: 30,
  },
  {
    bookNumber: 220,
    chapterNumber: 40,
    verseCount: 24,
  },
  {
    bookNumber: 220,
    chapterNumber: 41,
    verseCount: 34,
  },
  {
    bookNumber: 220,
    chapterNumber: 42,
    verseCount: 17,
  },
  {
    bookNumber: 230,
    chapterNumber: 1,
    verseCount: 6,
  },
  {
    bookNumber: 230,
    chapterNumber: 2,
    verseCount: 12,
  },
  {
    bookNumber: 230,
    chapterNumber: 3,
    verseCount: 8,
  },
  {
    bookNumber: 230,
    chapterNumber: 4,
    verseCount: 8,
  },
  {
    bookNumber: 230,
    chapterNumber: 5,
    verseCount: 12,
  },
  {
    bookNumber: 230,
    chapterNumber: 6,
    verseCount: 10,
  },
  {
    bookNumber: 230,
    chapterNumber: 7,
    verseCount: 17,
  },
  {
    bookNumber: 230,
    chapterNumber: 8,
    verseCount: 9,
  },
  {
    bookNumber: 230,
    chapterNumber: 9,
    verseCount: 20,
  },
  {
    bookNumber: 230,
    chapterNumber: 10,
    verseCount: 18,
  },
  {
    bookNumber: 230,
    chapterNumber: 11,
    verseCount: 7,
  },
  {
    bookNumber: 230,
    chapterNumber: 12,
    verseCount: 8,
  },
  {
    bookNumber: 230,
    chapterNumber: 13,
    verseCount: 6,
  },
  {
    bookNumber: 230,
    chapterNumber: 14,
    verseCount: 7,
  },
  {
    bookNumber: 230,
    chapterNumber: 15,
    verseCount: 5,
  },
  {
    bookNumber: 230,
    chapterNumber: 16,
    verseCount: 11,
  },
  {
    bookNumber: 230,
    chapterNumber: 17,
    verseCount: 15,
  },
  {
    bookNumber: 230,
    chapterNumber: 18,
    verseCount: 50,
  },
  {
    bookNumber: 230,
    chapterNumber: 19,
    verseCount: 14,
  },
  {
    bookNumber: 230,
    chapterNumber: 20,
    verseCount: 9,
  },
  {
    bookNumber: 230,
    chapterNumber: 21,
    verseCount: 13,
  },
  {
    bookNumber: 230,
    chapterNumber: 22,
    verseCount: 31,
  },
  {
    bookNumber: 230,
    chapterNumber: 23,
    verseCount: 6,
  },
  {
    bookNumber: 230,
    chapterNumber: 24,
    verseCount: 10,
  },
  {
    bookNumber: 230,
    chapterNumber: 25,
    verseCount: 22,
  },
  {
    bookNumber: 230,
    chapterNumber: 26,
    verseCount: 12,
  },
  {
    bookNumber: 230,
    chapterNumber: 27,
    verseCount: 14,
  },
  {
    bookNumber: 230,
    chapterNumber: 28,
    verseCount: 9,
  },
  {
    bookNumber: 230,
    chapterNumber: 29,
    verseCount: 11,
  },
  {
    bookNumber: 230,
    chapterNumber: 30,
    verseCount: 12,
  },
  {
    bookNumber: 230,
    chapterNumber: 31,
    verseCount: 24,
  },
  {
    bookNumber: 230,
    chapterNumber: 32,
    verseCount: 11,
  },
  {
    bookNumber: 230,
    chapterNumber: 33,
    verseCount: 22,
  },
  {
    bookNumber: 230,
    chapterNumber: 34,
    verseCount: 22,
  },
  {
    bookNumber: 230,
    chapterNumber: 35,
    verseCount: 28,
  },
  {
    bookNumber: 230,
    chapterNumber: 36,
    verseCount: 12,
  },
  {
    bookNumber: 230,
    chapterNumber: 37,
    verseCount: 40,
  },
  {
    bookNumber: 230,
    chapterNumber: 38,
    verseCount: 22,
  },
  {
    bookNumber: 230,
    chapterNumber: 39,
    verseCount: 13,
  },
  {
    bookNumber: 230,
    chapterNumber: 40,
    verseCount: 17,
  },
  {
    bookNumber: 230,
    chapterNumber: 41,
    verseCount: 13,
  },
  {
    bookNumber: 230,
    chapterNumber: 42,
    verseCount: 11,
  },
  {
    bookNumber: 230,
    chapterNumber: 43,
    verseCount: 5,
  },
  {
    bookNumber: 230,
    chapterNumber: 44,
    verseCount: 26,
  },
  {
    bookNumber: 230,
    chapterNumber: 45,
    verseCount: 17,
  },
  {
    bookNumber: 230,
    chapterNumber: 46,
    verseCount: 11,
  },
  {
    bookNumber: 230,
    chapterNumber: 47,
    verseCount: 9,
  },
  {
    bookNumber: 230,
    chapterNumber: 48,
    verseCount: 14,
  },
  {
    bookNumber: 230,
    chapterNumber: 49,
    verseCount: 20,
  },
  {
    bookNumber: 230,
    chapterNumber: 50,
    verseCount: 23,
  },
  {
    bookNumber: 230,
    chapterNumber: 51,
    verseCount: 19,
  },
  {
    bookNumber: 230,
    chapterNumber: 52,
    verseCount: 9,
  },
  {
    bookNumber: 230,
    chapterNumber: 53,
    verseCount: 6,
  },
  {
    bookNumber: 230,
    chapterNumber: 54,
    verseCount: 7,
  },
  {
    bookNumber: 230,
    chapterNumber: 55,
    verseCount: 23,
  },
  {
    bookNumber: 230,
    chapterNumber: 56,
    verseCount: 13,
  },
  {
    bookNumber: 230,
    chapterNumber: 57,
    verseCount: 11,
  },
  {
    bookNumber: 230,
    chapterNumber: 58,
    verseCount: 11,
  },
  {
    bookNumber: 230,
    chapterNumber: 59,
    verseCount: 17,
  },
  {
    bookNumber: 230,
    chapterNumber: 60,
    verseCount: 12,
  },
  {
    bookNumber: 230,
    chapterNumber: 61,
    verseCount: 8,
  },
  {
    bookNumber: 230,
    chapterNumber: 62,
    verseCount: 12,
  },
  {
    bookNumber: 230,
    chapterNumber: 63,
    verseCount: 11,
  },
  {
    bookNumber: 230,
    chapterNumber: 64,
    verseCount: 10,
  },
  {
    bookNumber: 230,
    chapterNumber: 65,
    verseCount: 13,
  },
  {
    bookNumber: 230,
    chapterNumber: 66,
    verseCount: 20,
  },
  {
    bookNumber: 230,
    chapterNumber: 67,
    verseCount: 7,
  },
  {
    bookNumber: 230,
    chapterNumber: 68,
    verseCount: 35,
  },
  {
    bookNumber: 230,
    chapterNumber: 69,
    verseCount: 36,
  },
  {
    bookNumber: 230,
    chapterNumber: 70,
    verseCount: 5,
  },
  {
    bookNumber: 230,
    chapterNumber: 71,
    verseCount: 24,
  },
  {
    bookNumber: 230,
    chapterNumber: 72,
    verseCount: 20,
  },
  {
    bookNumber: 230,
    chapterNumber: 73,
    verseCount: 28,
  },
  {
    bookNumber: 230,
    chapterNumber: 74,
    verseCount: 23,
  },
  {
    bookNumber: 230,
    chapterNumber: 75,
    verseCount: 10,
  },
  {
    bookNumber: 230,
    chapterNumber: 76,
    verseCount: 12,
  },
  {
    bookNumber: 230,
    chapterNumber: 77,
    verseCount: 20,
  },
  {
    bookNumber: 230,
    chapterNumber: 78,
    verseCount: 72,
  },
  {
    bookNumber: 230,
    chapterNumber: 79,
    verseCount: 13,
  },
  {
    bookNumber: 230,
    chapterNumber: 80,
    verseCount: 19,
  },
  {
    bookNumber: 230,
    chapterNumber: 81,
    verseCount: 16,
  },
  {
    bookNumber: 230,
    chapterNumber: 82,
    verseCount: 8,
  },
  {
    bookNumber: 230,
    chapterNumber: 83,
    verseCount: 18,
  },
  {
    bookNumber: 230,
    chapterNumber: 84,
    verseCount: 12,
  },
  {
    bookNumber: 230,
    chapterNumber: 85,
    verseCount: 13,
  },
  {
    bookNumber: 230,
    chapterNumber: 86,
    verseCount: 17,
  },
  {
    bookNumber: 230,
    chapterNumber: 87,
    verseCount: 7,
  },
  {
    bookNumber: 230,
    chapterNumber: 88,
    verseCount: 18,
  },
  {
    bookNumber: 230,
    chapterNumber: 89,
    verseCount: 52,
  },
  {
    bookNumber: 230,
    chapterNumber: 90,
    verseCount: 17,
  },
  {
    bookNumber: 230,
    chapterNumber: 91,
    verseCount: 16,
  },
  {
    bookNumber: 230,
    chapterNumber: 92,
    verseCount: 15,
  },
  {
    bookNumber: 230,
    chapterNumber: 93,
    verseCount: 5,
  },
  {
    bookNumber: 230,
    chapterNumber: 94,
    verseCount: 23,
  },
  {
    bookNumber: 230,
    chapterNumber: 95,
    verseCount: 11,
  },
  {
    bookNumber: 230,
    chapterNumber: 96,
    verseCount: 13,
  },
  {
    bookNumber: 230,
    chapterNumber: 97,
    verseCount: 12,
  },
  {
    bookNumber: 230,
    chapterNumber: 98,
    verseCount: 9,
  },
  {
    bookNumber: 230,
    chapterNumber: 99,
    verseCount: 9,
  },
  {
    bookNumber: 230,
    chapterNumber: 100,
    verseCount: 5,
  },
  {
    bookNumber: 230,
    chapterNumber: 101,
    verseCount: 8,
  },
  {
    bookNumber: 230,
    chapterNumber: 102,
    verseCount: 28,
  },
  {
    bookNumber: 230,
    chapterNumber: 103,
    verseCount: 22,
  },
  {
    bookNumber: 230,
    chapterNumber: 104,
    verseCount: 35,
  },
  {
    bookNumber: 230,
    chapterNumber: 105,
    verseCount: 45,
  },
  {
    bookNumber: 230,
    chapterNumber: 106,
    verseCount: 48,
  },
  {
    bookNumber: 230,
    chapterNumber: 107,
    verseCount: 43,
  },
  {
    bookNumber: 230,
    chapterNumber: 108,
    verseCount: 13,
  },
  {
    bookNumber: 230,
    chapterNumber: 109,
    verseCount: 31,
  },
  {
    bookNumber: 230,
    chapterNumber: 110,
    verseCount: 7,
  },
  {
    bookNumber: 230,
    chapterNumber: 111,
    verseCount: 10,
  },
  {
    bookNumber: 230,
    chapterNumber: 112,
    verseCount: 10,
  },
  {
    bookNumber: 230,
    chapterNumber: 113,
    verseCount: 9,
  },
  {
    bookNumber: 230,
    chapterNumber: 114,
    verseCount: 8,
  },
  {
    bookNumber: 230,
    chapterNumber: 115,
    verseCount: 18,
  },
  {
    bookNumber: 230,
    chapterNumber: 116,
    verseCount: 19,
  },
  {
    bookNumber: 230,
    chapterNumber: 117,
    verseCount: 2,
  },
  {
    bookNumber: 230,
    chapterNumber: 118,
    verseCount: 29,
  },
  {
    bookNumber: 230,
    chapterNumber: 119,
    verseCount: 176,
  },
  {
    bookNumber: 230,
    chapterNumber: 120,
    verseCount: 7,
  },
  {
    bookNumber: 230,
    chapterNumber: 121,
    verseCount: 8,
  },
  {
    bookNumber: 230,
    chapterNumber: 122,
    verseCount: 9,
  },
  {
    bookNumber: 230,
    chapterNumber: 123,
    verseCount: 4,
  },
  {
    bookNumber: 230,
    chapterNumber: 124,
    verseCount: 8,
  },
  {
    bookNumber: 230,
    chapterNumber: 125,
    verseCount: 5,
  },
  {
    bookNumber: 230,
    chapterNumber: 126,
    verseCount: 6,
  },
  {
    bookNumber: 230,
    chapterNumber: 127,
    verseCount: 5,
  },
  {
    bookNumber: 230,
    chapterNumber: 128,
    verseCount: 6,
  },
  {
    bookNumber: 230,
    chapterNumber: 129,
    verseCount: 8,
  },
  {
    bookNumber: 230,
    chapterNumber: 130,
    verseCount: 8,
  },
  {
    bookNumber: 230,
    chapterNumber: 131,
    verseCount: 3,
  },
  {
    bookNumber: 230,
    chapterNumber: 132,
    verseCount: 18,
  },
  {
    bookNumber: 230,
    chapterNumber: 133,
    verseCount: 3,
  },
  {
    bookNumber: 230,
    chapterNumber: 134,
    verseCount: 3,
  },
  {
    bookNumber: 230,
    chapterNumber: 135,
    verseCount: 21,
  },
  {
    bookNumber: 230,
    chapterNumber: 136,
    verseCount: 26,
  },
  {
    bookNumber: 230,
    chapterNumber: 137,
    verseCount: 9,
  },
  {
    bookNumber: 230,
    chapterNumber: 138,
    verseCount: 8,
  },
  {
    bookNumber: 230,
    chapterNumber: 139,
    verseCount: 24,
  },
  {
    bookNumber: 230,
    chapterNumber: 140,
    verseCount: 13,
  },
  {
    bookNumber: 230,
    chapterNumber: 141,
    verseCount: 10,
  },
  {
    bookNumber: 230,
    chapterNumber: 142,
    verseCount: 7,
  },
  {
    bookNumber: 230,
    chapterNumber: 143,
    verseCount: 12,
  },
  {
    bookNumber: 230,
    chapterNumber: 144,
    verseCount: 15,
  },
  {
    bookNumber: 230,
    chapterNumber: 145,
    verseCount: 21,
  },
  {
    bookNumber: 230,
    chapterNumber: 146,
    verseCount: 10,
  },
  {
    bookNumber: 230,
    chapterNumber: 147,
    verseCount: 20,
  },
  {
    bookNumber: 230,
    chapterNumber: 148,
    verseCount: 14,
  },
  {
    bookNumber: 230,
    chapterNumber: 149,
    verseCount: 9,
  },
  {
    bookNumber: 230,
    chapterNumber: 150,
    verseCount: 6,
  },
  {
    bookNumber: 240,
    chapterNumber: 1,
    verseCount: 33,
  },
  {
    bookNumber: 240,
    chapterNumber: 2,
    verseCount: 22,
  },
  {
    bookNumber: 240,
    chapterNumber: 3,
    verseCount: 35,
  },
  {
    bookNumber: 240,
    chapterNumber: 4,
    verseCount: 27,
  },
  {
    bookNumber: 240,
    chapterNumber: 5,
    verseCount: 23,
  },
  {
    bookNumber: 240,
    chapterNumber: 6,
    verseCount: 35,
  },
  {
    bookNumber: 240,
    chapterNumber: 7,
    verseCount: 27,
  },
  {
    bookNumber: 240,
    chapterNumber: 8,
    verseCount: 36,
  },
  {
    bookNumber: 240,
    chapterNumber: 9,
    verseCount: 18,
  },
  {
    bookNumber: 240,
    chapterNumber: 10,
    verseCount: 32,
  },
  {
    bookNumber: 240,
    chapterNumber: 11,
    verseCount: 31,
  },
  {
    bookNumber: 240,
    chapterNumber: 12,
    verseCount: 28,
  },
  {
    bookNumber: 240,
    chapterNumber: 13,
    verseCount: 25,
  },
  {
    bookNumber: 240,
    chapterNumber: 14,
    verseCount: 35,
  },
  {
    bookNumber: 240,
    chapterNumber: 15,
    verseCount: 33,
  },
  {
    bookNumber: 240,
    chapterNumber: 16,
    verseCount: 33,
  },
  {
    bookNumber: 240,
    chapterNumber: 17,
    verseCount: 28,
  },
  {
    bookNumber: 240,
    chapterNumber: 18,
    verseCount: 24,
  },
  {
    bookNumber: 240,
    chapterNumber: 19,
    verseCount: 29,
  },
  {
    bookNumber: 240,
    chapterNumber: 20,
    verseCount: 30,
  },
  {
    bookNumber: 240,
    chapterNumber: 21,
    verseCount: 31,
  },
  {
    bookNumber: 240,
    chapterNumber: 22,
    verseCount: 29,
  },
  {
    bookNumber: 240,
    chapterNumber: 23,
    verseCount: 35,
  },
  {
    bookNumber: 240,
    chapterNumber: 24,
    verseCount: 34,
  },
  {
    bookNumber: 240,
    chapterNumber: 25,
    verseCount: 28,
  },
  {
    bookNumber: 240,
    chapterNumber: 26,
    verseCount: 28,
  },
  {
    bookNumber: 240,
    chapterNumber: 27,
    verseCount: 27,
  },
  {
    bookNumber: 240,
    chapterNumber: 28,
    verseCount: 28,
  },
  {
    bookNumber: 240,
    chapterNumber: 29,
    verseCount: 27,
  },
  {
    bookNumber: 240,
    chapterNumber: 30,
    verseCount: 33,
  },
  {
    bookNumber: 240,
    chapterNumber: 31,
    verseCount: 31,
  },
  {
    bookNumber: 250,
    chapterNumber: 1,
    verseCount: 18,
  },
  {
    bookNumber: 250,
    chapterNumber: 2,
    verseCount: 26,
  },
  {
    bookNumber: 250,
    chapterNumber: 3,
    verseCount: 22,
  },
  {
    bookNumber: 250,
    chapterNumber: 4,
    verseCount: 16,
  },
  {
    bookNumber: 250,
    chapterNumber: 5,
    verseCount: 20,
  },
  {
    bookNumber: 250,
    chapterNumber: 6,
    verseCount: 12,
  },
  {
    bookNumber: 250,
    chapterNumber: 7,
    verseCount: 29,
  },
  {
    bookNumber: 250,
    chapterNumber: 8,
    verseCount: 17,
  },
  {
    bookNumber: 250,
    chapterNumber: 9,
    verseCount: 18,
  },
  {
    bookNumber: 250,
    chapterNumber: 10,
    verseCount: 20,
  },
  {
    bookNumber: 250,
    chapterNumber: 11,
    verseCount: 10,
  },
  {
    bookNumber: 250,
    chapterNumber: 12,
    verseCount: 14,
  },
  {
    bookNumber: 260,
    chapterNumber: 1,
    verseCount: 17,
  },
  {
    bookNumber: 260,
    chapterNumber: 2,
    verseCount: 17,
  },
  {
    bookNumber: 260,
    chapterNumber: 3,
    verseCount: 11,
  },
  {
    bookNumber: 260,
    chapterNumber: 4,
    verseCount: 16,
  },
  {
    bookNumber: 260,
    chapterNumber: 5,
    verseCount: 16,
  },
  {
    bookNumber: 260,
    chapterNumber: 6,
    verseCount: 13,
  },
  {
    bookNumber: 260,
    chapterNumber: 7,
    verseCount: 13,
  },
  {
    bookNumber: 260,
    chapterNumber: 8,
    verseCount: 14,
  },
  {
    bookNumber: 290,
    chapterNumber: 1,
    verseCount: 31,
  },
  {
    bookNumber: 290,
    chapterNumber: 2,
    verseCount: 22,
  },
  {
    bookNumber: 290,
    chapterNumber: 3,
    verseCount: 26,
  },
  {
    bookNumber: 290,
    chapterNumber: 4,
    verseCount: 6,
  },
  {
    bookNumber: 290,
    chapterNumber: 5,
    verseCount: 30,
  },
  {
    bookNumber: 290,
    chapterNumber: 6,
    verseCount: 13,
  },
  {
    bookNumber: 290,
    chapterNumber: 7,
    verseCount: 25,
  },
  {
    bookNumber: 290,
    chapterNumber: 8,
    verseCount: 22,
  },
  {
    bookNumber: 290,
    chapterNumber: 9,
    verseCount: 21,
  },
  {
    bookNumber: 290,
    chapterNumber: 10,
    verseCount: 34,
  },
  {
    bookNumber: 290,
    chapterNumber: 11,
    verseCount: 16,
  },
  {
    bookNumber: 290,
    chapterNumber: 12,
    verseCount: 6,
  },
  {
    bookNumber: 290,
    chapterNumber: 13,
    verseCount: 22,
  },
  {
    bookNumber: 290,
    chapterNumber: 14,
    verseCount: 32,
  },
  {
    bookNumber: 290,
    chapterNumber: 15,
    verseCount: 9,
  },
  {
    bookNumber: 290,
    chapterNumber: 16,
    verseCount: 14,
  },
  {
    bookNumber: 290,
    chapterNumber: 17,
    verseCount: 14,
  },
  {
    bookNumber: 290,
    chapterNumber: 18,
    verseCount: 7,
  },
  {
    bookNumber: 290,
    chapterNumber: 19,
    verseCount: 25,
  },
  {
    bookNumber: 290,
    chapterNumber: 20,
    verseCount: 6,
  },
  {
    bookNumber: 290,
    chapterNumber: 21,
    verseCount: 17,
  },
  {
    bookNumber: 290,
    chapterNumber: 22,
    verseCount: 25,
  },
  {
    bookNumber: 290,
    chapterNumber: 23,
    verseCount: 18,
  },
  {
    bookNumber: 290,
    chapterNumber: 24,
    verseCount: 23,
  },
  {
    bookNumber: 290,
    chapterNumber: 25,
    verseCount: 12,
  },
  {
    bookNumber: 290,
    chapterNumber: 26,
    verseCount: 21,
  },
  {
    bookNumber: 290,
    chapterNumber: 27,
    verseCount: 13,
  },
  {
    bookNumber: 290,
    chapterNumber: 28,
    verseCount: 29,
  },
  {
    bookNumber: 290,
    chapterNumber: 29,
    verseCount: 24,
  },
  {
    bookNumber: 290,
    chapterNumber: 30,
    verseCount: 33,
  },
  {
    bookNumber: 290,
    chapterNumber: 31,
    verseCount: 9,
  },
  {
    bookNumber: 290,
    chapterNumber: 32,
    verseCount: 20,
  },
  {
    bookNumber: 290,
    chapterNumber: 33,
    verseCount: 24,
  },
  {
    bookNumber: 290,
    chapterNumber: 34,
    verseCount: 17,
  },
  {
    bookNumber: 290,
    chapterNumber: 35,
    verseCount: 10,
  },
  {
    bookNumber: 290,
    chapterNumber: 36,
    verseCount: 22,
  },
  {
    bookNumber: 290,
    chapterNumber: 37,
    verseCount: 38,
  },
  {
    bookNumber: 290,
    chapterNumber: 38,
    verseCount: 22,
  },
  {
    bookNumber: 290,
    chapterNumber: 39,
    verseCount: 8,
  },
  {
    bookNumber: 290,
    chapterNumber: 40,
    verseCount: 31,
  },
  {
    bookNumber: 290,
    chapterNumber: 41,
    verseCount: 29,
  },
  {
    bookNumber: 290,
    chapterNumber: 42,
    verseCount: 25,
  },
  {
    bookNumber: 290,
    chapterNumber: 43,
    verseCount: 28,
  },
  {
    bookNumber: 290,
    chapterNumber: 44,
    verseCount: 28,
  },
  {
    bookNumber: 290,
    chapterNumber: 45,
    verseCount: 25,
  },
  {
    bookNumber: 290,
    chapterNumber: 46,
    verseCount: 13,
  },
  {
    bookNumber: 290,
    chapterNumber: 47,
    verseCount: 15,
  },
  {
    bookNumber: 290,
    chapterNumber: 48,
    verseCount: 22,
  },
  {
    bookNumber: 290,
    chapterNumber: 49,
    verseCount: 26,
  },
  {
    bookNumber: 290,
    chapterNumber: 50,
    verseCount: 11,
  },
  {
    bookNumber: 290,
    chapterNumber: 51,
    verseCount: 23,
  },
  {
    bookNumber: 290,
    chapterNumber: 52,
    verseCount: 15,
  },
  {
    bookNumber: 290,
    chapterNumber: 53,
    verseCount: 12,
  },
  {
    bookNumber: 290,
    chapterNumber: 54,
    verseCount: 17,
  },
  {
    bookNumber: 290,
    chapterNumber: 55,
    verseCount: 13,
  },
  {
    bookNumber: 290,
    chapterNumber: 56,
    verseCount: 12,
  },
  {
    bookNumber: 290,
    chapterNumber: 57,
    verseCount: 21,
  },
  {
    bookNumber: 290,
    chapterNumber: 58,
    verseCount: 14,
  },
  {
    bookNumber: 290,
    chapterNumber: 59,
    verseCount: 21,
  },
  {
    bookNumber: 290,
    chapterNumber: 60,
    verseCount: 22,
  },
  {
    bookNumber: 290,
    chapterNumber: 61,
    verseCount: 11,
  },
  {
    bookNumber: 290,
    chapterNumber: 62,
    verseCount: 12,
  },
  {
    bookNumber: 290,
    chapterNumber: 63,
    verseCount: 19,
  },
  {
    bookNumber: 290,
    chapterNumber: 64,
    verseCount: 12,
  },
  {
    bookNumber: 290,
    chapterNumber: 65,
    verseCount: 25,
  },
  {
    bookNumber: 290,
    chapterNumber: 66,
    verseCount: 24,
  },
  {
    bookNumber: 300,
    chapterNumber: 1,
    verseCount: 19,
  },
  {
    bookNumber: 300,
    chapterNumber: 2,
    verseCount: 37,
  },
  {
    bookNumber: 300,
    chapterNumber: 3,
    verseCount: 25,
  },
  {
    bookNumber: 300,
    chapterNumber: 4,
    verseCount: 31,
  },
  {
    bookNumber: 300,
    chapterNumber: 5,
    verseCount: 31,
  },
  {
    bookNumber: 300,
    chapterNumber: 6,
    verseCount: 30,
  },
  {
    bookNumber: 300,
    chapterNumber: 7,
    verseCount: 34,
  },
  {
    bookNumber: 300,
    chapterNumber: 8,
    verseCount: 22,
  },
  {
    bookNumber: 300,
    chapterNumber: 9,
    verseCount: 26,
  },
  {
    bookNumber: 300,
    chapterNumber: 10,
    verseCount: 25,
  },
  {
    bookNumber: 300,
    chapterNumber: 11,
    verseCount: 23,
  },
  {
    bookNumber: 300,
    chapterNumber: 12,
    verseCount: 17,
  },
  {
    bookNumber: 300,
    chapterNumber: 13,
    verseCount: 27,
  },
  {
    bookNumber: 300,
    chapterNumber: 14,
    verseCount: 22,
  },
  {
    bookNumber: 300,
    chapterNumber: 15,
    verseCount: 21,
  },
  {
    bookNumber: 300,
    chapterNumber: 16,
    verseCount: 21,
  },
  {
    bookNumber: 300,
    chapterNumber: 17,
    verseCount: 27,
  },
  {
    bookNumber: 300,
    chapterNumber: 18,
    verseCount: 23,
  },
  {
    bookNumber: 300,
    chapterNumber: 19,
    verseCount: 15,
  },
  {
    bookNumber: 300,
    chapterNumber: 20,
    verseCount: 18,
  },
  {
    bookNumber: 300,
    chapterNumber: 21,
    verseCount: 14,
  },
  {
    bookNumber: 300,
    chapterNumber: 22,
    verseCount: 30,
  },
  {
    bookNumber: 300,
    chapterNumber: 23,
    verseCount: 40,
  },
  {
    bookNumber: 300,
    chapterNumber: 24,
    verseCount: 10,
  },
  {
    bookNumber: 300,
    chapterNumber: 25,
    verseCount: 38,
  },
  {
    bookNumber: 300,
    chapterNumber: 26,
    verseCount: 24,
  },
  {
    bookNumber: 300,
    chapterNumber: 27,
    verseCount: 22,
  },
  {
    bookNumber: 300,
    chapterNumber: 28,
    verseCount: 17,
  },
  {
    bookNumber: 300,
    chapterNumber: 29,
    verseCount: 32,
  },
  {
    bookNumber: 300,
    chapterNumber: 30,
    verseCount: 24,
  },
  {
    bookNumber: 300,
    chapterNumber: 31,
    verseCount: 40,
  },
  {
    bookNumber: 300,
    chapterNumber: 32,
    verseCount: 44,
  },
  {
    bookNumber: 300,
    chapterNumber: 33,
    verseCount: 26,
  },
  {
    bookNumber: 300,
    chapterNumber: 34,
    verseCount: 22,
  },
  {
    bookNumber: 300,
    chapterNumber: 35,
    verseCount: 19,
  },
  {
    bookNumber: 300,
    chapterNumber: 36,
    verseCount: 32,
  },
  {
    bookNumber: 300,
    chapterNumber: 37,
    verseCount: 21,
  },
  {
    bookNumber: 300,
    chapterNumber: 38,
    verseCount: 28,
  },
  {
    bookNumber: 300,
    chapterNumber: 39,
    verseCount: 18,
  },
  {
    bookNumber: 300,
    chapterNumber: 40,
    verseCount: 16,
  },
  {
    bookNumber: 300,
    chapterNumber: 41,
    verseCount: 18,
  },
  {
    bookNumber: 300,
    chapterNumber: 42,
    verseCount: 22,
  },
  {
    bookNumber: 300,
    chapterNumber: 43,
    verseCount: 13,
  },
  {
    bookNumber: 300,
    chapterNumber: 44,
    verseCount: 30,
  },
  {
    bookNumber: 300,
    chapterNumber: 45,
    verseCount: 5,
  },
  {
    bookNumber: 300,
    chapterNumber: 46,
    verseCount: 28,
  },
  {
    bookNumber: 300,
    chapterNumber: 47,
    verseCount: 7,
  },
  {
    bookNumber: 300,
    chapterNumber: 48,
    verseCount: 47,
  },
  {
    bookNumber: 300,
    chapterNumber: 49,
    verseCount: 39,
  },
  {
    bookNumber: 300,
    chapterNumber: 50,
    verseCount: 46,
  },
  {
    bookNumber: 300,
    chapterNumber: 51,
    verseCount: 64,
  },
  {
    bookNumber: 300,
    chapterNumber: 52,
    verseCount: 34,
  },
  {
    bookNumber: 310,
    chapterNumber: 1,
    verseCount: 22,
  },
  {
    bookNumber: 310,
    chapterNumber: 2,
    verseCount: 22,
  },
  {
    bookNumber: 310,
    chapterNumber: 3,
    verseCount: 66,
  },
  {
    bookNumber: 310,
    chapterNumber: 4,
    verseCount: 22,
  },
  {
    bookNumber: 310,
    chapterNumber: 5,
    verseCount: 22,
  },
  {
    bookNumber: 330,
    chapterNumber: 1,
    verseCount: 28,
  },
  {
    bookNumber: 330,
    chapterNumber: 2,
    verseCount: 10,
  },
  {
    bookNumber: 330,
    chapterNumber: 3,
    verseCount: 27,
  },
  {
    bookNumber: 330,
    chapterNumber: 4,
    verseCount: 17,
  },
  {
    bookNumber: 330,
    chapterNumber: 5,
    verseCount: 17,
  },
  {
    bookNumber: 330,
    chapterNumber: 6,
    verseCount: 14,
  },
  {
    bookNumber: 330,
    chapterNumber: 7,
    verseCount: 27,
  },
  {
    bookNumber: 330,
    chapterNumber: 8,
    verseCount: 18,
  },
  {
    bookNumber: 330,
    chapterNumber: 9,
    verseCount: 11,
  },
  {
    bookNumber: 330,
    chapterNumber: 10,
    verseCount: 22,
  },
  {
    bookNumber: 330,
    chapterNumber: 11,
    verseCount: 25,
  },
  {
    bookNumber: 330,
    chapterNumber: 12,
    verseCount: 28,
  },
  {
    bookNumber: 330,
    chapterNumber: 13,
    verseCount: 23,
  },
  {
    bookNumber: 330,
    chapterNumber: 14,
    verseCount: 23,
  },
  {
    bookNumber: 330,
    chapterNumber: 15,
    verseCount: 8,
  },
  {
    bookNumber: 330,
    chapterNumber: 16,
    verseCount: 63,
  },
  {
    bookNumber: 330,
    chapterNumber: 17,
    verseCount: 24,
  },
  {
    bookNumber: 330,
    chapterNumber: 18,
    verseCount: 32,
  },
  {
    bookNumber: 330,
    chapterNumber: 19,
    verseCount: 14,
  },
  {
    bookNumber: 330,
    chapterNumber: 20,
    verseCount: 49,
  },
  {
    bookNumber: 330,
    chapterNumber: 21,
    verseCount: 32,
  },
  {
    bookNumber: 330,
    chapterNumber: 22,
    verseCount: 31,
  },
  {
    bookNumber: 330,
    chapterNumber: 23,
    verseCount: 49,
  },
  {
    bookNumber: 330,
    chapterNumber: 24,
    verseCount: 27,
  },
  {
    bookNumber: 330,
    chapterNumber: 25,
    verseCount: 17,
  },
  {
    bookNumber: 330,
    chapterNumber: 26,
    verseCount: 21,
  },
  {
    bookNumber: 330,
    chapterNumber: 27,
    verseCount: 36,
  },
  {
    bookNumber: 330,
    chapterNumber: 28,
    verseCount: 26,
  },
  {
    bookNumber: 330,
    chapterNumber: 29,
    verseCount: 21,
  },
  {
    bookNumber: 330,
    chapterNumber: 30,
    verseCount: 26,
  },
  {
    bookNumber: 330,
    chapterNumber: 31,
    verseCount: 18,
  },
  {
    bookNumber: 330,
    chapterNumber: 32,
    verseCount: 32,
  },
  {
    bookNumber: 330,
    chapterNumber: 33,
    verseCount: 33,
  },
  {
    bookNumber: 330,
    chapterNumber: 34,
    verseCount: 31,
  },
  {
    bookNumber: 330,
    chapterNumber: 35,
    verseCount: 15,
  },
  {
    bookNumber: 330,
    chapterNumber: 36,
    verseCount: 38,
  },
  {
    bookNumber: 330,
    chapterNumber: 37,
    verseCount: 28,
  },
  {
    bookNumber: 330,
    chapterNumber: 38,
    verseCount: 23,
  },
  {
    bookNumber: 330,
    chapterNumber: 39,
    verseCount: 29,
  },
  {
    bookNumber: 330,
    chapterNumber: 40,
    verseCount: 49,
  },
  {
    bookNumber: 330,
    chapterNumber: 41,
    verseCount: 26,
  },
  {
    bookNumber: 330,
    chapterNumber: 42,
    verseCount: 20,
  },
  {
    bookNumber: 330,
    chapterNumber: 43,
    verseCount: 27,
  },
  {
    bookNumber: 330,
    chapterNumber: 44,
    verseCount: 31,
  },
  {
    bookNumber: 330,
    chapterNumber: 45,
    verseCount: 25,
  },
  {
    bookNumber: 330,
    chapterNumber: 46,
    verseCount: 24,
  },
  {
    bookNumber: 330,
    chapterNumber: 47,
    verseCount: 23,
  },
  {
    bookNumber: 330,
    chapterNumber: 48,
    verseCount: 35,
  },
  {
    bookNumber: 340,
    chapterNumber: 1,
    verseCount: 21,
  },
  {
    bookNumber: 340,
    chapterNumber: 2,
    verseCount: 49,
  },
  {
    bookNumber: 340,
    chapterNumber: 3,
    verseCount: 30,
  },
  {
    bookNumber: 340,
    chapterNumber: 4,
    verseCount: 37,
  },
  {
    bookNumber: 340,
    chapterNumber: 5,
    verseCount: 31,
  },
  {
    bookNumber: 340,
    chapterNumber: 6,
    verseCount: 28,
  },
  {
    bookNumber: 340,
    chapterNumber: 7,
    verseCount: 28,
  },
  {
    bookNumber: 340,
    chapterNumber: 8,
    verseCount: 27,
  },
  {
    bookNumber: 340,
    chapterNumber: 9,
    verseCount: 27,
  },
  {
    bookNumber: 340,
    chapterNumber: 10,
    verseCount: 21,
  },
  {
    bookNumber: 340,
    chapterNumber: 11,
    verseCount: 45,
  },
  {
    bookNumber: 340,
    chapterNumber: 12,
    verseCount: 13,
  },
  {
    bookNumber: 350,
    chapterNumber: 1,
    verseCount: 11,
  },
  {
    bookNumber: 350,
    chapterNumber: 2,
    verseCount: 23,
  },
  {
    bookNumber: 350,
    chapterNumber: 3,
    verseCount: 5,
  },
  {
    bookNumber: 350,
    chapterNumber: 4,
    verseCount: 19,
  },
  {
    bookNumber: 350,
    chapterNumber: 5,
    verseCount: 15,
  },
  {
    bookNumber: 350,
    chapterNumber: 6,
    verseCount: 11,
  },
  {
    bookNumber: 350,
    chapterNumber: 7,
    verseCount: 16,
  },
  {
    bookNumber: 350,
    chapterNumber: 8,
    verseCount: 14,
  },
  {
    bookNumber: 350,
    chapterNumber: 9,
    verseCount: 17,
  },
  {
    bookNumber: 350,
    chapterNumber: 10,
    verseCount: 15,
  },
  {
    bookNumber: 350,
    chapterNumber: 11,
    verseCount: 12,
  },
  {
    bookNumber: 350,
    chapterNumber: 12,
    verseCount: 14,
  },
  {
    bookNumber: 350,
    chapterNumber: 13,
    verseCount: 16,
  },
  {
    bookNumber: 350,
    chapterNumber: 14,
    verseCount: 9,
  },
  {
    bookNumber: 360,
    chapterNumber: 1,
    verseCount: 20,
  },
  {
    bookNumber: 360,
    chapterNumber: 2,
    verseCount: 32,
  },
  {
    bookNumber: 360,
    chapterNumber: 3,
    verseCount: 21,
  },
  {
    bookNumber: 370,
    chapterNumber: 1,
    verseCount: 15,
  },
  {
    bookNumber: 370,
    chapterNumber: 2,
    verseCount: 16,
  },
  {
    bookNumber: 370,
    chapterNumber: 3,
    verseCount: 15,
  },
  {
    bookNumber: 370,
    chapterNumber: 4,
    verseCount: 13,
  },
  {
    bookNumber: 370,
    chapterNumber: 5,
    verseCount: 27,
  },
  {
    bookNumber: 370,
    chapterNumber: 6,
    verseCount: 14,
  },
  {
    bookNumber: 370,
    chapterNumber: 7,
    verseCount: 17,
  },
  {
    bookNumber: 370,
    chapterNumber: 8,
    verseCount: 14,
  },
  {
    bookNumber: 370,
    chapterNumber: 9,
    verseCount: 15,
  },
  {
    bookNumber: 380,
    chapterNumber: 1,
    verseCount: 21,
  },
  {
    bookNumber: 390,
    chapterNumber: 1,
    verseCount: 17,
  },
  {
    bookNumber: 390,
    chapterNumber: 2,
    verseCount: 10,
  },
  {
    bookNumber: 390,
    chapterNumber: 3,
    verseCount: 10,
  },
  {
    bookNumber: 390,
    chapterNumber: 4,
    verseCount: 11,
  },
  {
    bookNumber: 400,
    chapterNumber: 1,
    verseCount: 16,
  },
  {
    bookNumber: 400,
    chapterNumber: 2,
    verseCount: 13,
  },
  {
    bookNumber: 400,
    chapterNumber: 3,
    verseCount: 12,
  },
  {
    bookNumber: 400,
    chapterNumber: 4,
    verseCount: 13,
  },
  {
    bookNumber: 400,
    chapterNumber: 5,
    verseCount: 15,
  },
  {
    bookNumber: 400,
    chapterNumber: 6,
    verseCount: 16,
  },
  {
    bookNumber: 400,
    chapterNumber: 7,
    verseCount: 20,
  },
  {
    bookNumber: 410,
    chapterNumber: 1,
    verseCount: 15,
  },
  {
    bookNumber: 410,
    chapterNumber: 2,
    verseCount: 13,
  },
  {
    bookNumber: 410,
    chapterNumber: 3,
    verseCount: 19,
  },
  {
    bookNumber: 420,
    chapterNumber: 1,
    verseCount: 17,
  },
  {
    bookNumber: 420,
    chapterNumber: 2,
    verseCount: 20,
  },
  {
    bookNumber: 420,
    chapterNumber: 3,
    verseCount: 19,
  },
  {
    bookNumber: 430,
    chapterNumber: 1,
    verseCount: 18,
  },
  {
    bookNumber: 430,
    chapterNumber: 2,
    verseCount: 15,
  },
  {
    bookNumber: 430,
    chapterNumber: 3,
    verseCount: 20,
  },
  {
    bookNumber: 440,
    chapterNumber: 1,
    verseCount: 15,
  },
  {
    bookNumber: 440,
    chapterNumber: 2,
    verseCount: 23,
  },
  {
    bookNumber: 450,
    chapterNumber: 1,
    verseCount: 21,
  },
  {
    bookNumber: 450,
    chapterNumber: 2,
    verseCount: 13,
  },
  {
    bookNumber: 450,
    chapterNumber: 3,
    verseCount: 10,
  },
  {
    bookNumber: 450,
    chapterNumber: 4,
    verseCount: 14,
  },
  {
    bookNumber: 450,
    chapterNumber: 5,
    verseCount: 11,
  },
  {
    bookNumber: 450,
    chapterNumber: 6,
    verseCount: 15,
  },
  {
    bookNumber: 450,
    chapterNumber: 7,
    verseCount: 14,
  },
  {
    bookNumber: 450,
    chapterNumber: 8,
    verseCount: 23,
  },
  {
    bookNumber: 450,
    chapterNumber: 9,
    verseCount: 17,
  },
  {
    bookNumber: 450,
    chapterNumber: 10,
    verseCount: 12,
  },
  {
    bookNumber: 450,
    chapterNumber: 11,
    verseCount: 17,
  },
  {
    bookNumber: 450,
    chapterNumber: 12,
    verseCount: 14,
  },
  {
    bookNumber: 450,
    chapterNumber: 13,
    verseCount: 9,
  },
  {
    bookNumber: 450,
    chapterNumber: 14,
    verseCount: 21,
  },
  {
    bookNumber: 460,
    chapterNumber: 1,
    verseCount: 14,
  },
  {
    bookNumber: 460,
    chapterNumber: 2,
    verseCount: 17,
  },
  {
    bookNumber: 460,
    chapterNumber: 3,
    verseCount: 18,
  },
  {
    bookNumber: 460,
    chapterNumber: 4,
    verseCount: 6,
  },
  {
    bookNumber: 470,
    chapterNumber: 1,
    verseCount: 25,
  },
  {
    bookNumber: 470,
    chapterNumber: 2,
    verseCount: 23,
  },
  {
    bookNumber: 470,
    chapterNumber: 3,
    verseCount: 17,
  },
  {
    bookNumber: 470,
    chapterNumber: 4,
    verseCount: 25,
  },
  {
    bookNumber: 470,
    chapterNumber: 5,
    verseCount: 48,
  },
  {
    bookNumber: 470,
    chapterNumber: 6,
    verseCount: 34,
  },
  {
    bookNumber: 470,
    chapterNumber: 7,
    verseCount: 29,
  },
  {
    bookNumber: 470,
    chapterNumber: 8,
    verseCount: 34,
  },
  {
    bookNumber: 470,
    chapterNumber: 9,
    verseCount: 38,
  },
  {
    bookNumber: 470,
    chapterNumber: 10,
    verseCount: 42,
  },
  {
    bookNumber: 470,
    chapterNumber: 11,
    verseCount: 30,
  },
  {
    bookNumber: 470,
    chapterNumber: 12,
    verseCount: 50,
  },
  {
    bookNumber: 470,
    chapterNumber: 13,
    verseCount: 58,
  },
  {
    bookNumber: 470,
    chapterNumber: 14,
    verseCount: 36,
  },
  {
    bookNumber: 470,
    chapterNumber: 15,
    verseCount: 39,
  },
  {
    bookNumber: 470,
    chapterNumber: 16,
    verseCount: 28,
  },
  {
    bookNumber: 470,
    chapterNumber: 17,
    verseCount: 27,
  },
  {
    bookNumber: 470,
    chapterNumber: 18,
    verseCount: 35,
  },
  {
    bookNumber: 470,
    chapterNumber: 19,
    verseCount: 30,
  },
  {
    bookNumber: 470,
    chapterNumber: 20,
    verseCount: 34,
  },
  {
    bookNumber: 470,
    chapterNumber: 21,
    verseCount: 46,
  },
  {
    bookNumber: 470,
    chapterNumber: 22,
    verseCount: 46,
  },
  {
    bookNumber: 470,
    chapterNumber: 23,
    verseCount: 39,
  },
  {
    bookNumber: 470,
    chapterNumber: 24,
    verseCount: 51,
  },
  {
    bookNumber: 470,
    chapterNumber: 25,
    verseCount: 46,
  },
  {
    bookNumber: 470,
    chapterNumber: 26,
    verseCount: 75,
  },
  {
    bookNumber: 470,
    chapterNumber: 27,
    verseCount: 66,
  },
  {
    bookNumber: 470,
    chapterNumber: 28,
    verseCount: 20,
  },
  {
    bookNumber: 480,
    chapterNumber: 1,
    verseCount: 45,
  },
  {
    bookNumber: 480,
    chapterNumber: 2,
    verseCount: 28,
  },
  {
    bookNumber: 480,
    chapterNumber: 3,
    verseCount: 35,
  },
  {
    bookNumber: 480,
    chapterNumber: 4,
    verseCount: 41,
  },
  {
    bookNumber: 480,
    chapterNumber: 5,
    verseCount: 43,
  },
  {
    bookNumber: 480,
    chapterNumber: 6,
    verseCount: 56,
  },
  {
    bookNumber: 480,
    chapterNumber: 7,
    verseCount: 37,
  },
  {
    bookNumber: 480,
    chapterNumber: 8,
    verseCount: 38,
  },
  {
    bookNumber: 480,
    chapterNumber: 9,
    verseCount: 50,
  },
  {
    bookNumber: 480,
    chapterNumber: 10,
    verseCount: 52,
  },
  {
    bookNumber: 480,
    chapterNumber: 11,
    verseCount: 33,
  },
  {
    bookNumber: 480,
    chapterNumber: 12,
    verseCount: 44,
  },
  {
    bookNumber: 480,
    chapterNumber: 13,
    verseCount: 37,
  },
  {
    bookNumber: 480,
    chapterNumber: 14,
    verseCount: 72,
  },
  {
    bookNumber: 480,
    chapterNumber: 15,
    verseCount: 47,
  },
  {
    bookNumber: 480,
    chapterNumber: 16,
    verseCount: 20,
  },
  {
    bookNumber: 490,
    chapterNumber: 1,
    verseCount: 80,
  },
  {
    bookNumber: 490,
    chapterNumber: 2,
    verseCount: 52,
  },
  {
    bookNumber: 490,
    chapterNumber: 3,
    verseCount: 38,
  },
  {
    bookNumber: 490,
    chapterNumber: 4,
    verseCount: 44,
  },
  {
    bookNumber: 490,
    chapterNumber: 5,
    verseCount: 39,
  },
  {
    bookNumber: 490,
    chapterNumber: 6,
    verseCount: 49,
  },
  {
    bookNumber: 490,
    chapterNumber: 7,
    verseCount: 50,
  },
  {
    bookNumber: 490,
    chapterNumber: 8,
    verseCount: 56,
  },
  {
    bookNumber: 490,
    chapterNumber: 9,
    verseCount: 62,
  },
  {
    bookNumber: 490,
    chapterNumber: 10,
    verseCount: 42,
  },
  {
    bookNumber: 490,
    chapterNumber: 11,
    verseCount: 54,
  },
  {
    bookNumber: 490,
    chapterNumber: 12,
    verseCount: 59,
  },
  {
    bookNumber: 490,
    chapterNumber: 13,
    verseCount: 35,
  },
  {
    bookNumber: 490,
    chapterNumber: 14,
    verseCount: 35,
  },
  {
    bookNumber: 490,
    chapterNumber: 15,
    verseCount: 32,
  },
  {
    bookNumber: 490,
    chapterNumber: 16,
    verseCount: 31,
  },
  {
    bookNumber: 490,
    chapterNumber: 17,
    verseCount: 37,
  },
  {
    bookNumber: 490,
    chapterNumber: 18,
    verseCount: 43,
  },
  {
    bookNumber: 490,
    chapterNumber: 19,
    verseCount: 48,
  },
  {
    bookNumber: 490,
    chapterNumber: 20,
    verseCount: 47,
  },
  {
    bookNumber: 490,
    chapterNumber: 21,
    verseCount: 38,
  },
  {
    bookNumber: 490,
    chapterNumber: 22,
    verseCount: 71,
  },
  {
    bookNumber: 490,
    chapterNumber: 23,
    verseCount: 56,
  },
  {
    bookNumber: 490,
    chapterNumber: 24,
    verseCount: 53,
  },
  {
    bookNumber: 500,
    chapterNumber: 1,
    verseCount: 51,
  },
  {
    bookNumber: 500,
    chapterNumber: 2,
    verseCount: 25,
  },
  {
    bookNumber: 500,
    chapterNumber: 3,
    verseCount: 36,
  },
  {
    bookNumber: 500,
    chapterNumber: 4,
    verseCount: 54,
  },
  {
    bookNumber: 500,
    chapterNumber: 5,
    verseCount: 47,
  },
  {
    bookNumber: 500,
    chapterNumber: 6,
    verseCount: 71,
  },
  {
    bookNumber: 500,
    chapterNumber: 7,
    verseCount: 53,
  },
  {
    bookNumber: 500,
    chapterNumber: 8,
    verseCount: 59,
  },
  {
    bookNumber: 500,
    chapterNumber: 9,
    verseCount: 41,
  },
  {
    bookNumber: 500,
    chapterNumber: 10,
    verseCount: 42,
  },
  {
    bookNumber: 500,
    chapterNumber: 11,
    verseCount: 57,
  },
  {
    bookNumber: 500,
    chapterNumber: 12,
    verseCount: 50,
  },
  {
    bookNumber: 500,
    chapterNumber: 13,
    verseCount: 38,
  },
  {
    bookNumber: 500,
    chapterNumber: 14,
    verseCount: 31,
  },
  {
    bookNumber: 500,
    chapterNumber: 15,
    verseCount: 27,
  },
  {
    bookNumber: 500,
    chapterNumber: 16,
    verseCount: 33,
  },
  {
    bookNumber: 500,
    chapterNumber: 17,
    verseCount: 26,
  },
  {
    bookNumber: 500,
    chapterNumber: 18,
    verseCount: 40,
  },
  {
    bookNumber: 500,
    chapterNumber: 19,
    verseCount: 42,
  },
  {
    bookNumber: 500,
    chapterNumber: 20,
    verseCount: 31,
  },
  {
    bookNumber: 500,
    chapterNumber: 21,
    verseCount: 25,
  },
  {
    bookNumber: 510,
    chapterNumber: 1,
    verseCount: 26,
  },
  {
    bookNumber: 510,
    chapterNumber: 2,
    verseCount: 47,
  },
  {
    bookNumber: 510,
    chapterNumber: 3,
    verseCount: 26,
  },
  {
    bookNumber: 510,
    chapterNumber: 4,
    verseCount: 37,
  },
  {
    bookNumber: 510,
    chapterNumber: 5,
    verseCount: 42,
  },
  {
    bookNumber: 510,
    chapterNumber: 6,
    verseCount: 15,
  },
  {
    bookNumber: 510,
    chapterNumber: 7,
    verseCount: 60,
  },
  {
    bookNumber: 510,
    chapterNumber: 8,
    verseCount: 40,
  },
  {
    bookNumber: 510,
    chapterNumber: 9,
    verseCount: 43,
  },
  {
    bookNumber: 510,
    chapterNumber: 10,
    verseCount: 48,
  },
  {
    bookNumber: 510,
    chapterNumber: 11,
    verseCount: 30,
  },
  {
    bookNumber: 510,
    chapterNumber: 12,
    verseCount: 25,
  },
  {
    bookNumber: 510,
    chapterNumber: 13,
    verseCount: 52,
  },
  {
    bookNumber: 510,
    chapterNumber: 14,
    verseCount: 28,
  },
  {
    bookNumber: 510,
    chapterNumber: 15,
    verseCount: 41,
  },
  {
    bookNumber: 510,
    chapterNumber: 16,
    verseCount: 40,
  },
  {
    bookNumber: 510,
    chapterNumber: 17,
    verseCount: 34,
  },
  {
    bookNumber: 510,
    chapterNumber: 18,
    verseCount: 28,
  },
  {
    bookNumber: 510,
    chapterNumber: 19,
    verseCount: 41,
  },
  {
    bookNumber: 510,
    chapterNumber: 20,
    verseCount: 38,
  },
  {
    bookNumber: 510,
    chapterNumber: 21,
    verseCount: 40,
  },
  {
    bookNumber: 510,
    chapterNumber: 22,
    verseCount: 30,
  },
  {
    bookNumber: 510,
    chapterNumber: 23,
    verseCount: 35,
  },
  {
    bookNumber: 510,
    chapterNumber: 24,
    verseCount: 27,
  },
  {
    bookNumber: 510,
    chapterNumber: 25,
    verseCount: 27,
  },
  {
    bookNumber: 510,
    chapterNumber: 26,
    verseCount: 32,
  },
  {
    bookNumber: 510,
    chapterNumber: 27,
    verseCount: 44,
  },
  {
    bookNumber: 510,
    chapterNumber: 28,
    verseCount: 31,
  },
  {
    bookNumber: 520,
    chapterNumber: 1,
    verseCount: 32,
  },
  {
    bookNumber: 520,
    chapterNumber: 2,
    verseCount: 29,
  },
  {
    bookNumber: 520,
    chapterNumber: 3,
    verseCount: 31,
  },
  {
    bookNumber: 520,
    chapterNumber: 4,
    verseCount: 25,
  },
  {
    bookNumber: 520,
    chapterNumber: 5,
    verseCount: 21,
  },
  {
    bookNumber: 520,
    chapterNumber: 6,
    verseCount: 23,
  },
  {
    bookNumber: 520,
    chapterNumber: 7,
    verseCount: 25,
  },
  {
    bookNumber: 520,
    chapterNumber: 8,
    verseCount: 39,
  },
  {
    bookNumber: 520,
    chapterNumber: 9,
    verseCount: 33,
  },
  {
    bookNumber: 520,
    chapterNumber: 10,
    verseCount: 21,
  },
  {
    bookNumber: 520,
    chapterNumber: 11,
    verseCount: 36,
  },
  {
    bookNumber: 520,
    chapterNumber: 12,
    verseCount: 21,
  },
  {
    bookNumber: 520,
    chapterNumber: 13,
    verseCount: 14,
  },
  {
    bookNumber: 520,
    chapterNumber: 14,
    verseCount: 23,
  },
  {
    bookNumber: 520,
    chapterNumber: 15,
    verseCount: 33,
  },
  {
    bookNumber: 520,
    chapterNumber: 16,
    verseCount: 27,
  },
  {
    bookNumber: 530,
    chapterNumber: 1,
    verseCount: 31,
  },
  {
    bookNumber: 530,
    chapterNumber: 2,
    verseCount: 16,
  },
  {
    bookNumber: 530,
    chapterNumber: 3,
    verseCount: 23,
  },
  {
    bookNumber: 530,
    chapterNumber: 4,
    verseCount: 21,
  },
  {
    bookNumber: 530,
    chapterNumber: 5,
    verseCount: 13,
  },
  {
    bookNumber: 530,
    chapterNumber: 6,
    verseCount: 20,
  },
  {
    bookNumber: 530,
    chapterNumber: 7,
    verseCount: 40,
  },
  {
    bookNumber: 530,
    chapterNumber: 8,
    verseCount: 13,
  },
  {
    bookNumber: 530,
    chapterNumber: 9,
    verseCount: 27,
  },
  {
    bookNumber: 530,
    chapterNumber: 10,
    verseCount: 33,
  },
  {
    bookNumber: 530,
    chapterNumber: 11,
    verseCount: 34,
  },
  {
    bookNumber: 530,
    chapterNumber: 12,
    verseCount: 31,
  },
  {
    bookNumber: 530,
    chapterNumber: 13,
    verseCount: 13,
  },
  {
    bookNumber: 530,
    chapterNumber: 14,
    verseCount: 40,
  },
  {
    bookNumber: 530,
    chapterNumber: 15,
    verseCount: 58,
  },
  {
    bookNumber: 530,
    chapterNumber: 16,
    verseCount: 24,
  },
  {
    bookNumber: 540,
    chapterNumber: 1,
    verseCount: 24,
  },
  {
    bookNumber: 540,
    chapterNumber: 2,
    verseCount: 17,
  },
  {
    bookNumber: 540,
    chapterNumber: 3,
    verseCount: 18,
  },
  {
    bookNumber: 540,
    chapterNumber: 4,
    verseCount: 18,
  },
  {
    bookNumber: 540,
    chapterNumber: 5,
    verseCount: 21,
  },
  {
    bookNumber: 540,
    chapterNumber: 6,
    verseCount: 18,
  },
  {
    bookNumber: 540,
    chapterNumber: 7,
    verseCount: 16,
  },
  {
    bookNumber: 540,
    chapterNumber: 8,
    verseCount: 24,
  },
  {
    bookNumber: 540,
    chapterNumber: 9,
    verseCount: 15,
  },
  {
    bookNumber: 540,
    chapterNumber: 10,
    verseCount: 18,
  },
  {
    bookNumber: 540,
    chapterNumber: 11,
    verseCount: 33,
  },
  {
    bookNumber: 540,
    chapterNumber: 12,
    verseCount: 21,
  },
  {
    bookNumber: 540,
    chapterNumber: 13,
    verseCount: 14,
  },
  {
    bookNumber: 550,
    chapterNumber: 1,
    verseCount: 24,
  },
  {
    bookNumber: 550,
    chapterNumber: 2,
    verseCount: 21,
  },
  {
    bookNumber: 550,
    chapterNumber: 3,
    verseCount: 29,
  },
  {
    bookNumber: 550,
    chapterNumber: 4,
    verseCount: 31,
  },
  {
    bookNumber: 550,
    chapterNumber: 5,
    verseCount: 26,
  },
  {
    bookNumber: 550,
    chapterNumber: 6,
    verseCount: 18,
  },
  {
    bookNumber: 560,
    chapterNumber: 1,
    verseCount: 23,
  },
  {
    bookNumber: 560,
    chapterNumber: 2,
    verseCount: 22,
  },
  {
    bookNumber: 560,
    chapterNumber: 3,
    verseCount: 21,
  },
  {
    bookNumber: 560,
    chapterNumber: 4,
    verseCount: 32,
  },
  {
    bookNumber: 560,
    chapterNumber: 5,
    verseCount: 33,
  },
  {
    bookNumber: 560,
    chapterNumber: 6,
    verseCount: 24,
  },
  {
    bookNumber: 570,
    chapterNumber: 1,
    verseCount: 30,
  },
  {
    bookNumber: 570,
    chapterNumber: 2,
    verseCount: 30,
  },
  {
    bookNumber: 570,
    chapterNumber: 3,
    verseCount: 21,
  },
  {
    bookNumber: 570,
    chapterNumber: 4,
    verseCount: 23,
  },
  {
    bookNumber: 580,
    chapterNumber: 1,
    verseCount: 29,
  },
  {
    bookNumber: 580,
    chapterNumber: 2,
    verseCount: 23,
  },
  {
    bookNumber: 580,
    chapterNumber: 3,
    verseCount: 25,
  },
  {
    bookNumber: 580,
    chapterNumber: 4,
    verseCount: 18,
  },
  {
    bookNumber: 590,
    chapterNumber: 1,
    verseCount: 10,
  },
  {
    bookNumber: 590,
    chapterNumber: 2,
    verseCount: 20,
  },
  {
    bookNumber: 590,
    chapterNumber: 3,
    verseCount: 13,
  },
  {
    bookNumber: 590,
    chapterNumber: 4,
    verseCount: 18,
  },
  {
    bookNumber: 590,
    chapterNumber: 5,
    verseCount: 28,
  },
  {
    bookNumber: 600,
    chapterNumber: 1,
    verseCount: 12,
  },
  {
    bookNumber: 600,
    chapterNumber: 2,
    verseCount: 17,
  },
  {
    bookNumber: 600,
    chapterNumber: 3,
    verseCount: 18,
  },
  {
    bookNumber: 610,
    chapterNumber: 1,
    verseCount: 20,
  },
  {
    bookNumber: 610,
    chapterNumber: 2,
    verseCount: 15,
  },
  {
    bookNumber: 610,
    chapterNumber: 3,
    verseCount: 16,
  },
  {
    bookNumber: 610,
    chapterNumber: 4,
    verseCount: 16,
  },
  {
    bookNumber: 610,
    chapterNumber: 5,
    verseCount: 25,
  },
  {
    bookNumber: 610,
    chapterNumber: 6,
    verseCount: 21,
  },
  {
    bookNumber: 620,
    chapterNumber: 1,
    verseCount: 18,
  },
  {
    bookNumber: 620,
    chapterNumber: 2,
    verseCount: 26,
  },
  {
    bookNumber: 620,
    chapterNumber: 3,
    verseCount: 17,
  },
  {
    bookNumber: 620,
    chapterNumber: 4,
    verseCount: 22,
  },
  {
    bookNumber: 630,
    chapterNumber: 1,
    verseCount: 16,
  },
  {
    bookNumber: 630,
    chapterNumber: 2,
    verseCount: 15,
  },
  {
    bookNumber: 630,
    chapterNumber: 3,
    verseCount: 15,
  },
  {
    bookNumber: 640,
    chapterNumber: 1,
    verseCount: 25,
  },
  {
    bookNumber: 650,
    chapterNumber: 1,
    verseCount: 14,
  },
  {
    bookNumber: 650,
    chapterNumber: 2,
    verseCount: 18,
  },
  {
    bookNumber: 650,
    chapterNumber: 3,
    verseCount: 19,
  },
  {
    bookNumber: 650,
    chapterNumber: 4,
    verseCount: 16,
  },
  {
    bookNumber: 650,
    chapterNumber: 5,
    verseCount: 14,
  },
  {
    bookNumber: 650,
    chapterNumber: 6,
    verseCount: 20,
  },
  {
    bookNumber: 650,
    chapterNumber: 7,
    verseCount: 28,
  },
  {
    bookNumber: 650,
    chapterNumber: 8,
    verseCount: 13,
  },
  {
    bookNumber: 650,
    chapterNumber: 9,
    verseCount: 28,
  },
  {
    bookNumber: 650,
    chapterNumber: 10,
    verseCount: 39,
  },
  {
    bookNumber: 650,
    chapterNumber: 11,
    verseCount: 40,
  },
  {
    bookNumber: 650,
    chapterNumber: 12,
    verseCount: 29,
  },
  {
    bookNumber: 650,
    chapterNumber: 13,
    verseCount: 25,
  },
  {
    bookNumber: 660,
    chapterNumber: 1,
    verseCount: 27,
  },
  {
    bookNumber: 660,
    chapterNumber: 2,
    verseCount: 26,
  },
  {
    bookNumber: 660,
    chapterNumber: 3,
    verseCount: 18,
  },
  {
    bookNumber: 660,
    chapterNumber: 4,
    verseCount: 17,
  },
  {
    bookNumber: 660,
    chapterNumber: 5,
    verseCount: 20,
  },
  {
    bookNumber: 670,
    chapterNumber: 1,
    verseCount: 25,
  },
  {
    bookNumber: 670,
    chapterNumber: 2,
    verseCount: 25,
  },
  {
    bookNumber: 670,
    chapterNumber: 3,
    verseCount: 22,
  },
  {
    bookNumber: 670,
    chapterNumber: 4,
    verseCount: 19,
  },
  {
    bookNumber: 670,
    chapterNumber: 5,
    verseCount: 14,
  },
  {
    bookNumber: 680,
    chapterNumber: 1,
    verseCount: 21,
  },
  {
    bookNumber: 680,
    chapterNumber: 2,
    verseCount: 22,
  },
  {
    bookNumber: 680,
    chapterNumber: 3,
    verseCount: 18,
  },
  {
    bookNumber: 690,
    chapterNumber: 1,
    verseCount: 10,
  },
  {
    bookNumber: 690,
    chapterNumber: 2,
    verseCount: 29,
  },
  {
    bookNumber: 690,
    chapterNumber: 3,
    verseCount: 24,
  },
  {
    bookNumber: 690,
    chapterNumber: 4,
    verseCount: 21,
  },
  {
    bookNumber: 690,
    chapterNumber: 5,
    verseCount: 21,
  },
  {
    bookNumber: 700,
    chapterNumber: 1,
    verseCount: 13,
  },
  {
    bookNumber: 710,
    chapterNumber: 1,
    verseCount: 15,
  },
  {
    bookNumber: 720,
    chapterNumber: 1,
    verseCount: 25,
  },
  {
    bookNumber: 730,
    chapterNumber: 1,
    verseCount: 20,
  },
  {
    bookNumber: 730,
    chapterNumber: 2,
    verseCount: 29,
  },
  {
    bookNumber: 730,
    chapterNumber: 3,
    verseCount: 22,
  },
  {
    bookNumber: 730,
    chapterNumber: 4,
    verseCount: 11,
  },
  {
    bookNumber: 730,
    chapterNumber: 5,
    verseCount: 14,
  },
  {
    bookNumber: 730,
    chapterNumber: 6,
    verseCount: 17,
  },
  {
    bookNumber: 730,
    chapterNumber: 7,
    verseCount: 17,
  },
  {
    bookNumber: 730,
    chapterNumber: 8,
    verseCount: 13,
  },
  {
    bookNumber: 730,
    chapterNumber: 9,
    verseCount: 21,
  },
  {
    bookNumber: 730,
    chapterNumber: 10,
    verseCount: 11,
  },
  {
    bookNumber: 730,
    chapterNumber: 11,
    verseCount: 19,
  },
  {
    bookNumber: 730,
    chapterNumber: 12,
    verseCount: 17,
  },
  {
    bookNumber: 730,
    chapterNumber: 13,
    verseCount: 18,
  },
  {
    bookNumber: 730,
    chapterNumber: 14,
    verseCount: 20,
  },
  {
    bookNumber: 730,
    chapterNumber: 15,
    verseCount: 8,
  },
  {
    bookNumber: 730,
    chapterNumber: 16,
    verseCount: 21,
  },
  {
    bookNumber: 730,
    chapterNumber: 17,
    verseCount: 18,
  },
  {
    bookNumber: 730,
    chapterNumber: 18,
    verseCount: 24,
  },
  {
    bookNumber: 730,
    chapterNumber: 19,
    verseCount: 21,
  },
  {
    bookNumber: 730,
    chapterNumber: 20,
    verseCount: 15,
  },
  {
    bookNumber: 730,
    chapterNumber: 21,
    verseCount: 27,
  },
  {
    bookNumber: 730,
    chapterNumber: 22,
    verseCount: 21,
  },
];

export const getBookDetail = (book: string | number): IDBBookNames => {
  const bookDetail = DB_BOOK_NAMES.find(
    (x) =>
      x.longName === book ||
      x.longName.includes(book + '') ||
      (book + '').includes(x.longName) ||
      x.bookNumber === +book
  );

  return (bookDetail || {}) as IDBBookNames;
};
