export default [
  {
    question: '¿Quién construyó el arca según las instrucciones de Dios?',
    options: ['Abraham', 'Moisés', 'Noé', 'David'],
    correct: 'Noé',
    reference: 'Génesis 6:13-22',
    explanation: '',
    difficulty: 'easy',
  },
  {
    question: '¿Cuántos días le tomó a Dios crear el mundo según el Génesis?',
    options: ['3 días', '5 días', '6 días', '7 días'],
    correct: '6 días',
    reference: 'Génesis 1',
    explanation: '',
    difficulty: 'easy',
  },
  {
    question: '¿Cuál fue el primer milagro de Jesús?',
    options: [
      'Multiplicar los panes',
      'Convertir agua en vino',
      'Caminar sobre el agua',
      'Sanar a un leproso',
    ],
    correct: 'Convertir agua en vino',
    reference: 'Juan 2:1-11',
    explanation: '',
    difficulty: 'medium',
  },
  {
    question: '¿Cuántos apóstoles eligió Jesús?',
    options: ['10', '11', '12', '13'],
    correct: '12',
    reference: 'Mateo 10:1-4',
    explanation: '',
    difficulty: 'easy',
  },
  {
    question: '¿Quién fue llevado al cielo en un carro de fuego?',
    options: ['Moisés', 'Elías', 'Isaías', 'Daniel'],
    correct: 'Elías',
    reference: '2 Reyes 2:11',
    explanation: '',
    difficulty: 'medium',
  },
  {
    question: '¿Quién fue el primer rey de Israel?',
    options: ['David', 'Saúl', 'Salomón', 'Samuel'],
    correct: 'Saúl',
    reference: '1 Samuel 10:1',
    explanation: '',
    difficulty: 'medium',
  },
  {
    question: '¿Quién construyó el arca según las instrucciones de Dios?',
    options: ['Abraham', 'Moisés', 'Noé', 'David'],
    correct: 'Noé',
    reference: 'Génesis 6:13-22',
    explanation: '',
    difficulty: 'easy',
  },
  {
    question: '¿Cuántos días le tomó a Dios crear el mundo según el Génesis?',
    options: ['3 días', '5 días', '6 días', '7 días'],
    correct: '6 días',
    reference: 'Génesis 1',
    explanation: '',
    difficulty: 'easy',
  },
  {
    question: '¿Qué construyeron los hombres en Babel?',
    options: ['Un templo', 'Una torre', 'Una ciudad', 'Un palacio'],
    correct: 'Una torre',
    reference: 'Génesis 11:1-9',
    explanation: '',
    difficulty: 'easy',
  },
  {
    question: '¿Cuántos años vivió Matusalén?',
    options: ['777 años', '969 años', '888 años', '950 años'],
    correct: '969 años',
    reference: 'Génesis 5:27',
    explanation: '',
    difficulty: 'medium',
  },
  {
    question: '¿Cuál fue la señal del pacto de Dios con Noé?',
    options: ['Una estrella', 'Un arcoíris', 'Una paloma', 'Una nube'],
    correct: 'Un arcoíris',
    reference: 'Génesis 9:13',
    explanation: '',
    difficulty: 'easy',
  },
  {
    question: '¿Cuál era el nombre original de Abraham?',
    options: ['Abram', 'Ibrahim', 'Abel', 'Abrahan'],
    correct: 'Abram',
    reference: 'Génesis 17:5',
    explanation: '',
    difficulty: 'medium',
  },
  {
    question: '¿Qué pidió Salomón a Dios cuando se convirtió en rey?',
    options: ['Riquezas', 'Sabiduría', 'Poder', 'Larga vida'],
    correct: 'Sabiduría',
    reference: '1 Reyes 3:9',
    explanation: '',
    difficulty: 'easy',
  },
  {
    question: '¿Cuántos años vagó el pueblo de Israel por el desierto?',
    options: ['20 años', '30 años', '40 años', '50 años'],
    correct: '40 años',
    reference: 'Números 14:33-34',
    explanation: '',
    difficulty: 'easy',
  },
  {
    question: '¿Qué instrumento tocaba David para calmar a Saúl?',
    options: ['Flauta', 'Arpa', 'Tambor', 'Trompeta'],
    correct: 'Arpa',
    reference: '1 Samuel 16:23',
    explanation: '',
    difficulty: 'medium',
  },
  {
    question: '¿Cuál fue la primera plaga de Egipto?',
    options: ['Ranas', 'Sangre', 'Moscas', 'Granizo'],
    correct: 'Sangre',
    reference: 'Éxodo 7:20',
    explanation: '',
    difficulty: 'easy',
  },
  {
    question: '¿Cuál fue el primer milagro de Jesús?',
    options: [
      'Multiplicar los panes',
      'Convertir agua en vino',
      'Caminar sobre el agua',
      'Sanar a un leproso',
    ],
    correct: 'Convertir agua en vino',
    reference: 'Juan 2:1-11',
    explanation: '',
    difficulty: 'easy',
  },
  {
    question: '¿Quién negó a Jesús tres veces?',
    options: ['Juan', 'Pedro', 'Santiago', 'Andrés'],
    correct: 'Pedro',
    reference: 'Mateo 26:69-75',
    explanation: '',
    difficulty: 'easy',
  },
  {
    question:
      '¿Cuántos panes y peces usó Jesús para alimentar a 5000 personas?',
    options: [
      '5 panes y 2 peces',
      '7 panes y 3 peces',
      '3 panes y 5 peces',
      '2 panes y 7 peces',
    ],
    correct: '5 panes y 2 peces',
    reference: 'Mateo 14:17',
    explanation: '',
    difficulty: 'easy',
  },
  {
    question: '¿Quién escribió más libros del Nuevo Testamento?',
    options: ['Juan', 'Pedro', 'Pablo', 'Lucas'],
    correct: 'Pablo',
    reference: '',
    explanation: '',
    difficulty: 'medium',
  },
  {
    question: '¿A qué ciudad iba Saulo cuando se encontró con Jesús?',
    options: ['Jerusalén', 'Damasco', 'Antioquía', 'Tarso'],
    correct: 'Damasco',
    reference: 'Hechos 9:3',
    explanation: '',
    difficulty: 'medium',
  },
  {
    question: '¿Qué representa la levadura en la parábola de la levadura?',
    options: ['El pecado', 'El Reino de Dios', 'La fe', 'La maldad'],
    correct: 'El Reino de Dios',
    reference: 'Mateo 13:33',
    explanation: '',
    difficulty: 'medium',
  },
  {
    question:
      'En la parábola del hijo pródigo, ¿qué hizo el padre cuando vio regresar a su hijo?',
    options: [
      'Lo ignoró',
      'Corrió a su encuentro',
      'Lo reprendió',
      'Lo rechazó',
    ],
    correct: 'Corrió a su encuentro',
    reference: 'Lucas 15:20',
    explanation: '',
    difficulty: 'easy',
  },
  {
    question: '¿Qué buscaba la mujer en la parábola de la moneda perdida?',
    options: ['Una dracma', 'Un denario', 'Un talento', 'Un siclo'],
    correct: 'Una dracma',
    reference: 'Lucas 15:8',
    explanation: '',
    difficulty: 'medium',
  },
  {
    question: '¿Qué profeta fue tragado por un gran pez?',
    options: ['Jonás', 'Oseas', 'Amós', 'Nahúm'],
    correct: 'Jonás',
    reference: 'Jonás 1:17',
    explanation: '',
    difficulty: 'easy',
  },
  {
    question: '¿Qué profeta vio un valle de huesos secos?',
    options: ['Isaías', 'Jeremías', 'Ezequiel', 'Daniel'],
    correct: 'Ezequiel',
    reference: 'Ezequiel 37',
    explanation: '',
    difficulty: 'medium',
  },
  {
    question: '¿Qué profeta fue llevado al cielo en un carro de fuego?',
    options: ['Eliseo', 'Elías', 'Samuel', 'Natán'],
    correct: 'Elías',
    reference: '2 Reyes 2:11',
    explanation: '',
    difficulty: 'easy',
  },
  {
    question: '¿Qué profeta permaneció en el foso de los leones?',
    options: ['Daniel', 'Ezequiel', 'Jeremías', 'Isaías'],
    correct: 'Daniel',
    reference: 'Daniel 6',
    explanation: '',
    difficulty: 'easy',
  },
  {
    question: '¿Quién fue la primera mujer según la Biblia?',
    options: ['Eva', 'Sara', 'María', 'Rebeca'],
    correct: 'Eva',
    reference: 'Génesis 3:20',
    explanation: '',
    difficulty: 'easy',
  },
  {
    question: '¿Qué mujer escondió a los espías israelitas en Jericó?',
    options: ['Rahab', 'Rut', 'Débora', 'Ester'],
    correct: 'Rahab',
    reference: 'Josué 2:1-7',
    explanation: '',
    difficulty: 'medium',
  },
  {
    question: '¿Quién fue la suegra de Rut?',
    options: ['Sara', 'Raquel', 'Noemí', 'Ana'],
    correct: 'Noemí',
    reference: 'Rut 1:1-5',
    explanation: '',
    difficulty: 'medium',
  },
  {
    question: '¿Cuál fue la ciudad principal de los israelitas?',
    options: ['Jersusalén', 'Roma', 'Babilonia', 'Vaticano'],
    correct: 'Jersusalén',
    reference: '',
    explanation: '',
    difficulty: 'easy',
  },
  {
    question:
      "¿Quién dijo 'Muera yo ahora, ya que he visto tu rostro, y sé que aún vives'?",
    options: ['Israel', 'Moisés', 'Josué', 'Pablo'],
    correct: 'Israel',
    reference: 'Génesis 46:30',
    explanation: '',
    difficulty: 'very_hard',
  },
  {
    question: '¿En qué versículo se registra que Jesús cantó?',
    options: ['Mateo 26:30', 'Mateo 24:25', 'Mateo 25:30', 'Mateo 27:25'],
    correct: 'Mateo 26:30',
    reference: '',
    explanation: '',
    difficulty: 'very_hard',
  },
  {
    question: '¿Qué capítulo es considerado el “Salón de la fama de la fe”?',
    options: ['Hebreos 11', 'Mateo 11', 'Juan 11', 'Hechos 11'],
    correct: 'Hebreos 11',
    reference: '',
    explanation: '',
    difficulty: 'easy',
  },
  {
    question: '¿A cuál animal Dios privó de inteligencia?',
    options: ['Avestruz', 'Hormiga', 'Pavoreal', 'Leviatán'],
    correct: 'Avestruz',
    reference: 'Job 39:13-17',
    explanation: '',
    difficulty: 'medium',
  },
  {
    question: "¿Quién es considerado en la Biblia 'El hombre más manso'?",
    options: ['Moisés', 'Pablo', 'Pedro', 'Caleb'],
    correct: 'Moisés',
    reference: 'Números 12:3',
    explanation: '',
    difficulty: 'easy',
  },
  {
    question: '¿Qué misionero evangelizó a los pieles rojas?',
    options: [
      'David Brainerd',
      'William Carey',
      'John Wesley',
      'George Whitefield',
    ],
    correct: 'David Brainerd',
    reference: '',
    explanation: '',
    difficulty: 'very_hard',
  },
  {
    question: '¿Que hombre tenía una larga y pesada cabellera?',
    options: ['Absalón', 'Sansón', 'Juan el Bautista', 'Roboam'],
    correct: 'Absalón',
    reference: '2 Samuel 14:25-26',
    explanation: '',
    difficulty: 'medium',
  },
  {
    question: '¿Que hombre no llevó duelo cuando murieron sus hijos?',
    options: ['Aarón', 'Adán', 'David', 'Nehemías'],
    correct: 'Aarón',
    reference: 'Levítico 10',
    explanation: '',
    difficulty: 'hard',
  },
  {
    question: '¿Cuál era el nombre original de Josué?',
    options: ['Oseas', 'Nunca cambió su nombre', 'Caleb', 'Jozías'],
    correct: 'Oseas',
    reference: 'Números 13:16',
    explanation: '',
    difficulty: 'medium',
  },
  {
    question: '¿Quién dio el sermón más largo de la Biblia?',
    options: ['Pablo', 'Jesús', 'Pedro', 'Moisés'],
    correct: 'Pablo',
    reference: 'Hechos 20:7-11',
    explanation: '',
    difficulty: 'medium',
  },
  {
    question:
      "¿Quién dijo 'Señor, no tienes con qué sacarla, y el pozo es hondo. ¿de dónde, pues, tienes el agua viva?'?",
    options: [
      'Mujer samaritana',
      'Viuda de Sarepta',
      'Mujer adultera',
      'María Magdalena',
    ],
    correct: 'Mujer samaritana',
    reference: 'Juan 4:11',
    explanation: '',
    difficulty: 'medium',
  },
  {
    question: '¿En qué libro de la Biblia se menciona a más animales?',
    options: ['Levítico 11', 'Génesis 7', 'Levítico 9', 'Proverbios 5'],
    correct: 'Levítico 11',
    reference: '',
    explanation: '',
    difficulty: 'very_hard',
  },
  {
    question: '¿Cuántos versículos tiene el Salmo 117?',
    options: ['2', '176', '174', '4'],
    correct: '2',
    reference: '',
    explanation: '',
    difficulty: 'hard',
  },
  {
    question:
      'Jesús fue crucificado entre dos personas, estás dos personas ¿quiénes fueron?',
    options: ['Ladrones', 'Rebeldes', 'Recaudadores', 'Traidores'],
    correct: 'Ladrones',
    reference: 'Marcos 15:27',
    explanation: '',
    difficulty: 'easy',
  },
  {
    question:
      "¿Quién dijo '¿Quién es Jehová, para que yo oiga su voz y deje ir a Israel? Yo no conozco a Jehová, ni tampoco dejaré ir a Israel'?",
    options: ['Faraón', 'Moisés', 'Nabucodonosor', 'Pablo'],
    correct: 'Faraón',
    reference: 'Éxodo 5:2',
    explanation: '',
    difficulty: 'easy',
  },
  {
    question: '¿Quién de los siguientes NO fue discípulo de Jesús?',
    options: ['Marcos', 'Santiago', 'Mateo', 'Bartolomé'],
    correct: 'Marcos',
    reference: 'Mateo 10:2-4',
    explanation: '',
    difficulty: 'very_hard',
  },
  {
    question: "¿Quién dijo 'Por voluntad de Jehová he adquirido varón'?",
    options: ['Eva', 'Sara', 'Raquel', 'Ana'],
    correct: 'Eva',
    reference: 'Génesis 4:1',
    explanation: '',
    difficulty: 'hard',
  },
  {
    question:
      "¿A quién se refieren las siguientes pistas: 'carne, sueño, mujer, huesos, costilla'?",
    options: ['Adán', 'Goliat', 'David', 'José'],
    correct: 'Adán',
    reference: 'Génesis 2',
    explanation: '',
    difficulty: 'easy',
  },
  {
    question:
      "¿Quién dijo 'Mi corazón se regocija en Jehová, Mi poder se exalta en Jehová; Mi boca se ensanchó sobre mis enemigos, Por cuanto me alegré en tu salvación'?",
    options: ['Ana', 'David', 'Jeremías', 'Josué'],
    correct: 'Ana',
    reference: '1 Samuel 2:1',
    explanation: '',
    difficulty: 'very_hard',
  },
  {
    question:
      '¿Cuántos años habitaron los israelitas en Egipto antes de ser libertados?',
    options: ['430 años', '400 años', '410 años', '100 años'],
    correct: '430 años',
    reference: 'Éxodo 12:40',
    explanation: '',
    difficulty: 'medium',
  },
  {
    question:
      'Moisés e Israel llegaron a un lugar llamado Elim, ¿cuántas palmeras y cuantas fuentes había en ese lugar?',
    options: [
      '12 fuentes y 70 palmeras',
      '70 fuentes y 12 palmeras',
      '12 fuentes y 12 palmeras',
      '7 fuentes y 70 palmeras',
    ],
    correct: '12 fuentes y 70 palmeras',
    reference: 'Éxodo 15:27',
    explanation: '',
    difficulty: 'very_hard',
  },
  {
    question:
      '¿Cuánto tiempo dio Nabucodonosor a Daniel para que aprendiera la lengua y escritura de los caldeos?',
    options: ['3 años', '3 meses', '1 año', '6 meses'],
    correct: '3 años',
    reference: 'Daniel 1:5',
    explanation: '',
    difficulty: 'hard',
  },
  {
    question:
      '¿Cuántas vueltas dio a Jericó el ejercito de Josué antes del asalto a la ciudad?',
    options: ['13 vueltas', '7 vueltas', '14 vueltas', '12 vueltas'],
    correct: '13 vueltas',
    reference: 'Josué 6:3-4',
    explanation: '',
    difficulty: 'medium',
  },
  {
    question: 'Y le dieron nombre las vecinas, y lo llamaron...',
    options: ['Obed', 'Oseas', 'Eliú', 'Jefté'],
    correct: 'Obed',
    reference: 'Rut 4:17',
    explanation: '',
    difficulty: 'hard',
  },
  {
    question:
      '¿Nombre del personaje al que su asna aplastó su pie contra la pared?',
    options: ['Balaam', 'Balaac', 'Baal', 'Jonás'],
    correct: 'Balaam',
    reference: 'Números 22:25',
    explanation: '',
    difficulty: 'medium',
  },
  {
    question:
      '¿En casa de quién se alojaron los espías que Josué envió a Jericó?',
    options: ['Rahab', 'María', 'Salomé', 'Racab'],
    correct: 'Rahab',
    reference: 'Josué 2:1',
    explanation: '',
    difficulty: 'medium',
  },
  {
    question: '¿Con cuántos hombres venció Gedeón a los medianitas?',
    options: ['300 hombres', '350 hombres', '200 hombres', '600 hombres'],
    correct: '300 hombres',
    reference: 'Jueces 7',
    explanation: '',
    difficulty: 'medium',
  },
  {
    question: '¿Cómo se llamaban las dos nueras de Noemí?',
    options: ['Rut y Orfa', 'Rut y Ester', 'Rut y Rebeca', 'Rut y Lea'],
    correct: 'Rut y Orfa',
    reference: 'Rut 1:4',
    explanation: '',
    difficulty: 'easy',
  },
  {
    question: 'Según la Biblia, ¿cuál es la raíz de todos los males?',
    options: [
      'El amor al dinero',
      'La desobediencia',
      'Un corazón perverso',
      'La poca fe',
    ],
    correct: 'El amor al dinero',
    reference: '1 Timoteo 6:10',
    explanation: '',
    difficulty: 'hard',
  },
  {
    question: '¿En qué monte murió Saúl con sus tres hijos?',
    options: ['Gilboa', 'Hebrón', 'Moriah', 'Tabor'],
    correct: 'Gilboa',
    reference: '1 Samuel 31',
    explanation: '',
    difficulty: 'very_hard',
  },
  {
    question: '¿En qué monte murió Moisés?',
    options: ['Nebo', 'Sinaí', 'Horeb', 'Tabor'],
    correct: 'Nebo',
    reference: 'Deuteronomio 34',
    explanation: '',
    difficulty: 'very_hard',
  },
  {
    question: '¿Por cuántos días ayunó Moisés?',
    options: ['40 días', 'Nunca ayunó', '7 días', '12 días'],
    correct: '40 días',
    reference: 'Éxodo 34:28',
    explanation: '',
    difficulty: 'hard',
  },
  {
    question: '¿Cómo se llamaba el esposo de Jezabel?',
    options: ['Acab', 'Acaz', 'Ocozías', 'Urías'],
    correct: 'Acab',
    reference: '1 Reyes 16:29-31',
    explanation: '',
    difficulty: 'medium',
  },
  {
    question: '¿Qué sígnica el lugar llamado Gólgota?',
    options: [
      'Lugar de la calavera',
      'Lugar de tristezas',
      'Lugar de llanto',
      'Lugar de muerte',
    ],
    correct: 'Lugar de la calavera',
    reference: 'Marcos 15:22',
    explanation: '',
    difficulty: 'hard',
  },
  {
    question: '¿Cuál es el título de Apocalipsis 21:1?',
    options: [
      'Cielo nuevo y tierra nueva',
      'Los mil años',
      'La nueva Jerusalén',
      'Las bodas del cordero',
    ],
    correct: 'Cielo nuevo y tierra nueva',
    reference: '',
    explanation: '',
    difficulty: 'medium',
  },
  {
    question:
      '¿En que libro de la Biblia se narra la historia de José y sus hermanos?',
    options: ['Génesis', 'Éxodo', 'Levítico', 'Deuteronomio'],
    correct: 'Génesis',
    reference: 'Génesis 37-50',
    explanation: '',
    difficulty: 'easy',
  },
  {
    question: '¿Cuál era la nacionalidad de Rut?',
    options: ['Moabita', 'Israelita', 'Edomita', 'Filistea'],
    correct: 'Moabita',
    reference: 'Rut 1:4',
    explanation: '',
    difficulty: 'easy',
  },
  {
    question: '¿Quién fue el padre de Abel?',
    options: ['Adán', 'Moisés', 'Caín', 'Abraham'],
    correct: 'Adán',
    reference: 'Génesis 4:1-2',
    explanation: '',
    difficulty: 'easy',
  },
  {
    question: '¿Cómo se llamaba la mujer que se dice tenía “ojos delicados”?',
    options: ['Lea', 'Rebeca', 'Raquel', 'Ester'],
    correct: 'Lea',
    reference: 'Génesis 29:17',
    explanation: '',
    difficulty: 'easy',
  },
  {
    question: '¿Cómo se llamaba el esposo de Débora?',
    options: ['Lapidot', 'Nun', 'Jefté', 'Otoniel'],
    correct: 'Lapidot',
    reference: 'Jueces 4:4',
    explanation: '',
    difficulty: 'medium',
  },
  {
    question: '¿Qué oficio tenía Jesús?',
    options: ['Carpintero', 'Herrero', 'Guerrero', 'Soldado'],
    correct: 'Carpintero',
    reference: 'Mateo 13:55 y Marcos 6:3',
    explanation: '',
    difficulty: 'easy',
  },
  {
    question:
      'Un barco enorme construí, por mandato divino, mis vecinos se burlaron de mí, pero lloraron cuando la lluvia vino',
    options: ['Noé', 'Caín', 'Jesús', 'Aarón'],
    correct: 'Noé',
    reference: 'Génesis 6',
    explanation: '',
    difficulty: 'easy',
  },
  {
    question:
      'Rubio era mi semblante, fui un experto cazador, por culpa de un guisado, perdí mis derechos de hijo mayor',
    options: ['Esaú', 'Jacob', 'David', 'Saúl'],
    correct: 'Esaú',
    reference: 'Génesis 25',
    explanation: '',
    difficulty: 'medium',
  },
  {
    question:
      'De gran estatura fui el terror de Israel, ¿quién podría imaginar que con una honda me podrían vencer?',
    options: ['Goliat', 'Sansón', 'Absalón', 'Faraón'],
    correct: 'Goliat',
    reference: '1 Samuel 17',
    explanation: '',
    difficulty: 'easy',
  },
  {
    question:
      '¿Cuál de los siguientes colores NO eran parte de las cortinas del Tabernáculo?',
    options: ['Bermejo', 'Azul', 'Púrpura', 'Carmesí'],
    correct: 'Bermejo',
    reference: 'Éxodo 26:1',
    explanation: '',
    difficulty: 'hard',
  },
  {
    question: '¿De qué color era la túnica de José?',
    options: [
      'Muchos colores',
      'Roja y amarilla',
      'Blanca y roja',
      'Púrpura y blanca',
    ],
    correct: 'Muchos colores',
    reference: 'Génesis 37:3',
    explanation: '',
    difficulty: 'easy',
  },
  {
    question: '¿Qué oficio tenía Nehemías?',
    options: ['Copero', 'Mensajero', 'Consejero', 'Cocinero'],
    correct: 'Copero',
    reference: 'Nehemías 1:11',
    explanation: '',
    difficulty: 'medium',
  },
  {
    question: '¿De qué nacionalidad era Moisés?',
    options: ['Hebreo', 'Filisteo', 'Egipcio', 'Moabita'],
    correct: 'Hebreo',
    reference: '',
    explanation: '',
    difficulty: 'medium',
  },
  {
    question:
      '¿Qué edad tenía Moisés cuando fue descubierto por la hija de Faraón?',
    options: ['3 meses', '7 días', '8 días', '1 mes'],
    correct: '3 meses',
    reference: 'Éxodo 2',
    explanation: '',
    difficulty: 'medium',
  },
  {
    question:
      '¿Cómo se llamaba el pan que caía del cielo y alimentaba a los israelitas en el desierto?',
    options: ['Maná', 'Manac', 'Francés', 'Bimbo'],
    correct: 'Maná',
    reference: 'Éxodo 16',
    explanation: '',
    difficulty: 'easy',
  },
  {
    question: '¿Cómo se llamaba el esposo de María madre de Jesús?',
    options: ['José', 'Juan', 'Lázaro', 'Abraham'],
    correct: 'José',
    reference: 'Mateo 1:16',
    explanation: '',
    difficulty: 'easy',
  },
  {
    question:
      '¿Dónde fue prendido y arrestado Jesús cuando se encontraba orando?',
    options: [
      'Huerto de Getsemaní',
      'Monte de los Olivos',
      'Gólgota',
      'En el templo',
    ],
    correct: 'Huerto de Getsemaní',
    reference: 'Mateo 26, Marcos 14, Lucas 22',
    explanation: '',
    difficulty: 'easy',
  },
  {
    question:
      '¿Quién propuso a su mujer hacerse pasar por su hermana en Egipto, para preservar su vida?',
    options: ['Abraham', 'Enoc', 'Moisés', 'Sem'],
    correct: 'Abraham',
    reference: 'Génesis 12:10-13',
    explanation: '',
    difficulty: 'easy',
  },
  {
    question: '¿Quién fue el segundo rey de Israel?',
    options: ['David', 'Jonatán', 'Saúl', 'Josué'],
    correct: 'David',
    reference: '',
    explanation: '',
    difficulty: 'easy',
  },
  {
    question:
      "¿Quién condujo a los israelitas a conquistar la 'Tierra Prometida'?",
    options: ['Josué', 'Moisés', 'Caleb', 'Coré'],
    correct: 'Josué',
    reference: '',
    explanation: '',
    difficulty: 'easy',
  },
  {
    question:
      'Fue desterrado a la isla de Patmos, donde escribió el libro de Apocalipsis:',
    options: ['Juan', 'Pablo', 'Bernabé', 'Marcos'],
    correct: 'Juan',
    reference: 'Apocalipsis 1:9',
    explanation: '',
    difficulty: 'easy',
  },
  {
    question: '¿Dónde dijo Jehová que la serpiente heriría a la mujer?',
    options: ['En el calcañar', 'En su orgullo', 'En la cara', 'En la pierna'],
    correct: 'En el calcañar',
    reference: 'Génesis 3:15',
    explanation: '',
    difficulty: 'easy',
  },
  {
    question: '¿Quién pasó una noche encerrado en un foso de leones?',
    options: ['Daniel', 'Jeremías', 'Pedro', 'Pablo'],
    correct: 'Daniel',
    reference: 'Daniel 6',
    explanation: '',
    difficulty: 'easy',
  },
  {
    question: '¿En quién se originó el pecado?',
    options: ['Lucifer', 'Eva', 'Adán', 'Caín'],
    correct: 'Lucifer',
    reference: 'Isaías 14',
    explanation: '',
    difficulty: 'medium',
  },
  {
    question:
      "¿A qué ciudad se refirió Jesús cuando dijo 'No hay profeta sin honra, sino en su propia tierra y en su casa'?",
    options: ['Nazaret', 'Jerusalén', 'Galilea', 'Belén'],
    correct: 'Nazaret',
    reference: 'Mateo 13:53-58',
    explanation: '',
    difficulty: 'hard',
  },
  {
    question: '¿Qué libro se encuentra entre Amós y Jonás?',
    options: ['Abdías', 'Ninguno', 'Habacuc', 'Joel'],
    correct: 'Abdías',
    reference: '',
    explanation: '',
    difficulty: 'hard',
  },
  {
    question: '¿Cuántas tinajas de agua convirtió Jesús en vino?',
    options: ['Seis', 'Diez', 'Tres', 'Cuatro'],
    correct: 'Seis',
    reference: 'Juan 2:6',
    explanation: '',
    difficulty: 'hard',
  },
  {
    question: '¿Quién escribió el libro de Proverbios?',
    options: ['Varios autores', 'David', 'Moisés', 'Salomón'],
    correct: 'Varios autores',
    reference: '',
    explanation: '',
    difficulty: 'very_hard',
  },
  {
    question: '¿Quién fue profeta durante el reinado de Darío?',
    options: ['Daniel', 'Zacarías', 'Hageo', 'Jeremías'],
    correct: 'Daniel',
    reference: '',
    explanation: '',
    difficulty: 'hard',
  },
  {
    question: '¿Qué significa Bet-el?',
    options: [
      'Casa de Dios',
      'Escalera de Dios',
      'Dios es mi roca',
      'Sueño de Dios',
    ],
    correct: 'Casa de Dios',
    reference: 'Génesis 12:8',
    explanation: '',
    difficulty: 'very_hard',
  },
  {
    question: '¿Cuántos capítulos tiene el libro de Judas?',
    options: ['Uno', 'Dos', 'Tres', 'Cinco'],
    correct: 'Uno',
    reference: '',
    explanation: '',
    difficulty: 'easy',
  },
  {
    question: '¿Qué padre e hijo fueron circuncidados el mismo día?',
    options: [
      'Abraham e Ismael',
      'Isaac y Jacob',
      'Abraham e Isaac',
      'Moisés y Gersón',
    ],
    correct: 'Abraham e Ismael',
    reference: 'Génesis 17:26',
    explanation: '',
    difficulty: 'very_hard',
  },
  {
    question: '¿Cuánto tiempo anduvo Isaías desnudo y descalzo?',
    options: ['Tres años', 'Tres días', 'Tres meses', 'Nunca hizo eso'],
    correct: 'Tres años',
    reference: 'Isaías 20:3',
    explanation: '',
    difficulty: 'very_hard',
  },
  {
    question:
      '¿En qué libro de la Biblia cuenta que el arcángel Miguel y el diablo disputaban por el cuerpo de Moisés?',
    options: ['Judas', 'Deuteronomio', 'Zacarías', 'Apocalipsis'],
    correct: 'Judas',
    reference: 'Judas 1:9',
    explanation: '',
    difficulty: 'hard',
  },
  {
    question:
      '¿A qué tribu de Israel pertenecía el rey Saúl y el apostol Pablo?,',
    options: ['Benjamín', 'Judá', 'Efraín', 'Otra'],
    correct: 'Benjamín',
    reference: '1 Samuel 9:1-2',
    explanation: '',
    difficulty: 'hard',
  },
  {
    question: '¿Cuántos de los jueces de Israel fueron mujeres?',
    options: ['Una', 'Dos', 'Ninguna', 'Tres'],
    correct: 'Una',
    reference: 'Jueces 4',
    explanation: '',
    difficulty: 'medium',
  },
  {
    question:
      'En el N.T. aparecía una mujer llamada Lidia ¿qué vendía esta mujer?,',
    options: ['Púrpura', 'Templos de Diana', 'Ungüentos', 'Tiendas'],
    correct: 'Púrpura',
    reference: 'Hechos 16:14',
    explanation: '',
    difficulty: 'medium',
  },
  {
    question:
      '¿Cuál es el evangelio que NO registra ninguna predicción de Jesús acerca de su resurreción?',
    options: ['Juan', 'Mateo', 'Marcos', 'Lucas'],
    correct: 'Juan',
    reference: '',
    explanation: '',
    difficulty: 'very_hard',
  },
  {
    question: '¿Quién vió a unos ángeles subir y bajar por una escalera?',
    options: ['Jacob', 'Isaac', 'Isaías', 'Jeremías'],
    correct: 'Jacob',
    reference: 'Génesis 28:10-12',
    explanation: '',
    difficulty: 'medium',
  },
  {
    question: '¿Cuál es el capítulo más largo de la Biblia?',
    options: ['Salmos 119', 'Apocalipsis 22', 'Job 42', 'Mateo 24'],
    correct: 'Salmos 119',
    reference: '176 versículos',
    explanation: '',
    difficulty: 'medium',
  },
  {
    question: '¿Cuál de los siguientes hombres fueron hijos de Raquel?',
    options: [
      'Benjamín y José',
      'Esaú y Jacob',
      'Isaac e Ismael',
      'Rubén y Judá',
    ],
    correct: 'Benjamín y José',
    reference: 'Génesis 35:24',
    explanation: '',
    difficulty: 'medium',
  },
  {
    question:
      '¿Cuántas veces pasó el pueblo de Israel por aguas que se abrieron?,',
    options: ['Dos veces', 'Una vez', 'Tres veces', 'Siete veces'],
    correct: 'Dos veces',
    reference: 'Éxodo 14 y Josué 3',
    explanation: '',
    difficulty: 'medium',
  },
  {
    question:
      "¿Qué parábola relató Jesús para responder a la pregunta '¿Quién es mi prójimo?'?",
    options: [
      'El buen samaritano',
      'El hijo pródigo',
      'La oveja perdida',
      'El fariseo y el publicano',
    ],
    correct: 'El buen samaritano',
    reference: 'Lucas 10:25-37',
    explanation: '',
    difficulty: 'medium',
  },
  {
    question:
      "¿Quién dijo 'No temáis; estad firmes, y ved la salvación que Jehová hará hoy con vosotros'?",
    options: ['Moisés', 'Josué', 'Gedeón', 'David'],
    correct: 'Moisés',
    reference: 'Éxodo 14:13',
    explanation: '',
    difficulty: 'very_hard',
  },
  {
    question: '¿Cómo se llamaba la esposa de Moisés?',
    options: ['Séfora', 'Sara', 'Rebeca', 'Lea'],
    correct: 'Séfora',
    reference: 'Éxodo 2:21',
    explanation: '',
    difficulty: 'easy',
  },
  {
    question: '¿Quién cerró la puerta del arca que construyó Noé?',
    options: ['Jehová', 'Noé', 'Cam', 'Jafet'],
    correct: 'Jehová',
    reference: 'Génesis 7:16',
    explanation: '',
    difficulty: 'easy',
  },
  {
    question: '¿Dónde estaba situado el Monte Moriah?',
    options: ['Jerusalén', 'Jericó', 'Sinaí', 'Cerca de Ur'],
    correct: 'Jerusalén',
    reference: '2 Crónicas 3:1',
    explanation: '',
    difficulty: 'very_hard',
  },
  {
    question: '¿Quién escribió el libro de Lamentaciones?',
    options: ['Jeremías', 'Isaías', 'Salomón', 'David'],
    correct: 'Jeremías',
    reference: '',
    explanation: '',
    difficulty: 'medium',
  },
  {
    question: '¿A qué rey se le añadieron 15 años de vida?',
    options: ['Ezequías', 'Josías', 'Ocozías', 'Ezequiel'],
    correct: 'Ezequías',
    reference: 'Isaías 38:5',
    explanation: '',
    difficulty: 'medium',
  },
  {
    question: '¿A quién pertenecía el manto al que David cortó una orilla?',
    options: ['Saúl', 'Samuel', 'Jonatán', 'Urías'],
    correct: 'Saúl',
    reference: '1 Samuel 24:4',
    explanation: '',
    difficulty: 'medium',
  },
  {
    question: '¿Quién predicó en el día de Pentecostés?',
    options: ['Pedro', 'Jesús', 'Pablo', 'Felipe'],
    correct: 'Pedro',
    reference: 'Hechos 2',
    explanation: '',
    difficulty: 'medium',
  },
  {
    question: '¿Quién pidió a Dios una señal dos veces?',
    options: ['Gedeón', 'Daniel', 'Otro', 'Abraham'],
    correct: 'Gedeón',
    reference: 'Jueces 6',
    explanation: '',
    difficulty: 'hard',
  },
  {
    question: '¿Cómo se llamaba el padre de Samuel?',
    options: ['Elcana', 'Jared', 'Jeroham', 'Finees'],
    correct: 'Elcana',
    reference: '1 Samuel 1',
    explanation: '',
    difficulty: 'very_hard',
  },
  {
    question:
      '¿Cuántas personas (además de Jesús) estuvieron presentes en la Transfiguración?',
    options: ['Tres', 'Dos', 'Cuatro', 'Uno'],
    correct: 'Tres',
    reference: 'Mateo 17:1, Marcos 9:2, Lucas 9:28',
    explanation: '',
    difficulty: 'very_hard',
  },
  {
    question:
      "¿En qué libro se encuentra la siguiente frase 'y me buscaréis y me hallaréis, porque me buscaréis de todo vuestro corazón'?",
    options: ['Jeremías', 'Isaías', 'Salmos', 'Deuteronomio'],
    correct: 'Jeremías',
    reference: 'Jeremías 29:13',
    explanation: '',
    difficulty: 'very_hard',
  },
  {
    question: '¿Cuál es la primera mentira que se registra en la Biblia?',
    options: ['No moriréis', 'No te conozco', 'Soy tu hijo', 'No sé'],
    correct: 'No moriréis',
    reference: 'Génesis 3:4',
    explanation: '',
    difficulty: 'medium',
  },
  {
    question: '¿Por qué murió Uza?',
    options: [
      'Por tocar el arca',
      'Por blasfemar',
      'Por robar del anatema',
      'Por adulterio',
    ],
    correct: 'Por tocar el arca',
    reference: '2 Samuel 6:6-7',
    explanation: '',
    difficulty: 'hard',
  },
  {
    question: "¿Quién fue llamado el 'Tisbita'?",
    options: ['Elías', 'Simón', 'Eliseo', 'Jeremías'],
    correct: 'Elías',
    reference: '1 Reyes 17:1',
    explanation: '',
    difficulty: 'very_hard',
  },
  {
    question: '¿Cuántos capítulos tiene el libro de Rut?',
    options: ['Cuatro', 'Seis', 'Tres', 'Cinco'],
    correct: 'Cuatro',
    reference: '',
    explanation: '',
    difficulty: 'hard',
  },
  {
    question: '¿Cuál es el nombre del río en el cual fue bautizado Jesús?',
    options: ['Jordán', 'Nilo', 'Éufrates', 'Tigris'],
    correct: 'Jordán',
    reference: 'Mateo 3:13',
    explanation: '',
    difficulty: 'easy',
  },
  {
    question:
      '¿En qué libro de la Biblia el pueblo de Israel adora a un becerro de oro hecho por Aarón?',
    options: ['Éxodo', 'Levítico', 'Números', 'Deuteronomio'],
    correct: 'Éxodo',
    reference: 'Éxodo 31:18-32:35',
    explanation: '',
    difficulty: 'easy',
  },
  {
    question: '¿Cuál de las siguientes personas NO conocieron la muerte?',
    options: [
      'Enoc y Elías',
      'Elías y Moisés',
      'Sansón y Moisés',
      'Matusalén y Samuel',
    ],
    correct: 'Enoc y Elías',
    reference: 'Génesis 5:22 y 2 Reyes 2:11',
    explanation: '',
    difficulty: 'easy',
  },
  {
    question: '¿Qué instrumento musical tocaba David delante de Saúl?',
    options: ['Arpa', 'Címbalo', 'Cítara', 'Trompeta'],
    correct: 'Arpa',
    reference: '1 Samuel 16:23',
    explanation: '',
    difficulty: 'easy',
  },
  {
    question: '¿Cuántos hijos tuvo Isaac?',
    options: ['Dos', 'Doce', 'Uno', 'Ninguno'],
    correct: 'Dos',
    reference: 'Génesis 25:19-26',
    explanation: '',
    difficulty: 'easy',
  },
  {
    question:
      "¿En qué libro aparece la cita: 'Dios es nuestro amparo y fortaleza, nuestro pronto auxilio en las tribulaciones'?",
    options: ['Salmos', 'Proverbios', 'Cantares', 'Eclesiastés'],
    correct: 'Salmos',
    reference: 'Salmos 46:1',
    explanation: '',
    difficulty: 'medium',
  },
  {
    question:
      'Según el evangelio de Lucas ¿qué tenía Jesús por costumbre los sábados?',
    options: ['Ir a la Sinangoga', 'Descansar', 'Sanar enfermos', 'Predicar'],
    correct: 'Ir a la Sinangoga',
    reference: 'Lucas 4:16',
    explanation: '',
    difficulty: 'medium',
  },
  {
    question: '¿Cuántos hijos e hijas tuvo Job?',
    options: ['Veinte', 'Siete', 'Doce', 'Diez'],
    correct: 'Veinte',
    reference: 'Job 1:2 más Job 42:13',
    explanation: '',
    difficulty: 'very_hard',
  },
  {
    question: 'Bienaventurados los pobres en espíritu, porque...',
    options: [
      'De ellos es el reino de los cielos',
      'Ellos verán a Dios',
      'Ellos serán saciados',
      'Ellos serán consolados',
    ],
    correct: 'De ellos es el reino de los cielos',
    reference: 'Mateo 5:3',
    explanation: '',
    difficulty: 'medium',
  },
  {
    question: '¿Con qué se comparará la ley de Dios?',
    options: [
      'Con un espejo',
      'Con una espada',
      'Con una fruta',
      'Con el agua',
    ],
    correct: 'Con un espejo',
    reference: 'Santiago 1:23, 2 Corintios 3:18',
    explanation: '',
    difficulty: 'medium',
  },
  {
    question: '¿Cuál es nombre del nieto de Adán, hijo de Set?',
    options: ['Enós', 'Enoc', 'Lamec', 'Matusael'],
    correct: 'Enós',
    reference: 'Génesis 4:26',
    explanation: '',
    difficulty: 'hard',
  },
  {
    question:
      'Según el evangelio de Marcos, Jesús sanó a la suegra de uno de sus discipulos ¿de quién?',
    options: ['Simón', 'Juan', 'Jacobo', 'Andrés'],
    correct: 'Simón',
    reference: 'Marcos 1:29-30',
    explanation: '',
    difficulty: 'hard',
  },
  {
    question:
      '¿A dónde se dirigían los discipulos cuando Jesús se les apareció después de resucitar?',
    options: ['Galilea', 'Betania', 'Jersusalén', 'Samaria'],
    correct: 'Galilea',
    reference: '',
    explanation: '',
    difficulty: 'hard',
  },
  {
    question: 'Antes de ser rey David era...',
    options: ['Pastor', 'Agricultor', 'Guerrero', 'Futbolista'],
    correct: 'Pastor',
    reference: '1 Samuel 17:34',
    explanation: '',
    difficulty: 'easy',
  },
  {
    question: '¿A quién ofreció Pilato liberar en lugar de Jesús?',
    options: ['Barrabás', 'Dos ladrones', 'Juan el Bautista', 'Pedro'],
    correct: 'Barrabás',
    reference: 'Mateo 27:15-21',
    explanation: '',
    difficulty: 'easy',
  },
  {
    question:
      '¿Cuántas piedras lisas cogió David del arroyo en su enfrentamiento con Goliat?',
    options: ['Cinco', 'Una', 'Tres', 'Siete'],
    correct: 'Cinco',
    reference: '1 Samuel 17:40',
    explanation: '',
    difficulty: 'medium',
  },
  {
    question: '¿Quién fue Eliseo?',
    options: ['Un profeta', 'Un arquitecto', 'Un apostol', 'Un fariseo'],
    correct: 'Un profeta',
    reference: '1 Reyes 19:16',
    explanation: '',
    difficulty: 'easy',
  },
  {
    question:
      "Jesús dijo 'cuando veáis en el lugar santo la abominación desoladora de que habló el profeta Daniel entonces los que estén en Judea...'",
    options: [
      'Huyan a los montes',
      'Huyan a los campos',
      'Clamen al Padre',
      'Arrepiéntanse',
    ],
    correct: 'Huyan a los montes',
    reference: 'Mateo 24:14-16',
    explanation: '',
    difficulty: 'hard',
  },
  {
    question:
      "'El hombre que tiene amigos ha de mostrarse amigo; y amigo hay más unido que...'",
    options: ['Un hermano', 'Una esposa', 'Un rey', 'Un padre'],
    correct: 'Un hermano',
    reference: 'Proverbios 18:24',
    explanation: '',
    difficulty: 'medium',
  },
  {
    question: "¿Quién dijo 'Nunca os conocí'?",
    options: ['Jesús', 'Juan el Bautista', 'Pedro', 'Pablo'],
    correct: 'Jesús',
    reference: 'Mateo 7:21-23',
    explanation: '',
    difficulty: 'medium',
  },
  {
    question: '¿Qué tenía Nabot que fue codiciado por un rey?',
    options: ['Una viña', 'Una casa', 'Una mujer', 'Una hija'],
    correct: 'Una viña',
    reference: '1 Reyes 21',
    explanation: '',
    difficulty: 'medium',
  },
  {
    question: '¿Con qué otro nombre se le conoce al discipulo Leví de Alfeo?',
    options: ['Mateo', 'Marcos', 'Juan', 'Lucas'],
    correct: 'Mateo',
    reference: 'Marcos 2:14 y Mateo 10:3',
    explanation: '',
    difficulty: 'hard',
  },
  {
    question: '¿En qué día de la creación separó Dios la luz de las tinieblas?',
    options: ['Primero', 'Segundo', 'Tercero', 'Cuarto'],
    correct: 'Primero',
    reference: 'Génesis 1:4',
    explanation: '',
    difficulty: 'easy',
  },
  {
    question: '¿Qué recibirán aquellos quienes sean fieles hasta la muerte?',
    options: [
      'Corona de vida',
      'Vida eterna',
      'El fruto de la vida',
      'Moradas',
    ],
    correct: 'Corona de vida',
    reference: 'Apocalipsis 2:10',
    explanation: '',
    difficulty: 'hard',
  },
  {
    question: '¿De qué ciudad escapó Pablo en un canasto?',
    options: ['Damasco', 'Éfeso', 'Corintios', 'Filipo'],
    correct: 'Damasco',
    reference: '2 Corintios 11:32-33',
    explanation: '',
    difficulty: 'very_hard',
  },
  {
    question: '¿En qué ciudades puso Jeroboam los becerros de oro?',
    options: ['Bet-el y Dan', 'Bet-el y Hai', 'Siquem y Bet-el', 'Hiram y Dan'],
    correct: 'Bet-el y Dan',
    reference: '1 Reyes 12:28-29',
    explanation: '',
    difficulty: 'very_hard',
  },
  {
    question:
      '¿Cuál fue el nombre de la esposa de Herodes que se había casado con su hermano Felipe?',
    options: ['Herodías', 'Adalía', 'Zila', 'Salomé'],
    correct: 'Herodías',
    reference: 'Mateo 14:3',
    explanation: '',
    difficulty: 'very_hard',
  },
  {
    question:
      '¿Quién reinó por seis años en Israel y empezó su reinado matando a todos sus nietos menos a uno?',
    options: ['Atalía', 'Josabar', 'Jedida', 'Amalía'],
    correct: 'Atalía',
    reference: '2 Reyes 11',
    explanation: '',
    difficulty: 'very_hard',
  },
  {
    question:
      '¿Cómo se llamaba el sacerdote encargado del cuidado del pequeño Samuel?',
    options: ['Elí', 'Isaí', 'Elcana', 'Ananías'],
    correct: 'Elí',
    reference: '1 Samuel 1',
    explanation: '',
    difficulty: 'medium',
  },
  {
    question:
      '¿Gracias a qué emperador persa pudo Nehemías reconstruir los muros de la ciudad de Jerusalén?',
    options: ['Artajerjes', 'Ciro', 'Belsasar', 'Nabucodonosor'],
    correct: 'Artajerjes',
    reference: 'Nehemías 2',
    explanation: '',
    difficulty: 'hard',
  },
  {
    question: '¿Quién fue puesto en una horca que él mismo había preparado?',
    options: ['Amán', 'Mardoqueo', 'Anías', 'Asuero'],
    correct: 'Amán',
    reference: 'Ester 7:10',
    explanation: '',
    difficulty: 'medium',
  },
  {
    question: "¿Quién dijo: '¿De Nazaret puede salir algo de bueno?'?",
    options: ['Natanael', 'Felipe', 'Andrés', 'Herodes'],
    correct: 'Natanael',
    reference: 'Juan 1:46',
    explanation: '',
    difficulty: 'medium',
  },
  {
    question:
      '¿Qué nombre puso Jacob al lugar donde soñó con una escalera que ascendía al cielo?',
    options: ['Bet-el', 'Gilgal', 'Eben-ezer', 'Luz'],
    correct: 'Bet-el',
    reference: 'Génesis 28:10-22',
    explanation: '',
    difficulty: 'hard',
  },
  {
    question: '¿Qué profesión ejercía Lucas?',
    options: ['Médico', 'Pescador', 'Pastor', 'Recaudador de impuestos'],
    correct: 'Médico',
    reference: 'Colosenses 4:14',
    explanation: '',
    difficulty: 'medium',
  },
  {
    question:
      '¿Quién fue juez en Israel durante 20 años en tiempos de los filisteos?',
    options: ['Sansón', 'Jefté', 'Gedeón', 'Otro'],
    correct: 'Sansón',
    reference: 'Jueces 15:20',
    explanation: '',
    difficulty: 'medium',
  },
  {
    question:
      '¿Cuántos días pasó Jesús en el desierto después de ser bautizado?',
    options: ['40 días', '30 días', '7 días', '120 días'],
    correct: '40 días',
    reference: 'Marcos 1:13',
    explanation: '',
    difficulty: 'easy',
  },
  {
    question: '¿Cuántas veces fue tentado Jesús en el desierto?',
    options: ['3 veces', '1 vez', '2 veces', '4 veces'],
    correct: '3 veces',
    reference: 'Mateo 4',
    explanation: '',
    difficulty: 'easy',
  },
  {
    question: '¿Cuál fue la primera plaga de Egipto?',
    options: [
      'Las aguas se tornan en sangre',
      'Las ranas',
      'Los piojos',
      'Las serpientes',
    ],
    correct: 'Las aguas se tornan en sangre',
    reference: 'Éxodo 7:14-25',
    explanation: '',
    difficulty: 'easy',
  },
  {
    question: "¿Quién dijo 'Yo sé que mi Redentor vive'?",
    options: ['Job', 'David', 'Salomón', 'Isaías'],
    correct: 'Job',
    reference: 'Job 19:25',
    explanation: '',
    difficulty: 'medium',
  },
  {
    question: '¿Cómo se llamaba la mujer de Abraham?',
    options: ['Sarai', 'Raquel', 'Milca', 'Séfora'],
    correct: 'Sarai',
    reference: 'Génesis 11:29',
    explanation: '',
    difficulty: 'easy',
  },
  {
    question: '¿En que día de la creación Dios hizo los árboles y las plantas?',
    options: ['Tercero', 'Primero', 'Cuarto', 'Segundo'],
    correct: 'Tercero',
    reference: 'Génesis 1:12-13',
    explanation: '',
    difficulty: 'easy',
  },
  {
    question: '¿Qué relación tenía Mardoqueo con Ester?',
    options: ['Primo', 'Tío', 'Padre', 'Hermano'],
    correct: 'Primo',
    reference: 'Ester 2:7',
    explanation: '',
    difficulty: 'medium',
  },
  {
    question:
      "¿A quién dijo Jesús: 'Ve al mar, y echa el anzuelo, y el primer pez que saques, tómalo, y al abrirle la boca, hallarás un estatero'?",
    options: ['Pedro', 'Juan', 'Andrés', 'Tomás'],
    correct: 'Pedro',
    reference: 'Mateo 17:24-27',
    explanation: '',
    difficulty: 'hard',
  },
  {
    question:
      '¿De qué tipo de madera estaban hechos los querubines del lugar Santísimo del templo de Salomón?',
    options: ['Olivo', 'Acacia', 'Roble', 'Cedro'],
    correct: 'Olivo',
    reference: '1 Reyes 6:23',
    explanation: '',
    difficulty: 'very_hard',
  },
  {
    question: "¿Quién es el 'Padre de la Fe'?",
    options: ['Abraham', 'Jesús', 'Moisés', 'Pedro'],
    correct: 'Abraham',
    reference: '',
    explanation: '',
    difficulty: 'medium',
  },
  {
    question: '¿Quién fue el mejor amigo de David?',
    options: ['Jonatán', 'Saúl', 'Samuel', 'Joab'],
    correct: 'Jonatán',
    reference: '',
    explanation: '',
    difficulty: 'easy',
  },
  {
    question: '¿Con quién se casó Booz?',
    options: ['Rut', 'Abigail', 'Ester', 'Elisabet'],
    correct: 'Rut',
    reference: 'Rut 4:13',
    explanation: '',
    difficulty: 'medium',
  },
  {
    question: '¿Quién escribió el libro de Ezequías?',
    options: ['No existe', 'Joel', 'Ezequías', 'Isaías'],
    correct: 'No existe',
    reference: 'Es Ezequiel',
    explanation: '',
    difficulty: 'medium',
  },
  {
    question:
      "¿A quién se refiere Isaías con 'Voz que clama en el desierto: Preparad camino a Jehová'?",
    options: ['Juan el Bautista', 'Elías', 'Jesús', 'David'],
    correct: 'Juan el Bautista',
    reference: 'Mateo 3:3',
    explanation: '',
    difficulty: 'hard',
  },
  {
    question:
      "¿Quién dijo 'Señor, si hubieses estado aquí, mi hermano no habría muerto'?",
    options: ['Marta y María', 'Marta', 'La viuda de Serepta', 'Lázaro'],
    correct: 'Marta y María',
    reference: 'Juan 11:21 y Juan 11:32',
    explanation: '',
    difficulty: 'medium',
  },
  {
    question: '¿Dónde vivía Tabita la discípula?',
    options: ['Jope', 'Damasco', 'Tarso', 'Jerusalén'],
    correct: 'Jope',
    reference: 'Hechos 9:36',
    explanation: '',
    difficulty: 'very_hard',
  },
  {
    question:
      '¿En qué ciudad ascendió Jesús a los cielos después de resucitar y bendecir a sus discipulos?',
    options: ['Betania', 'Galilea', 'Capernaúm', 'Nazaret'],
    correct: 'Betania',
    reference: 'Lucas 24:50-51',
    explanation: '',
    difficulty: 'very_hard',
  },
  {
    question: '¿Quién dirigió la reconstrucción del muro de Jerusalén?',
    options: ['Nehemías', 'Esdras', 'Ciro', 'Artajerjes'],
    correct: 'Nehemías',
    reference: 'Nehemías 2',
    explanation: '',
    difficulty: 'medium',
  },
  {
    question: '¿Quién mató a seiscientos filisteos con una aguijada de buey?',
    options: ['Samgar', 'Sansón', 'Otoniel', 'Barac'],
    correct: 'Samgar',
    reference: 'Jueces 3:31',
    explanation: '',
    difficulty: 'hard',
  },
  {
    question: '¿Quién iba a maldecir a Israel, pero tuvo que bendecirlos?',
    options: ['Balaam', 'Balac', 'Jozabad', 'Semaías'],
    correct: 'Balaam',
    reference: 'Números 22',
    explanation: '',
    difficulty: 'medium',
  },
  {
    question:
      '¿Quién se convirtió en el primer rey de las 10 tribus que se separaron?',
    options: ['Jeroboam', 'Roboam', 'Salomón', 'Zimri'],
    correct: 'Jeroboam',
    reference: '1 Reyes 12:20',
    explanation: '',
    difficulty: 'medium',
  },
  {
    question: '¿Quién aconsejó a David que no matara a su necio marido Nabal?',
    options: ['Abigail', 'Betsabé', 'Mical', 'Ana'],
    correct: 'Abigail',
    reference: '1 Samuel 25:23-26',
    explanation: '',
    difficulty: 'medium',
  },
  {
    question:
      '¿Quién fue reprendido por Pablo por negarse a comer con los gentiles?',
    options: ['Pedro', 'Bernabé', 'Lucas', 'Aquila'],
    correct: 'Pedro',
    reference: 'Gálatas 2:11-21',
    explanation: '',
    difficulty: 'medium',
  },
  {
    question:
      '¿En qué lugar Elías tuvo un enfrentamiento con los profetas de Baal?',
    options: ['Monte Carmelo', 'Monte Sion', 'Monte Sinaí', 'Monte Ararat'],
    correct: 'Monte Carmelo',
    reference: '1 Reyes 18:19-21',
    explanation: '',
    difficulty: 'medium',
  },
  {
    question:
      '¿En qué lugar los creyentes fueron llamados “cristianos” por primera vez?',
    options: ['Antioquía', 'Corintos', 'Jerusalén', 'Éfeso'],
    correct: 'Antioquía',
    reference: 'Hechos 11:26',
    explanation: '',
    difficulty: 'medium',
  },
  {
    question: '¿A qué lugar se dirigía Pablo cuando fue cegado en el camino?',
    options: ['Damasco', 'Tarsis', 'Jerusalén', 'Samaria'],
    correct: 'Damasco',
    reference: 'Hechos 9:3',
    explanation: '',
    difficulty: 'medium',
  },
  {
    question:
      '¿Cuál es el nombre del río en el cual estaba Ezequiel con los exiliados cuando recibió una visión de Dios?',
    options: ['Quebar', 'Jordán', 'Gihón', 'Éufrates'],
    correct: 'Quebar',
    reference: 'Ezequiel 1:1',
    explanation: '',
    difficulty: 'hard',
  },
  {
    question:
      '¿En qué libro se encuentra una descripción de la armadura de Dios?',
    options: ['Efesios 6', '1 Corintios 6', 'Gálatas 3', 'Colosenses 3'],
    correct: 'Efesios 6',
    reference: '',
    explanation: '',
    difficulty: 'hard',
  },
  {
    question: '¿Quién fue llamado el incrédulo?',
    options: ['Tomás', 'Felipe', 'Juan', 'Simón'],
    correct: 'Tomás',
    reference: 'Juan 20:27',
    explanation: '',
    difficulty: 'medium',
  },
  {
    question: '¿Quién fue llamado rama fructífera?',
    options: ['José', 'David', 'Jesús', 'Abraham'],
    correct: 'José',
    reference: 'Génesis 49:22',
    explanation: '',
    difficulty: 'very_hard',
  },
  {
    question: '¿Quién es el dulce cantor de Israel?',
    options: ['David', 'Daniel', 'Salomón', 'Moisés'],
    correct: 'David',
    reference: '2 Samuel 23:1',
    explanation: '',
    difficulty: 'medium',
  },
  {
    question: '¿Cuantas estrellas se inclinaron ante José en su sueño?',
    options: ['11', '14', '12', '13'],
    correct: '11',
    reference: 'Génesis 37:9',
    explanation: '',
    difficulty: 'hard',
  },
  {
    question: '¿Cuántos años tardó Salomón para construir el templo?',
    options: ['7 años', '12 años', '20 años', '40 años'],
    correct: '7 años',
    reference: '1 Reyes 6:38',
    explanation: '',
    difficulty: 'very_hard',
  },
  {
    question: '¿Por quién se dió 20 piezas de plata?',
    options: ['José', 'Jesús', 'Rebeca', 'Ester'],
    correct: 'José',
    reference: 'Génesis 37:28',
    explanation: '',
    difficulty: 'medium',
  },
  {
    question:
      '¿Quién fue el gobernador romano que sentenció a muerte a Cristo?',
    options: ['Pilato', 'Nerón', 'Julio Cesar', 'Herodes'],
    correct: 'Pilato',
    reference: 'Mateo 27',
    explanation: '',
    difficulty: 'medium',
  },
  {
    question: '¿Cuántas personas estuvieron en el arca de Noé?',
    options: ['Ocho', 'Siete', 'Seis', 'Nueve'],
    correct: 'Ocho',
    reference: 'Génesis 7:13',
    explanation: '',
    difficulty: 'medium',
  },
  {
    question: '¿Qué significa epístola?',
    options: ['Carta', 'Evangelio', 'Buenas nuevas', 'Salvación'],
    correct: 'Carta',
    reference: '',
    explanation: '',
    difficulty: 'medium',
  },
  {
    question:
      '¿Cuál era la fiesta del A.T. que recordaba cuando Dios salvó a los primogénitos de Israel la noche que salieron de Egipto?',
    options: [
      'La Pascua',
      'La fiesta de los panes',
      'Fiesta de la cosecha',
      'La fiesta de Purim',
    ],
    correct: 'La Pascua',
    reference: 'Éxodo 12',
    explanation: '',
    difficulty: 'medium',
  },
  {
    question: '¿Cuáles de éstos animales hablaron?',
    options: [
      'La serpiente y el asna',
      'La serpiente y el cordero',
      'El asna y el dragón',
      'El dragón y el cordero',
    ],
    correct: 'La serpiente y el asna',
    reference: 'Génesis 3:1 y Números 22:28',
    explanation: '',
    difficulty: 'medium',
  },
  {
    question: '¿Con cuál mujer cometió adulterio David?',
    options: ['Betsabé', 'Elisabet', 'Mical', 'Abigail'],
    correct: 'Betsabé',
    reference: '2 Samuel 11',
    explanation: '',
    difficulty: 'medium',
  },
  {
    question:
      '¿Cuál era la tribu de Israel encargada del sacerdocio y por tanto apartada para Jehová?',
    options: ['Leví', 'Judá', 'Benjamín', 'Zabulón'],
    correct: 'Leví',
    reference: '',
    explanation: '',
    difficulty: 'easy',
  },
  {
    question:
      'En la armadura de Dios que describe Pablo ¿qué representa el yelmo?',
    options: ['Salvación', 'Espíritu', 'Verdad', 'Fe'],
    correct: 'Salvación',
    reference: 'Efesios 6:17',
    explanation: '',
    difficulty: 'hard',
  },
  {
    question: '¿Cuántos hijos varones tuvo Jacob?',
    options: ['Doce', 'Trece', 'Once', 'Diéz'],
    correct: 'Doce',
    reference: 'Génesis 29:31-35:18',
    explanation: '',
    difficulty: 'medium',
  },
  {
    question: '¿Con quién comparaban a Juan el Bautista?',
    options: ['Elías', 'Eliseo', 'Samuel', 'Isaías'],
    correct: 'Elías',
    reference: 'Mateo 11:7-14',
    explanation: '',
    difficulty: 'medium',
  },
  {
    question: '¿Qué edad tenía Abraham cuando nació Isaac?',
    options: ['100 años', '86 años', '102 años', '110 años'],
    correct: '100 años',
    reference: 'Génesis 21:5',
    explanation: '',
    difficulty: 'medium',
  },
  {
    question: '¿Cuál es el libro que está entre Oseas y Amós?',
    options: ['Joel', 'Abdías', 'Jonás', 'Daniel'],
    correct: 'Joel',
    reference: '',
    explanation: '',
    difficulty: 'hard',
  },
  {
    question: '¿A qué tierra Abraham llevó a Isaac para sacrificarlo?',
    options: ['Moriah', 'Ur', 'Mambre', 'Beerseba'],
    correct: 'Moriah',
    reference: 'Génesis 22:2',
    explanation: '',
    difficulty: 'very_hard',
  },
  {
    question:
      '¿En cuál evangelio NO se narra el encuentro de Jesús con el hombre rico?',
    options: ['Juan', 'Mateo', 'Marcos', 'Lucas'],
    correct: 'Juan',
    reference: 'Mateo 19:15-17, Marcos 10:16-18, Lucas 18:17-19',
    explanation: '',
    difficulty: 'very_hard',
  },
  {
    question:
      '¿A qué rey se le secó la mano cuando intentó prender a un varón de Dios?',
    options: ['Jeroboam', 'Roboam', 'Uzías', 'Josafat'],
    correct: 'Jeroboam',
    reference: '1 Reyes 13:4',
    explanation: '',
    difficulty: 'hard',
  },
  {
    question: '¿Quién es nuestro abogado en el cielo?',
    options: ['Jesús', 'Pablo', 'Abraham', 'El Papa'],
    correct: 'Jesús',
    reference: '1 Juan 2:1',
    explanation: '',
    difficulty: 'easy',
  },
  {
    question: '¿Cuál de los siguientes libros fue escrito por varios autores?',
    options: ['Salmos', 'Génesis', 'Éxodo', 'Lucas'],
    correct: 'Salmos',
    reference: '',
    explanation: '',
    difficulty: 'medium',
  },
  {
    question:
      '¿Cuánto tiempo pasó desde que dejó de llover en el diluvio hasta que la tierra se secó?',
    options: ['150 días', '40 días', '120 días', '7 días'],
    correct: '150 días',
    reference: 'Génesis 7:24',
    explanation: '',
    difficulty: 'hard',
  },
  {
    question: '¿Cuántas mujeres entraron en el Arca de Noé?',
    options: ['Cuatro', 'Una', 'Dos', 'Tres'],
    correct: 'Cuatro',
    reference: 'Génesis 7:13',
    explanation: '',
    difficulty: 'medium',
  },
  {
    question: '¿Qué libro de la Biblia se encuentra entre Ester y Job?',
    options: ['Ninguno', 'Salmos', 'Proverbios', 'Nehemías'],
    correct: 'Ninguno',
    reference: '',
    explanation: '',
    difficulty: 'medium',
  },
  {
    question:
      '¿Cómo se llamaba el siervo del sumo sacerdote, al cual Pedro le cortó una oreja?',
    options: ['Malco', 'Jairo', 'Eliud', 'Simón'],
    correct: 'Malco',
    reference: 'Juan 18:10',
    explanation: '',
    difficulty: 'very_hard',
  },
  {
    question: '¿Cuál fue el número de concubinas de Salomón?',
    options: ['300', '700', '1000', '500'],
    correct: '300',
    reference: '1 Reyes 11:3',
    explanation: '',
    difficulty: 'very_hard',
  },
  {
    question: "¿Cómo se traduce 'Emanuel'?",
    options: [
      'Dios con nosotros',
      'Dios nuestro',
      'Bendito de Dios',
      'Principe de paz',
    ],
    correct: 'Dios con nosotros',
    reference: 'Mateo 1:23',
    explanation: '',
    difficulty: 'hard',
  },
  {
    question: '¿Cuál es el ultimo libro del Antiguo Testamento?',
    options: ['Malaquías', 'Zacarías', 'Oseas', 'Habacuc'],
    correct: 'Malaquías',
    reference: '',
    explanation: '',
    difficulty: 'medium',
  },
  {
    question:
      '¿En que capítulo del libro de Isaías se describe detalladamente al Mesías?',
    options: ['53', '23', '55', '56'],
    correct: '53',
    reference: '',
    explanation: '',
    difficulty: 'medium',
  },
  {
    question: '¿Quién fue el padre de Maher-salal-hasbaz?',
    options: ['Isaías', 'Nabucodonosor', 'Nehemías', 'Artajerjes'],
    correct: 'Isaías',
    reference: 'Isaías 8:3',
    explanation: '',
    difficulty: 'very_hard',
  },
  {
    question:
      '¿Cuáles eran las dimensiones (en codos) del arca construida por Noé?',
    options: [
      '300 x 50 x 30',
      '300 x 30 x 20',
      '200 x 50 x 30',
      '200 x 45 x 30',
    ],
    correct: '300 x 50 x 30',
    reference: 'Génesis 6:15',
    explanation: '',
    difficulty: 'very_hard',
  },
  {
    question:
      '¿De qué material fue hecha el Arca del Pacto para el Tabernáculo en los tiempos de Moisés?',
    options: ['Acacia', 'Oro', 'Olivo', 'Cedro'],
    correct: 'Acacia',
    reference: 'Éxodo 25:10',
    explanation: '',
    difficulty: 'very_hard',
  },
  {
    question:
      '¿Quién construyó el Arca del Pacto para el Tabernáculo en los tiempos de Moisés?',
    options: ['Bezaleel', 'Aholiab', 'Aarón', 'Quelal'],
    correct: 'Bezaleel',
    reference: 'Éxodo 37:1',
    explanation: '',
    difficulty: 'very_hard',
  },
  {
    question: "¿Qué es 'Azazel'?",
    options: ['Una cabra', 'Un dios pagano', 'Una ciudad', 'Un monte'],
    correct: 'Una cabra',
    reference: 'Levítico 16:26',
    explanation: '',
    difficulty: 'very_hard',
  },
  {
    question: "¿Quién dijo '¿Soy yo perro, para que vengas a mí con palos?'?",
    options: ['Goliat', 'Acab', 'Absalón', 'Roboam'],
    correct: 'Goliat',
    reference: '1 Samuel 17:43',
    explanation: '',
    difficulty: 'hard',
  },
  {
    question: "¿Quién dijo '¿quién podrá gobernar este tu pueblo tan grande?'?",
    options: ['Salomón', 'Josué', 'Moisés', 'Saúl'],
    correct: 'Salomón',
    reference: '1 Reyes 3:9',
    explanation: '',
    difficulty: 'hard',
  },
  {
    question:
      "¿Quién dijo 'He aquí el fuego y la leña; mas ¿dónde está el cordero para el holocausto?'?",
    options: ['Isaac', 'Abraham', 'Jacob', 'Cam'],
    correct: 'Isaac',
    reference: 'Génesis 22:7',
    explanation: '',
    difficulty: 'medium',
  },
  {
    question:
      "¿Quién dijo 'Ordena que en tu reino se sienten estos dos hijos míos, el uno a tu derecha, y el otro a tu izquierda'?",
    options: [
      'La mujer de Zebedeo',
      'La mujer de Felipe',
      'La mujer de Zaqueo',
      'La mujer de Santiago',
    ],
    correct: 'La mujer de Zebedeo',
    reference: 'Mateo 20:21',
    explanation: '',
    difficulty: 'very_hard',
  },
  {
    question: "¿Quién dijo 'Si perezco, que perezca'?",
    options: ['Ester', 'Rut', 'Sara', 'Ana'],
    correct: 'Ester',
    reference: 'Ester 4:16',
    explanation: '',
    difficulty: 'medium',
  },
  {
    question: "¿En qué capítulo se encuentra 'Satanás atado por mil años'?",
    options: [
      'Apocalipsis 20',
      'Apocalipsis 21',
      'Apocalipsis 19',
      'Apocalipsis 22',
    ],
    correct: 'Apocalipsis 20',
    reference: '',
    explanation: '',
    difficulty: 'hard',
  },
  {
    question: "¿En qué capítulo se encuentra 'El Sermón del monte'?",
    options: ['Mateo 5', 'Mateo 6', 'Mateo 7', 'Mateo 10'],
    correct: 'Mateo 5',
    reference: '',
    explanation: '',
    difficulty: 'hard',
  },
  {
    question: '¿Cuál profeta se casa con una prostituta?',
    options: ['Oseas', 'Joel', 'Abdías', 'Amós'],
    correct: 'Oseas',
    reference: 'Oseas 1',
    explanation: '',
    difficulty: 'hard',
  },
  {
    question: '¿Quién apareció con Jesús en la Transfiguración?',
    options: [
      'Moisés y Elías',
      'Enoc y Elías',
      'Moisés e Isaías',
      'Eliseo y Elías',
    ],
    correct: 'Moisés y Elías',
    reference: 'Mateo 17:3',
    explanation: '',
    difficulty: 'medium',
  },
  {
    question:
      '¿En que libro del A.T. se encuentran las palabras “Dios mío, Dios mío, ¿por qué me has desamparado?”?',
    options: ['Salmos', 'Jeremías', '1 Reyes', 'Eclesiastés'],
    correct: 'Salmos',
    reference: 'Salmos 22:1',
    explanation: '',
    difficulty: 'hard',
  },
  {
    question: '¿A qué edad murió Noé?',
    options: ['950 años', '930 años', '955 años', '940 años'],
    correct: '950 años',
    reference: 'Génesis 9:29',
    explanation: '',
    difficulty: 'hard',
  },
  {
    question: '¿A qué edad murió Moisés?',
    options: ['120 años', '110 años', '130 años', '100 años'],
    correct: '120 años',
    reference: 'Deuteronomio 34:1-12',
    explanation: '',
    difficulty: 'hard',
  },
  {
    question: '¿Cuál era la estatura de Goliat?',
    options: [
      '6 codos y un palmo',
      '6 codos y 1/2 palmo',
      '6 codos y 2 palmos',
      '6 codos y 3 palmos',
    ],
    correct: '6 codos y un palmo',
    reference: '1 Samuel 17:4',
    explanation: '',
    difficulty: 'medium',
  },
  {
    question:
      'El profeta me mando 7 veces a bañar, tenía que obedecerle, para mi lepra poder sanar',
    options: ['Naamán', 'Felipe', 'Eunuco', 'Eliseo'],
    correct: 'Naamán',
    reference: '2 Reyes 5:1-27',
    explanation: '',
    difficulty: 'medium',
  },
  {
    question: '¿Quién bautizó a Jesús?',
    options: ['Pedro', 'Juan el Bautista', 'Santiago', 'Andrés'],
    correct: 'Juan el Bautista',
    reference: 'Mateo 3:13-17',
    explanation: 'Juan el Bautista bautizó a Jesús en el río Jordán.',
    difficulty: 'easy',
  },
];
