type BookChapter = {
  [key: string]: string;
};

export const cdnUrl = `https://cdn.jsdelivr.net/gh/pauloluan/cdn/images/bible/testament`;

export const BOOK_IMAGES: BookChapter = {
  Génesis: `${cdnUrl}/old/gen-1--Eq0CRx.png`,
  Éxodo: `${cdnUrl}/old/exo-1.png`,
  Levítico: `${cdnUrl}/old/lev.png`,
  Números: `${cdnUrl}/old/num.png`,
  Deuteronomio: `${cdnUrl}/old/deut.png`,
  Josué: `${cdnUrl}/old/josh.png`,
  Jueces: `${cdnUrl}/old/judg.png`,
  Rut: `${cdnUrl}/old/ruth.png`,
  "1 Samuel": `${cdnUrl}/old/sam-1.png`,
  "2 Samuel": `${cdnUrl}/old/sam-2.png`,
  "1 Reyes": `${cdnUrl}/old/kings.png`,
  "2 Reyes": `${cdnUrl}/old/kings.png`, // assuming it's the same image as 1 Kings
  "1 Crónicas": `${cdnUrl}/old/chron.png`,
  "2 Crónicas": `${cdnUrl}/old/chron.png`, // assuming it's the same image as 1 Chronicles
  Esdras: `${cdnUrl}/old/ezra-neh.png`,
  Nehemías: `${cdnUrl}/old/ezra-neh.png`, // assuming it's the same image as Ezra
  Ester: `${cdnUrl}/old/est.png`,
  Job: `${cdnUrl}/old/job.png`,
  Salmos: `${cdnUrl}/old/psa.png`,
  Proverbios: `${cdnUrl}/old/prov.png`,
  Eclesiastés: `${cdnUrl}/old/eccles.png`,
  "Cantar de los Cantares": `${cdnUrl}/old/song.png`,
  Isaías: `${cdnUrl}/old/isa-1.png`,
  Jeremías: `${cdnUrl}/old/jer.png`,
  Lamentaciones: `${cdnUrl}/old/lam.png`,
  Ezequiel: `${cdnUrl}/old/ezek-1.png`,
  Daniel: `${cdnUrl}/old/dan.png`,
  Oseas: `${cdnUrl}/old/hos.png`,
  Joel: `${cdnUrl}/old/joel.png`,
  Amós: `${cdnUrl}/old/amos.png`,
  Abdías: `${cdnUrl}/old/obad.png`,
  Jonás: `${cdnUrl}/old/jonah.png`,
  Miqueas: `${cdnUrl}/old/mic.png`,
  Nahum: `${cdnUrl}/old/nah.png`,
  Habacuc: `${cdnUrl}/old/hab.png`,
  Sofonías: `${cdnUrl}/old/zeph.png`,
  Hageo: `${cdnUrl}/old/hag.png`,
  Zacarías: `${cdnUrl}/old/zech.png`,
  Malaquías: `${cdnUrl}/old/mal.png`,
  Mateo: `${cdnUrl}/new/matt-1.png`,
  Marcos: `${cdnUrl}/new/mark.png`,
  Lucas: `${cdnUrl}/new/luke-1.png`,
  Juan: `${cdnUrl}/new/john-gospel-1.png`,
  "Hechos de los Apóstoles": `${cdnUrl}/new/acts-1.png`,
  Romanos: `${cdnUrl}/new/rom-1.png`,
  "1 Corintios": `${cdnUrl}/new/cor-1.png`,
  "2 Corintios": `${cdnUrl}/new/cor-2.png`,
  Gálatas: `${cdnUrl}/new/gal.png`,
  Efesios: `${cdnUrl}/new/eph.png`,
  Filipenses: `${cdnUrl}/new/phil.png`,
  Colosenses: `${cdnUrl}/new/col.png`,
  "1 Tesalonicenses": `${cdnUrl}/new/thes-1.png`,
  "2 Tesalonicenses": `${cdnUrl}/new/thes-2.png`,
  "1 Timoteo": `${cdnUrl}/new/tim-1.png`,
  "2 Timoteo": `${cdnUrl}/new/tim-2.png`,
  Tito: `${cdnUrl}/new/titus.png`,
  Filemón: `${cdnUrl}/new/philem.png`,
  Hebreos: `${cdnUrl}/new/heb.png`,
  Santiago: `${cdnUrl}/new/james.png`,
  "1 Pedro": `${cdnUrl}/new/peter-1.png`,
  "2 Pedro": `${cdnUrl}/new/peter-2.png`,
  "1 Juan": `${cdnUrl}/new/john-letters-1-3.png`,
  "2 Juan": `${cdnUrl}/new/john-letters-1-3.png`,
  "3 Juan": `${cdnUrl}/new/john-letters-1-3.png`,
  Judas: `${cdnUrl}/new/jude.png`,
  "Apocalipsis (de Juan)": `${cdnUrl}/new/rev-1.png`,
};
