import { SpeechVoice } from "@/types";

const Voices: SpeechVoice[] = [
  {
    identifier: "es-us-x-sfb-network",
    language: "es-US",
    name: "Sofía Bell",
    quality: "Enhanced",
    isMale: false,
  },
  {
    identifier: "es-US-language",
    language: "es-US",
    name: "Daniela Suárez",
    quality: "Enhanced",
    isMale: false,
  },
  {
    identifier: "es-us-x-esc-network",
    language: "es-US",
    name: "Elena Sánchez",
    quality: "Enhanced",
    isMale: false,
  },
  {
    identifier: "es-es-x-eee-local",
    language: "es-ES",
    name: "kristin Doe",
    quality: "Enhanced",
    isMale: false,
  },
  {
    identifier: "es-us-x-esd-local",
    language: "es-US",
    name: "Santiago Urrutia",
    quality: "Enhanced",
    isMale: true,
  },
  {
    identifier: "es-es-x-eef-local",
    language: "es-ES",
    name: "Carlos Fernández",
    quality: "Enhanced",
    isMale: true,
  },
  {
    identifier: "es-es-x-eec-network",
    language: "es-ES",
    name: "Ana López",
    quality: "Enhanced",
    isMale: false,
  },
  {
    identifier: "es-es-x-eea-local",
    language: "es-ES",
    name: "Pedronila García",
    quality: "Enhanced",
    isMale: false,
  },
  {
    identifier: "es-es-x-eea-network",
    language: "es-ES",
    name: "María Gómez",
    quality: "Enhanced",
    isMale: false,
  },
  {
    identifier: "ca-es-x-caf-network",
    language: "ca-ES",
    name: "Joanna Costa",
    quality: "Enhanced",
    isMale: false,
  },
  {
    identifier: "es-us-x-esf-local",
    language: "es-US",
    name: "Fernando Silva",
    quality: "Enhanced",
    isMale: true,
  },
  {
    identifier: "es-us-x-esc-local",
    language: "es-US",
    name: "Catalina Reyes",
    quality: "Enhanced",
    isMale: false,
  },
  {
    identifier: "es-es-x-eed-local",
    language: "es-ES",
    name: "Miguel Martínez",
    quality: "Enhanced",
    isMale: true,
  },
  {
    identifier: "es-us-x-esf-network",
    language: "es-US",
    name: "Raúl Fernández",
    quality: "Enhanced",
    isMale: true,
  },
  {
    identifier: "es-us-x-sfb-local",
    language: "es-US",
    name: "Isabel Bravo",
    quality: "Enhanced",
    isMale: false,
  },
  {
    identifier: "es-ES-language",
    language: "es-ES",
    name: "Alejandra Vargas",
    quality: "Enhanced",
    isMale: false,
  },
  {
    identifier: "es-es-x-eed-network",
    language: "es-ES",
    name: "Leudy Fernández",
    quality: "Enhanced",
    isMale: true,
  },
  {
    identifier: "ca-es-x-caf-local",
    language: "ca-ES",
    name: "Roe Roca",
    quality: "Enhanced",
    isMale: false,
  },
  {
    identifier: "es-es-x-eec-local",
    language: "es-ES",
    name: "Rosa Moreno",
    quality: "Enhanced",
    isMale: false,
  },
  {
    identifier: "es-us-x-esd-network",
    language: "es-US",
    name: "Valerio Ramírez",
    quality: "Enhanced",
    isMale: true,
  },
];

export default Voices;
