export default [
  {
    identifier: "es-us-x-sfb-network",
    language: "es-US",
    name: "es-us-x-sfb-network",
    quality: "Enhanced",
  },
  {
    identifier: "es-US-language",
    language: "es-US",
    name: "es-US-language",
    quality: "Enhanced",
  },
  {
    identifier: "es-us-x-esc-network",
    language: "es-US",
    name: "es-us-x-esc-network",
    quality: "Enhanced",
  },
  {
    identifier: "es-es-x-eee-local",
    language: "es-ES",
    name: "es-es-x-eee-local",
    quality: "Enhanced",
  },
  {
    identifier: "es-us-x-esd-local",
    language: "es-US",
    name: "es-us-x-esd-local",
    quality: "Enhanced",
  },
  {
    identifier: "es-es-x-eef-local",
    language: "es-ES",
    name: "es-es-x-eef-local",
    quality: "Enhanced",
  },
  {
    identifier: "es-es-x-eec-network",
    language: "es-ES",
    name: "es-es-x-eec-network",
    quality: "Enhanced",
  },
  {
    identifier: "es-es-x-eea-local",
    language: "es-ES",
    name: "es-es-x-eea-local",
    quality: "Enhanced",
  },
  {
    identifier: "es-es-x-eea-network",
    language: "es-ES",
    name: "es-es-x-eea-network",
    quality: "Enhanced",
  },
  {
    identifier: "ca-es-x-caf-network",
    language: "ca-ES",
    name: "ca-es-x-caf-network",
    quality: "Enhanced",
  },
  {
    identifier: "es-us-x-esf-local",
    language: "es-US",
    name: "es-us-x-esf-local",
    quality: "Enhanced",
  },
  {
    identifier: "es-us-x-esc-local",
    language: "es-US",
    name: "es-us-x-esc-local",
    quality: "Enhanced",
  },
  {
    identifier: "es-es-x-eed-local",
    language: "es-ES",
    name: "es-es-x-eed-local",
    quality: "Enhanced",
  },
  {
    identifier: "es-us-x-esf-network",
    language: "es-US",
    name: "es-us-x-esf-network",
    quality: "Enhanced",
  },
  {
    identifier: "es-us-x-sfb-local",
    language: "es-US",
    name: "es-us-x-sfb-local",
    quality: "Enhanced",
  },
  {
    identifier: "es-ES-language",
    language: "es-ES",
    name: "es-ES-language",
    quality: "Enhanced",
  },
  {
    identifier: "es-es-x-eed-network",
    language: "es-ES",
    name: "es-es-x-eed-network",
    quality: "Enhanced",
  },
  {
    identifier: "ca-es-x-caf-local",
    language: "ca-ES",
    name: "ca-es-x-caf-local",
    quality: "Enhanced",
  },
  {
    identifier: "es-es-x-eec-local",
    language: "es-ES",
    name: "es-es-x-eec-local",
    quality: "Enhanced",
  },
  {
    identifier: "es-us-x-esd-network",
    language: "es-US",
    name: "es-us-x-esd-network",
    quality: "Enhanced",
  },
];
